// Generated by large_library_splitter.dart; keep changes in the source library.
part of 'admin_training_api_test.dart';

void _registeradmin_training_api_testCases02() {
  test('training rezka order gets a Laminatsiya input batch on generation',
      () async {
    await TestModeController.instance.setEnabled(true);
    const apparatus = _rezkaApparatusId;
    final result =
        await MobileApi.instance.adminSaveTrainingProductionMapWithOrder(
      map: const ProductionMapDefinition(
        id: 'zakaz-draft-rezka-input-1',
        productCode: 'TRAINING-REZKA-1',
        title: 'Training rezka order',
        orderKg: 10,
        nodes: [
          ProductionMapNode(id: 'start', kind: 'start', title: 'Start'),
          ProductionMapNode(
            id: 'rezka',
            kind: 'apparatus',
            title: _rezkaApparatusName,
            apparatusId: apparatus,
          ),
          ProductionMapNode(id: 'end', kind: 'end', title: 'End'),
        ],
        edges: [
          ProductionMapEdge(from: 'start', to: 'rezka'),
          ProductionMapEdge(from: 'rezka', to: 'end'),
        ],
      ),
      template: CalculateOrderTemplate.fromJson(const {
        'name': 'Training rezka order',
        'product': 'Training rezka order',
        'frame_product_size_mm': 200,
        'frame_count': 4,
        'width_mm': 810,
        'waste_percent': 5,
      }),
    );
    final saved = result.saved;
    expect(
      saved.map.nodes.firstWhere((node) => node.id == 'rezka').rezkaKadrCount,
      4,
    );
    final orderId = saved.map.id;
    final mapWithoutRezkaFrameConfig = saved.map.copyWith(
      nodes: saved.map.nodes
          .map(
            (node) => node.id == 'rezka'
                ? const ProductionMapNode(
                    id: 'rezka',
                    kind: 'apparatus',
                    title: _rezkaApparatusName,
                    apparatusId: apparatus,
                  )
                : node,
          )
          .toList(growable: false),
    );
    await MobileApi.instance.adminSaveTrainingProductionMap(
      mapWithoutRezkaFrameConfig,
    );
    expect(
      (await MobileApi.instance.adminTrainingProductionMaps(id: orderId))
          .single
          .map
          .nodes
          .firstWhere((node) => node.id == 'rezka')
          .rezkaKadrCount,
      isNull,
    );
    await MobileApi.instance.adminSaveProductionMapSequence(
      apparatus: apparatus,
      orderIds: [orderId],
    );

    await expectLater(
      () => MobileApi.instance.adminApparatusQueueActionResult(
        apparatus: apparatus,
        orderId: orderId,
        action: 'start',
      ),
      throwsA(
        isA<MobileApiException>().having(
          (error) => error.code,
          'code',
          'progress_qr_required',
        ),
      ),
    );

    final generated = await MobileApi.instance.adminGenerateTrainingInputBatch(
      orderId: orderId,
    );
    expect(generated.apparatus, _trainingLaminationInputStageId);
    expect(generated.nextApparatus, apparatus);
    expect(generated.qrPayload, matches(RegExp(r'^4001[0-9A-F]{20}$')));
    expect(generated.qrPayload, _productionProgressQr(generated.batchId));

    final scanned = await MobileApi.instance.adminProgressQrLookup(
      generated.qrPayload,
    );
    expect(scanned.batchId, generated.batchId);
    expect(scanned.apparatus, _trainingLaminationInputStageId);
    expect(scanned.nextApparatus, apparatus);

    final batches = await MobileApi.instance.adminWipBatches(
      status: 'all',
      nextApparatus: apparatus,
      orderId: orderId,
    );
    expect(batches, hasLength(1));
    expect(batches.single.qrPayload, generated.qrPayload);

    final started = await MobileApi.instance.adminApparatusQueueActionResult(
      apparatus: apparatus,
      orderId: orderId,
      action: 'start',
      qrPayload: generated.qrPayload,
      progressBatchId: generated.batchId,
    );
    expect(started.states[orderId], 'in_progress');

    final detached = await MobileApi.instance.adminApparatusQueueActionResult(
      apparatus: apparatus,
      orderId: orderId,
      action: 'detach_roll',
      grossQty: 52,
      finishedGoodsKg: 50,
      finishedGoodsMeter: 450,
      bobinaKg: 2,
      diameter: 30,
      rezkaBosmaWaste: 0.5,
      rezkaLaminationWaste: 1,
      rezkaEdgeWaste: 1.5,
      totalWaste: 3,
      uom: 'm',
    );
    expect(detached.states[orderId], 'paused');
    expect(detached.progressBatches, hasLength(4));
    expect(detached.printJobs, hasLength(4));
    expect(
      detached.progressBatches.every((batch) => batch.producedQty == 450),
      isTrue,
    );
    expect(detached.progressBatches.first.totalWaste, 3);
    expect(detached.progressBatches[1].totalWaste, isNull);
    for (var index = 0; index < detached.progressBatches.length; index += 1) {
      final batch = detached.progressBatches[index];
      expect(batch.action, 'detach_roll');
      expect(batch.status, 'roll_detached');
      expect(batch.batchId, endsWith(':frame:${index + 1}'));
      expect(batch.qrPayload, _productionProgressQr(batch.batchId));
      expect(detached.printJobs[index].epc, batch.qrPayload);
    }

    final resumed = await MobileApi.instance.adminApparatusQueueActionResult(
      apparatus: apparatus,
      orderId: orderId,
      action: 'resume',
      qrPayload: detached.progressBatches.first.qrPayload,
      progressBatchId: detached.progressBatches.first.batchId,
    );
    expect(resumed.states[orderId], 'in_progress');
    expect(resumed.progressBatches, hasLength(4));
    expect(
      resumed.progressBatches.every((batch) => batch.status == 'resumed'),
      isTrue,
    );

    final completed = await MobileApi.instance.adminApparatusQueueActionResult(
      apparatus: apparatus,
      orderId: orderId,
      action: 'complete',
      producedQty: 900,
      grossQty: 104,
      finishedGoodsKg: 100,
      finishedGoodsMeter: 900,
      bobinaKg: 4,
      diameter: 42,
      rezkaBosmaWaste: 1,
      rezkaLaminationWaste: 2,
      rezkaEdgeWaste: 3,
      totalWaste: 6,
      uom: 'm',
    );
    expect(completed.states[orderId], 'completed');
    expect(completed.progressBatches, hasLength(4));
    expect(completed.printJobs, hasLength(4));
    expect(
      completed.progressBatch?.batchId,
      completed.progressBatches.first.batchId,
    );
    expect(completed.printJob?.epc, completed.printJobs.first.epc);
    expect(
      completed.progressBatches.map((batch) => batch.batchId).toSet(),
      hasLength(4),
    );
    expect(
      completed.progressBatches.map((batch) => batch.qrPayload).toSet(),
      hasLength(4),
    );
    for (var index = 0; index < completed.progressBatches.length; index += 1) {
      final batch = completed.progressBatches[index];
      expect(batch.batchId, endsWith(':frame:${index + 1}'));
      expect(batch.qrPayload, _productionProgressQr(batch.batchId));
      expect(batch.parentBatchId, generated.batchId);
      expect(batch.payloadJson['rezka_frame_index'], index + 1);
      expect(batch.payloadJson['rezka_frame_count'], 4);
      expect(batch.payloadJson['rezka_output_kind'], 'frame');
      expect(batch.payloadJson['rezka_metrics_owner'], index == 0);
      expect(completed.printJobs[index].epc, batch.qrPayload);
      final lookedUp = await MobileApi.instance.adminProgressQrLookup(
        batch.qrPayload,
      );
      expect(lookedUp.batchId, batch.batchId);
    }
    expect(completed.progressBatches.first.diameter, 42);
    expect(completed.progressBatches.first.totalWaste, 6);
    expect(completed.progressBatches.first.bobinaKg, 4);
    expect(completed.progressBatches[1].diameter, isNull);
    expect(completed.progressBatches[1].totalWaste, isNull);
    expect(completed.progressBatches[1].bobinaKg, isNull);
    final report = await MobileApi.instance.adminProgressQrReport(
      completed.progressBatches.last.qrPayload,
    );
    expect(
      report.progressBatches.where(
        (batch) =>
            batch.action == 'complete' &&
            batch.payloadJson['rezka_output_kind'] == 'frame',
      ),
      hasLength(4),
    );
  });

  test('training input batch set keeps partial and final completion separate',
      () async {
    await TestModeController.instance.setEnabled(true);
    const apparatus = _secondLaminationApparatusId;
    final saved = await MobileApi.instance.adminSaveTrainingProductionMap(
      const ProductionMapDefinition(
        id: 'zakaz-draft-laminatsiya-batch-set',
        productCode: 'TRAINING-LAM-SET',
        title: 'Training laminatsiya batch set',
        orderKg: 10,
        nodes: [
          ProductionMapNode(id: 'start', kind: 'start', title: 'Start'),
          ProductionMapNode(
            id: 'laminatsiya',
            kind: 'apparatus',
            title: _secondLaminationApparatusName,
            apparatusId: apparatus,
          ),
          ProductionMapNode(id: 'end', kind: 'end', title: 'End'),
        ],
        edges: [
          ProductionMapEdge(from: 'start', to: 'laminatsiya'),
          ProductionMapEdge(from: 'laminatsiya', to: 'end'),
        ],
      ),
    );
    final orderId = saved.map.id;
    await MobileApi.instance.adminSaveProductionMapSequence(
      apparatus: apparatus,
      orderIds: [orderId],
    );

    final inputs = await MobileApi.instance.adminGenerateTrainingInputBatches(
      orderId: orderId,
      count: 2,
    );
    expect(inputs, hasLength(2));
    expect(inputs.map((batch) => batch.batchId).toSet(), hasLength(2));
    expect(inputs.map((batch) => batch.qrPayload).toSet(), hasLength(2));

    await MobileApi.instance.adminApparatusQueueActionResult(
      apparatus: apparatus,
      orderId: orderId,
      action: 'start',
      qrPayload: inputs.first.qrPayload,
      progressBatchId: inputs.first.batchId,
    );
    setMobileApiTestModeQueueActionControlFixture(
      apparatus: apparatus,
      orderId: orderId,
      control: _inProgressQueueControl(completeRequiresFullReport: false),
    );
    var queue = await MobileApi.instance.adminProductionMapQueueSnapshot();
    expect(
      queue
          .queueActionControls[apparatus]![orderId]!.completeRequiresFullReport,
      isFalse,
    );
    final partial = await MobileApi.instance.adminApparatusQueueActionResult(
      apparatus: apparatus,
      orderId: orderId,
      action: 'complete',
      finishedGoodsKg: 5,
      finishedGoodsMeter: 50,
      bobinaKg: 1,
      uom: 'm',
    );
    expect(partial.states[orderId], 'pending');

    await MobileApi.instance.adminApparatusQueueActionResult(
      apparatus: apparatus,
      orderId: orderId,
      action: 'start',
      qrPayload: inputs.last.qrPayload,
      progressBatchId: inputs.last.batchId,
    );
    setMobileApiTestModeQueueActionControlFixture(
      apparatus: apparatus,
      orderId: orderId,
      control: _inProgressQueueControl(completeRequiresFullReport: true),
    );
    queue = await MobileApi.instance.adminProductionMapQueueSnapshot();
    expect(
      queue
          .queueActionControls[apparatus]![orderId]!.completeRequiresFullReport,
      isTrue,
    );
    final completed = await MobileApi.instance.adminApparatusQueueActionResult(
      apparatus: apparatus,
      orderId: orderId,
      action: 'complete',
      finishedGoodsKg: 5,
      finishedGoodsMeter: 50,
      bobinaKg: 1,
      laminationPrintLeftoverRolls: 1,
      totalWaste: 1,
      uom: 'm',
    );
    expect(completed.states[orderId], 'completed');
  });
}
