// Generated by large_library_splitter.dart; keep changes in the source library.
part of 'admin_item_create_screen_test.dart';

Future<void> _pumpAdminItemCreateScreen(
  WidgetTester tester, {
  bool waitForItems = false,
}) async {
  await tester.pump();
  await tester.pump(const Duration(milliseconds: 100));
  final deadline = waitForItems ? 30 : 10;
  for (var i = 0; i < deadline; i++) {
    await tester.pump(const Duration(milliseconds: 100));
    if (waitForItems && find.text('Item 001').evaluate().isNotEmpty) {
      return;
    }
  }
}

Future<void> _openCreateItemTab(WidgetTester tester) async {
  await tester.tap(find.byKey(const ValueKey('app-primary-navigation-button')));
  await tester.pumpAndSettle();
  await tester.tap(find.text('Item qo‘shish').last);
  await tester.pumpAndSettle();
  for (var i = 0; i < 30; i++) {
    await tester.pump(const Duration(milliseconds: 100));
    if (find.text('All Item Groups').evaluate().isNotEmpty) {
      await tester.pumpAndSettle();
      return;
    }
  }
}

Future<void> _openItemsTab(WidgetTester tester) async {
  await tester.tap(find.widgetWithText(Tab, 'Itemlar'));
  await tester.pump();
  for (var i = 0; i < 30; i++) {
    await tester.pump(const Duration(milliseconds: 100));
    if (find.text('Item 001').evaluate().isNotEmpty) {
      return;
    }
  }
}

Finder _appBarSearchEditable() {
  return find.descendant(
    of: find.byType(AdminCatalogSearchField),
    matching: find.byType(EditableText),
  );
}

Finder _createTabTextFieldAt(int index) {
  return find.byKey(
    index == 0
        ? const ValueKey('admin-item-create-code')
        : const ValueKey('admin-item-create-name'),
  );
}

class _AdminItemCreateHttpClient implements HttpClient {
  _AdminItemCreateHttpClient(
    this.seenRequests, {
    this.sameNameDifferentCode = false,
    this.duplicateOnPost = false,
    this.customerRequiredOnPost = false,
  });

  final List<String> seenRequests;
  final bool sameNameDifferentCode;
  final bool duplicateOnPost;
  final bool customerRequiredOnPost;

  @override
  Future<HttpClientRequest> openUrl(String method, Uri url) async {
    final key =
        '$method ${url.path}${url.query.isEmpty ? '' : '?${url.query}'}';
    seenRequests.add(key);

    if (key == 'GET /v1/mobile/admin/items?limit=80') {
      return _FakeHttpClientRequest(
        response: _FakeHttpClientResponse(
          body: jsonEncode(_itemsPage(1, 80)),
          statusCode: HttpStatus.ok,
        ),
      );
    }
    if (key == 'GET /v1/mobile/admin/items?limit=80&offset=80') {
      return _FakeHttpClientRequest(
        response: _FakeHttpClientResponse(
          body: jsonEncode(_itemsPage(81, 5)),
          statusCode: HttpStatus.ok,
        ),
      );
    }
    if (sameNameDifferentCode &&
        key == 'GET /v1/mobile/admin/items?q=ITEM-UNIQUE&limit=5') {
      return _FakeHttpClientRequest(
        response: _FakeHttpClientResponse(
          body: jsonEncode(const [
            {
              'code': 'ITEM-OTHER',
              'name': 'Shared name',
              'uom': 'Kg',
              'item_group': 'All Item Groups',
            },
          ]),
          statusCode: HttpStatus.ok,
        ),
      );
    }
    if (duplicateOnPost &&
        key == 'GET /v1/mobile/admin/items?q=ITEM-RACE&limit=5') {
      return _FakeHttpClientRequest(
        response: _FakeHttpClientResponse(
          body: '[]',
          statusCode: HttpStatus.ok,
        ),
      );
    }
    if (customerRequiredOnPost &&
        key == 'GET /v1/mobile/admin/items?q=ITEM-FG-RACE&limit=5') {
      return _FakeHttpClientRequest(
        response: _FakeHttpClientResponse(
          body: '[]',
          statusCode: HttpStatus.ok,
        ),
      );
    }
    if (key == 'POST /v1/mobile/admin/items') {
      final statusCode = sameNameDifferentCode
          ? HttpStatus.ok
          : customerRequiredOnPost
              ? HttpStatus.badRequest
              : duplicateOnPost
                  ? HttpStatus.conflict
                  : HttpStatus.internalServerError;
      final body = sameNameDifferentCode
          ? const {
              'code': 'ITEM-UNIQUE',
              'name': 'Shared name',
              'uom': 'Kg',
              'item_group': 'All Item Groups',
            }
          : customerRequiredOnPost
              ? const {
                  'error': 'tayyor mahsulot uchun kamida bitta customer kerak',
                }
              : duplicateOnPost
                  ? const {'error': 'item code already exists'}
                  : const {'error': 'admin item create failed'};
      return _FakeHttpClientRequest(
        response: _FakeHttpClientResponse(
          body: jsonEncode(body),
          statusCode: statusCode,
        ),
      );
    }

    final Object body = switch (key) {
      'GET /v1/mobile/admin/settings' => {'default_uom': 'Kg'},
      'GET /v1/mobile/admin/items/uoms' => const ['Kg', 'Dona'],
      'GET /v1/mobile/admin/item-groups' => const [
          'All Item Groups',
          'Group A',
          'Group B',
        ],
      'GET /v1/mobile/admin/item-groups/tree' => const [
          {
            'name': 'Metal',
            'item_group_name': 'Metal',
            'parent_item_group': 'Homashyo',
            'is_group': false,
          },
          {
            'name': 'Group B',
            'item_group_name': 'Group B',
            'parent_item_group': 'All Item Groups',
            'is_group': false,
          },
          {
            'name': 'All Item Groups',
            'item_group_name': 'All Item Groups',
            'parent_item_group': '',
            'is_group': true,
          },
          {
            'name': 'Homashyo',
            'item_group_name': 'Homashyo',
            'parent_item_group': 'All Item Groups',
            'is_group': true,
          },
          {
            'name': 'Plastic',
            'item_group_name': 'Plastic',
            'parent_item_group': 'Homashyo',
            'is_group': false,
          },
        ],
      'GET /v1/mobile/admin/items?q=test&limit=5' => const [
          {
            'code': 'test',
            'name': 'test',
            'uom': 'Kg',
            'warehouse': 'Stores - A',
            'item_group': 'All Item Groups',
          },
        ],
      _ => throw StateError('Unhandled request: $key'),
    };

    return _FakeHttpClientRequest(
      response: _FakeHttpClientResponse(
        body: jsonEncode(body),
        statusCode: HttpStatus.ok,
      ),
    );
  }

  @override
  Future<HttpClientRequest> getUrl(Uri url) => openUrl('GET', url);

  @override
  Future<HttpClientRequest> postUrl(Uri url) => openUrl('POST', url);

  @override
  void close({bool force = false}) {}

  @override
  noSuchMethod(Invocation invocation) => super.noSuchMethod(invocation);
}

List<Map<String, String>> _itemsPage(int start, int count) {
  return List<Map<String, String>>.generate(count, (index) {
    final number = start + index;
    final padded = number.toString().padLeft(3, '0');
    return {
      'code': 'ITEM-$padded',
      'name': 'Item $padded',
      'uom': 'Kg',
      'warehouse': 'Stores - A',
      'item_group': number.isEven ? 'Tayyor Mahsulot' : 'Homashyo',
    };
  });
}

class _FakeHttpClientRequest implements HttpClientRequest {
  _FakeHttpClientRequest({required this.response});

  final _FakeHttpClientResponse response;
  final _FakeHttpHeaders _headers = _FakeHttpHeaders();
  final Completer<HttpClientResponse> _done = Completer<HttpClientResponse>();

  @override
  HttpHeaders get headers => _headers;

  @override
  bool persistentConnection = true;

  @override
  bool followRedirects = true;

  @override
  int maxRedirects = 5;

  @override
  int contentLength = -1;

  @override
  bool bufferOutput = true;

  @override
  List<Cookie> get cookies => const <Cookie>[];

  @override
  Future<HttpClientResponse> get done => _done.future;

  @override
  void add(List<int> data) {}

  @override
  Future<void> addStream(Stream<List<int>> stream) async {}

  @override
  void write(Object? object) {}

  @override
  void writeAll(Iterable<Object?> objects, [String separator = '']) {}

  @override
  void writeCharCode(int charCode) {}

  @override
  void writeln([Object? object = '']) {}

  @override
  Future<void> flush() async {}

  @override
  Future<HttpClientResponse> close() {
    if (!_done.isCompleted) {
      _done.complete(response);
    }
    return _done.future;
  }

  @override
  void abort([Object? exception, StackTrace? stackTrace]) {
    if (!_done.isCompleted) {
      _done.completeError(
        exception ?? const HttpException('aborted'),
        stackTrace ?? StackTrace.empty,
      );
    }
  }

  @override
  noSuchMethod(Invocation invocation) => super.noSuchMethod(invocation);
}

class _FakeHttpClientResponse extends StreamView<List<int>>
    implements HttpClientResponse {
  _FakeHttpClientResponse({required String body, required this.statusCode})
      : _bytes = utf8.encode(body),
        _headers = _FakeHttpHeaders(),
        super(Stream<List<int>>.value(utf8.encode(body))) {
    _headers.set('content-type', 'application/json; charset=utf-8');
    _headers.contentLength = _bytes.length;
  }

  final List<int> _bytes;
  final _FakeHttpHeaders _headers;

  @override
  final int statusCode;

  @override
  String get reasonPhrase => statusCode == HttpStatus.ok ? 'OK' : 'ERROR';

  @override
  int get contentLength => _bytes.length;

  @override
  HttpHeaders get headers => _headers;

  @override
  HttpClientResponseCompressionState get compressionState =>
      HttpClientResponseCompressionState.notCompressed;

  @override
  bool get persistentConnection => false;

  @override
  bool get isRedirect => false;

  @override
  List<RedirectInfo> get redirects => const <RedirectInfo>[];

  @override
  Future<HttpClientResponse> redirect([
    String? method,
    Uri? url,
    bool? followLoops,
  ]) async {
    return this;
  }

  @override
  Future<Socket> detachSocket() {
    return Future<Socket>.error(
      UnsupportedError('detachSocket is not supported in tests'),
    );
  }

  @override
  List<Cookie> get cookies => const <Cookie>[];

  @override
  X509Certificate? get certificate => null;

  @override
  HttpConnectionInfo? get connectionInfo => null;

  @override
  noSuchMethod(Invocation invocation) => super.noSuchMethod(invocation);
}
