// Generated by large_library_splitter.dart; keep changes in the source library.
part of 'admin_warehouses_screen_test.dart';

void _registeradmin_warehouses_screen_testCases02() {
  testWidgets('warehouse assignee picker hides already assigned users', (
    tester,
  ) async {
    final assigned = await MobileApi.instance.adminCreateSystemUser(
      role: UserRole.materialTaminotchi,
      name: 'Already Assigned Material',
      phone: '+998110000014',
    );
    await MobileApi.instance.adminCreateSystemUser(
      role: UserRole.qolipchi,
      name: 'Available Qolipchi',
      phone: '+998110000015',
    );
    await MobileApi.instance.adminAssignWarehouse(
      warehouse: 'Tayyor mahsulot ombori - DEMO',
      principalRole: assigned.role,
      principalRef: assigned.id,
      displayName: assigned.name,
    );

    await _pumpWarehousesScreen(tester);
    await _selectWarehouse(tester, 'Tayyor mahsulot ombori - DEMO');
    await tester.tap(find.text('Sozlamalar'));
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(const ValueKey('warehouse-assign-user')));
    await tester.pumpAndSettle();

    final sheet = find.byType(BottomSheet);
    await tester.enterText(
      find.descendant(of: sheet, matching: find.byType(TextField)),
      'Already Assigned Material',
    );
    await tester.pumpAndSettle();
    expect(
      find.descendant(
        of: sheet,
        matching: find.byWidgetPredicate(
          (widget) =>
              widget is Text && widget.data == 'Already Assigned Material',
        ),
      ),
      findsNothing,
    );

    await tester.enterText(
      find.descendant(of: sheet, matching: find.byType(TextField)),
      'Available Qolipchi',
    );
    await tester.pumpAndSettle();
    expect(
      find.descendant(
        of: sheet,
        matching: find.byWidgetPredicate(
          (widget) => widget is Text && widget.data == 'Available Qolipchi',
        ),
      ),
      findsOneWidget,
    );
  });

  testWidgets('warehouse page separates products and settings tabs', (
    tester,
  ) async {
    await _pumpWarehousesScreen(tester);

    expect(find.text('Mahsulotlar'), findsOneWidget);
    expect(find.text('Sozlamalar'), findsOneWidget);

    await _selectWarehouse(tester, 'Tayyor mahsulot ombori - DEMO');
    await tester.tap(find.text('Sozlamalar'));
    await tester.pumpAndSettle();

    expect(find.text('Ombor ma’lumoti'), findsOneWidget);
    expect(find.text('Assign qilinganlar'), findsOneWidget);
    expect(find.text('Kimga assign qilish'), findsOneWidget);
    expect(find.text('Omborni o‘chirish'), findsOneWidget);
  });

  testWidgets('warehouse settings assigns a qolipchi user', (
    tester,
  ) async {
    await MobileApi.instance.adminCreateSystemUser(
      role: UserRole.qolipchi,
      name: 'Jumaniyoz qolipchi',
      phone: '+998110000011',
    );
    await _pumpWarehousesScreen(tester);
    await _selectWarehouse(tester, 'Tayyor mahsulot ombori - DEMO');
    await tester.tap(find.text('Sozlamalar'));
    await tester.pumpAndSettle();

    await tester.tap(find.byKey(const ValueKey('warehouse-assign-user')));
    await tester.pumpAndSettle();
    await tester.enterText(find.byType(TextField).last, 'jumaniyoz');
    await tester.pumpAndSettle();
    await tester.tap(find.text('Jumaniyoz qolipchi'));
    await tester.pumpAndSettle();

    expect(find.text('Jumaniyoz qolipchi'), findsOneWidget);
    expect(find.text('Qolipchi'), findsOneWidget);
  });

  testWidgets('warehouse settings removes one assignment after confirmation', (
    tester,
  ) async {
    await MobileApi.instance.adminAssignWarehouse(
      warehouse: 'Tayyor mahsulot ombori - DEMO',
      principalRole: UserRole.werka,
      principalRef: 'werka',
      displayName: 'Werka',
    );
    await _pumpWarehousesScreen(tester);
    await _selectWarehouse(tester, 'Tayyor mahsulot ombori - DEMO');
    await tester.tap(find.text('Sozlamalar'));
    await tester.pumpAndSettle();

    expect(find.text('Werka'), findsWidgets);
    await tester.tap(find.byTooltip('Assigndan chiqarish'));
    await tester.pumpAndSettle();

    expect(find.text('Assigndan chiqarish'), findsOneWidget);
    expect(find.textContaining('omboridan chiqarasizmi'), findsOneWidget);
    await tester.tap(find.text('Olib tashlash'));
    await tester.pumpAndSettle();

    expect(find.text('Hech kim assign qilinmagan'), findsOneWidget);
    expect(find.text('Werka assigndan chiqarildi'), findsOneWidget);
  });

  testWidgets('warehouse deletion warns when products will be deleted', (
    tester,
  ) async {
    await _pumpWarehousesScreen(tester);
    await _selectWarehouse(tester, 'Tayyor mahsulot ombori - DEMO');
    await tester.tap(find.text('Sozlamalar'));
    await tester.pumpAndSettle();

    final deleteButton = find.byKey(const ValueKey('warehouse-delete-button'));
    await tester.ensureVisible(deleteButton);
    await tester.tap(deleteButton);
    await tester.pumpAndSettle();

    expect(find.textContaining('mahsulot bor'), findsOneWidget);
    expect(find.textContaining('o‘chib ketadi'), findsOneWidget);
    expect(
        find.byKey(const ValueKey('warehouse-delete-confirm')), findsOneWidget);
  });

  testWidgets('confirmed deletion removes an empty warehouse immediately', (
    tester,
  ) async {
    await MobileApi.instance.adminCreateWarehouse('Bo‘sh ombor');
    await _pumpWarehousesScreen(tester);
    await _selectWarehouse(tester, 'Bo‘sh ombor');
    await tester.tap(find.text('Sozlamalar'));
    await tester.pumpAndSettle();

    final deleteButton = find.byKey(const ValueKey('warehouse-delete-button'));
    await tester.ensureVisible(deleteButton);
    await tester.tap(deleteButton);
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(const ValueKey('warehouse-delete-confirm')));
    await tester.pumpAndSettle();

    expect(find.text('Ombor o‘chirildi'), findsOneWidget);
    expect(find.text('Ombor tanlanmagan'), findsOneWidget);
    await _openWarehouseFilter(tester);
    expect(find.text('Bo‘sh ombor'), findsNothing);
  });

  testWidgets('material scoped warehouses page shows only assigned warehouses',
      (
    tester,
  ) async {
    await tester.binding.setSurfaceSize(const Size(800, 1200));
    addTearDown(() => tester.binding.setSurfaceSize(null));
    AppSession.instance.profile = const SessionProfile(
      role: UserRole.materialTaminotchi,
      displayName: 'Materialchi',
      legalName: '',
      ref: 'material_taminotchi',
      phone: '',
      avatarUrl: '',
      capabilities: [
        'gscale.catalog.read',
        'gscale.print',
        'rps.batch.manage',
        'raw_material.assign',
      ],
      assignedItemGroups: ['Kraska'],
      assignedWarehouses: ['Xomashyo ombori - DEMO'],
    );

    await tester.pumpWidget(
      MaterialApp(
        theme: ThemeData(useMaterial3: true),
        locale: const Locale('uz'),
        localizationsDelegates: const [
          AppLocalizations.delegate,
          GlobalMaterialLocalizations.delegate,
          GlobalCupertinoLocalizations.delegate,
          GlobalWidgetsLocalizations.delegate,
        ],
        supportedLocales: AppLocalizations.supportedLocales,
        home: const AdminWarehousesScreen(),
      ),
    );

    for (var i = 0; i < 20; i++) {
      await tester.pump(const Duration(milliseconds: 100));
      if (find.byKey(_warehouseFilterKey).evaluate().isNotEmpty) {
        break;
      }
    }

    expect(find.text('Joylashuvdagi mahsulotni qidirish'), findsOneWidget);
    expect(find.text('Omborlar'), findsOneWidget);
    expect(find.text('State’lar'), findsOneWidget);
    expect(find.text('Ombor yaratish'), findsNothing);

    await _openWarehouseFilter(tester);

    expect(find.text('Xomashyo ombori - DEMO'), findsOneWidget);
    expect(find.text('Tayyor mahsulot ombori - DEMO'), findsNothing);

    await tester.tap(find.text('Xomashyo ombori - DEMO'));
    await tester.pumpAndSettle();

    expect(find.text('Demo kraska'), findsNothing);
    expect(find.text('Demo xomashyo rulon'), findsOneWidget);
    expect(find.textContaining('30AA • 12 Kg'), findsOneWidget);
    expect(find.text('Hotlunch'), findsNothing);

    await tester.tap(find.text('Demo xomashyo rulon'));
    await tester.pumpAndSettle();

    final qrButton = find.byKey(const ValueKey('raw-stock-qr-30AA'));
    final editButton = find.byKey(const ValueKey('raw-stock-edit-30AA'));
    expect(qrButton, findsOneWidget);
    expect(editButton, findsOneWidget);
    expect(tester.getCenter(qrButton).dx,
        lessThan(tester.getCenter(editButton).dx));

    await tester.tap(qrButton);
    await tester.pumpAndSettle();

    expect(find.text('Chop etilgan QR'), findsOneWidget);
    expect(
      find.byKey(const ValueKey('raw-stock-qr-preview-30AA')),
      findsOneWidget,
    );
    expect(find.text('GSR-30AA'), findsWidgets);
    expect(find.byKey(const ValueKey('raw-stock-qr-reprint')), findsOneWidget);

    await tester.tap(find.byTooltip('Yopish'));
    await tester.pumpAndSettle();

    expect(find.byKey(const ValueKey('raw-stock-edit-30AA')), findsOneWidget);
    await tester.tap(find.byKey(const ValueKey('raw-stock-edit-30AA')));
    await tester.pumpAndSettle();

    expect(find.text('Homashyoni tahrirlash'), findsOneWidget);
    expect(find.textContaining('Shtrix-kod 30AA'), findsOneWidget);
    expect(find.byKey(const ValueKey('raw-stock-edit-qty')), findsOneWidget);
    expect(find.byKey(const ValueKey('raw-stock-edit-save')), findsOneWidget);
  });

  testWidgets(
      'material state tab only shows own current placements and returns them',
      (tester) async {
    await tester.binding.setSurfaceSize(const Size(800, 1200));
    addTearDown(() => tester.binding.setSurfaceSize(null));
    AppSession.instance.profile = const SessionProfile(
      role: UserRole.materialTaminotchi,
      displayName: 'Materialchi',
      legalName: '',
      ref: 'material_taminotchi',
      phone: '',
      avatarUrl: '',
      capabilities: ['inventory.movement.manage'],
      assignedWarehouses: ['Xomashyo ombori - DEMO'],
    );
    seedMobileApiInventoryMovementTestData(
      locations: const [
        InventoryLocation(
          id: 'inventory_location:warehouse:demo-raw',
          kind: InventoryLocationKind.warehouse,
          name: 'Xomashyo ombori - DEMO',
          warehouseId: 'warehouse:demo-raw',
        ),
        InventoryLocation(
          id: 'inventory_location:state:bosma',
          kind: InventoryLocationKind.state,
          name: '7 ta bosma apar',
          factoryLocationId: 'state:bosma',
        ),
      ],
      assets: const [
        InventoryAsset(
          kind: InventoryAssetKind.rawMaterial,
          assetRef: 'raw:30aa',
          custodyWarehouseId: 'warehouse:demo-raw',
          custodyWarehouse: 'Xomashyo ombori - DEMO',
          itemCode: 'DEMO-RAW-001',
          itemName: 'Demo xomashyo rulon',
          identifier: '30AA',
          qty: 12,
          uom: 'Kg',
          status: 'available',
          physicalLocation: InventoryLocationReference(
            id: 'inventory_location:warehouse:demo-raw',
            kind: InventoryLocationKind.warehouse,
            name: 'Xomashyo ombori - DEMO',
          ),
        ),
      ],
    );
    await MobileApi.instance.inventoryRelocate(
      assetKind: InventoryAssetKind.rawMaterial,
      assetRef: 'raw:30aa',
      physicalLocationId: 'inventory_location:state:bosma',
      idempotencyKey: 'material-state-placement',
    );

    await tester.pumpWidget(
      MaterialApp(
        theme: ThemeData(useMaterial3: true),
        locale: const Locale('uz'),
        localizationsDelegates: const [
          AppLocalizations.delegate,
          GlobalMaterialLocalizations.delegate,
          GlobalCupertinoLocalizations.delegate,
          GlobalWidgetsLocalizations.delegate,
        ],
        supportedLocales: AppLocalizations.supportedLocales,
        home: const AdminWarehousesScreen(),
      ),
    );
    await tester.pumpAndSettle();

    await tester.tap(find.text('State’lar'));
    await tester.pumpAndSettle();
    await tester.tap(
      find.byKey(const ValueKey('material-state-filter-chip')),
    );
    await tester.pumpAndSettle();
    expect(find.text('7 ta bosma apar'), findsOneWidget);

    await tester.tap(find.text('7 ta bosma apar'));
    await tester.pumpAndSettle();
    expect(find.text('Demo xomashyo rulon'), findsOneWidget);

    await tester.tap(find.text('Demo xomashyo rulon'));
    await tester.pumpAndSettle();
    expect(find.text('Hisobdagi ombor'), findsNothing);
    expect(find.text('Omborga qaytarish'), findsOneWidget);

    await tester.tap(find.byKey(
      const ValueKey('material-state-return-button'),
    ));
    await tester.pumpAndSettle();
    await tester.tap(find.text('Ha'));
    await tester.pumpAndSettle();

    expect(
      find.text('Siz joylashtirgan State’dagi mahsulot topilmadi'),
      findsOneWidget,
    );
  });

  test('admin warehouse live url uses websocket scheme and session token', () {
    final uri = MobileApi.instance.adminWarehouseLiveUri();

    expect(uri.scheme, 'wss');
    expect(uri.path, '/v1/mobile/admin/warehouses/live');
    expect(uri.queryParameters['token'], 'token');
  });
}
