// Generated by large_library_splitter.dart; keep changes in the source library.
part of 'admin_production_map_test_screen_test.dart';

void _registeradmin_production_map_test_screen_testCases04() {
  testWidgets('reopened saved map appends skipped apparatus group after tail', (
    tester,
  ) async {
    await TestModeController.instance.setEnabled(true);
    final orderNumber =
        '${DateTime.now().microsecondsSinceEpoch.remainder(9000) + 1000}';
    final mapId = 'zakaz-reopen-chain-test-$orderNumber';
    await _usePhoneViewport(tester);
    await tester.pumpWidget(
      MaterialApp(
        theme: ThemeData(useMaterial3: true),
        locale: const Locale('uz'),
        localizationsDelegates: const [
          AppLocalizations.delegate,
          GlobalMaterialLocalizations.delegate,
          GlobalCupertinoLocalizations.delegate,
          GlobalWidgetsLocalizations.delegate,
        ],
        supportedLocales: AppLocalizations.supportedLocales,
        home: AdminProductionMapTestScreen(
          savedMap: ProductionMapDefinition(
            id: mapId,
            title: 'Reopened chain order',
            productCode: 'ITEM-REOPEN-CHAIN',
            code: orderNumber,
            orderNumber: orderNumber,
            rollCount: 7,
            widthMm: 650,
            nodes: [
              const ProductionMapNode(
                id: 'start',
                kind: 'start',
                title: 'Start',
                x: 420,
                y: 32,
              ),
              const ProductionMapNode(
                id: 'order',
                kind: 'task',
                title: 'Reopened chain order',
                roleCode: 'zakaz',
                x: 420,
                y: 164,
              ),
              const ProductionMapNode(
                id: 'apparatus_1',
                kind: 'apparatus',
                title: '7 ta rangli bosma aparat',
                apparatusId: _print7Id,
                alternativeGroupId: 'alt_pechat_1',
                alternativeGroupLabel: 'pechat',
                x: 280,
                y: 296,
              ),
              const ProductionMapNode(
                id: 'apparatus_2',
                kind: 'apparatus',
                title: '8 ta rangli bosma aparat',
                apparatusId: _print8Id,
                alternativeGroupId: 'alt_pechat_1',
                alternativeGroupLabel: 'pechat',
                x: 560,
                y: 296,
              ),
              const ProductionMapNode(
                id: 'end',
                kind: 'end',
                title: 'reopen chain product',
                itemCode: 'ITEM-REOPEN-CHAIN',
                x: 420,
                y: 428,
              ),
            ],
            edges: [
              const ProductionMapEdge(from: 'start', to: 'order'),
              const ProductionMapEdge(from: 'order', to: 'apparatus_1'),
              const ProductionMapEdge(from: 'order', to: 'apparatus_2'),
              const ProductionMapEdge(from: 'apparatus_1', to: 'end'),
              const ProductionMapEdge(from: 'apparatus_2', to: 'end'),
            ],
          ),
          orderContext: const ProductionMapOrderContext(
            orderName: 'Reopened chain order',
            productName: 'reopen chain product',
            itemCode: 'ITEM-REOPEN-CHAIN',
            rollCount: 7,
            widthMm: 650,
          ),
        ),
      ),
    );
    await tester.pumpAndSettle();

    await _tapMapTool(tester, 'Laminatsiya');
    await tester.pumpAndSettle();
    await tester.tap(find.text('Skip'));
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(const ValueKey('production-map-save')));
    await tester.pumpAndSettle();

    final saved = await MobileApi.instance.adminProductionMap(
      mapId,
    );
    final map = saved.map;
    final ids = map.nodes.map((node) => node.id).toList(growable: false);
    final pechatNodes = map.nodes
        .where((node) => node.title.trim().contains('rangli bosma'))
        .toList(growable: false);
    final laminatsiyaNodes = map.nodes
        .where((node) => node.title.trim().contains('Laminatsiya'))
        .toList(growable: false);

    expect(ids.toSet().length, ids.length);
    expect(laminatsiyaNodes, hasLength(2));
    for (final pechat in pechatNodes) {
      expect(
        map.edges.any(
          (edge) =>
              edge.from == pechat.id &&
              laminatsiyaNodes.any((node) => node.id == edge.to),
        ),
        isTrue,
      );
      expect(
        map.edges.any((edge) => edge.from == pechat.id && edge.to == 'end'),
        isFalse,
      );
    }
    for (final laminatsiya in laminatsiyaNodes) {
      expect(
        map.edges
            .any((edge) => edge.from == laminatsiya.id && edge.to == 'end'),
        isTrue,
      );
    }
    await tester.pump(const Duration(seconds: 2));
  });

  testWidgets('production map does not show kk product action', (
    tester,
  ) async {
    await TestModeController.instance.setEnabled(true);
    await _usePhoneViewport(tester);
    await tester.pumpWidget(
      MaterialApp(
        theme: ThemeData(useMaterial3: true),
        locale: const Locale('uz'),
        localizationsDelegates: const [
          AppLocalizations.delegate,
          GlobalMaterialLocalizations.delegate,
          GlobalCupertinoLocalizations.delegate,
          GlobalWidgetsLocalizations.delegate,
        ],
        supportedLocales: AppLocalizations.supportedLocales,
        home: const AdminProductionMapTestScreen(
          orderContext: ProductionMapOrderContext(
            orderName: 'Zenit order',
            productName: 'zenit frutto ninja 70gr',
            itemCode: 'ITEM-001',
          ),
        ),
      ),
    );
    await tester.pumpAndSettle();

    await tester.tap(find.bySemanticsLabel('Element qo‘shish'));
    await tester.pumpAndSettle();

    expect(find.byKey(const ValueKey('admin-fab-menu-kk li mahsulot')),
        findsNothing);
    expect(find.text('kk li mahsulot'), findsNothing);
  });

  testWidgets('production map apparatus picker shows only recommended pechat', (
    tester,
  ) async {
    await TestModeController.instance.setEnabled(true);
    await _usePhoneViewport(tester);
    await tester.pumpWidget(
      MaterialApp(
        theme: ThemeData(useMaterial3: true),
        locale: const Locale('uz'),
        localizationsDelegates: const [
          AppLocalizations.delegate,
          GlobalMaterialLocalizations.delegate,
          GlobalCupertinoLocalizations.delegate,
          GlobalWidgetsLocalizations.delegate,
        ],
        supportedLocales: AppLocalizations.supportedLocales,
        home: const AdminProductionMapTestScreen(
          orderContext: ProductionMapOrderContext(
            orderName: 'Zenit order',
            productName: 'zenit frutto ninja 70gr',
            itemCode: 'ITEM-001',
            rollCount: 8,
            widthMm: 700,
          ),
        ),
      ),
    );
    await tester.pumpAndSettle();

    await _tapMapTool(tester, 'Bosma aparat');
    await tester.pumpAndSettle();

    expect(find.text('8 ta rangli bosma aparat'), findsOneWidget);
    expect(find.text('7 ta rangli bosma aparat'), findsNothing);
    expect(find.text('9 ta rangli bosma aparat'), findsNothing);
  });

  test('production map edges are unrestricted between supported nodes', () {
    const apparatus = ProductionMapNode(
      id: 'apparatus_1',
      kind: 'apparatus',
      title: 'Godex aparat - DEMO',
      apparatusId: _godexId,
    );
    const task = ProductionMapNode(
      id: 'task_1',
      kind: 'task',
      title: 'Ishlov jarayoni',
    );
    const start = ProductionMapNode(id: 'start', kind: 'start', title: 'Start');

    expect(productionMapCanCreateEdge(start, task), isTrue);
    expect(productionMapCanCreateEdge(task, start), isTrue);
    expect(productionMapCanCreateEdge(task, apparatus), isTrue);
    expect(productionMapCanCreateEdge(apparatus, task), isTrue);
  });

  test(
    'production map pechat compatibility summary uses product constraints',
    () {
      expect(
        productionMapPechatCompatibilitySummary(rollCount: 7, widthMm: 650),
        'Minimal 7 ta rangli bosma • Mos: 7 ta rangli bosma, 8 ta rangli bosma',
      );
      expect(
        productionMapPechatCompatibilitySummary(rollCount: 7, widthMm: 1250),
        'Minimal 9 ta rangli bosma • Mos: 9 ta rangli bosma',
      );
    },
  );

  test('production map pechat recommendation prioritizes val then rubber', () {
    expect(
      productionMapRecommendedPechatColorCount(rollCount: 7, widthMm: 700),
      7,
    );
    expect(
      productionMapRecommendedPechatColorCount(rollCount: 7, widthMm: 815),
      7,
    );
    expect(
      productionMapRecommendedPechatColorCount(rollCount: 7, widthMm: 900),
      8,
    );
    expect(
      productionMapRecommendedPechatColorCount(rollCount: 8, widthMm: 700),
      8,
    );
    expect(
      productionMapRecommendedPechatColorCount(rollCount: 9, widthMm: 700),
      9,
    );
    expect(
      productionMapRecommendedPechatColorCount(rollCount: 6, widthMm: 1200),
      9,
    );
    expect(
      productionMapRecommendedPechatColorCount(rollCount: 10, widthMm: 700),
      isNull,
    );
  });

  test('production map pechat filter uses expanded rubber limits', () {
    expect(productionMapRubberSizeFromWidth(815), 850);
    const screenshotOrderContext = ProductionMapOrderContext(
      orderName: 'alanga guruch qora',
      productName: 'alanga guruch qora',
      itemCode: 'ITEM-815',
      rollCount: 7,
      widthMm: 815,
    );
    expect(
      productionMapApparatusMatchesOrder(
        const AdminApparatus(
          name: '7 ta rangli bosma aparat',
          operation: 'print',
          technology: 'rotogravure',
          colorStations: 7,
        ),
        screenshotOrderContext,
      ),
      isTrue,
    );
    expect(
      productionMapPechatCanHandleOrder(
        apparatusColorCount: 7,
        rollCount: 7,
        widthMm: 815,
      ),
      isTrue,
    );
    expect(
      productionMapPechatCanHandleOrder(
        apparatusColorCount: 7,
        rollCount: 7,
        widthMm: 851,
      ),
      isFalse,
    );
    expect(
      productionMapPechatCanHandleOrder(
        apparatusColorCount: 8,
        rollCount: 8,
        widthMm: 1050,
      ),
      isTrue,
    );
    expect(
      productionMapPechatCanHandleOrder(
        apparatusColorCount: 8,
        rollCount: 8,
        widthMm: 1051,
      ),
      isFalse,
    );
    expect(productionMapRubberSizeFromWidth(1500), 1350);
    expect(
      productionMapPechatCanHandleOrder(
        apparatusColorCount: 9,
        rollCount: 9,
        widthMm: 1350,
      ),
      isTrue,
    );
  });
}
