// Generated by large_library_splitter.dart; keep changes in the source library.
part of 'admin_production_map_test_screen_test.dart';

void _registeradmin_production_map_test_screen_testCases12() {
  testWidgets('opened orders move module moves only compatible pechat orders', (
    tester,
  ) async {
    await TestModeController.instance.setEnabled(true);
    await MobileApi.instance.adminSaveProductionMap(
      _productionOrderMap(
        id: 'zakaz-move-ok',
        title: 'Move ok order',
        productCode: 'MOVE-OK',
        apparatusId: _print8Id,
        product: 'move ok product',
        rollCount: 7,
        widthMm: 650,
        apparatusCopies: 2,
      ),
    );
    await MobileApi.instance.adminSaveProductionMap(
      _productionOrderMap(
        id: 'zakaz-move-blocked',
        title: 'Move blocked order',
        productCode: 'MOVE-BLOCK',
        apparatusId: _print8Id,
        product: 'move blocked product',
        rollCount: 8,
        widthMm: 700,
      ),
    );
    await MobileApi.instance.adminSaveProductionMap(
      _productionOrderMap(
        id: 'zakaz-move-target',
        title: 'Move target order',
        productCode: 'MOVE-TARGET',
        apparatusId: _print7Id,
        product: 'move target product',
        rollCount: 7,
        widthMm: 650,
      ),
    );
    await _usePhoneViewport(tester);
    await tester.pumpWidget(
      MaterialApp(
        theme: ThemeData(useMaterial3: true),
        locale: const Locale('uz'),
        localizationsDelegates: const [
          AppLocalizations.delegate,
          GlobalMaterialLocalizations.delegate,
          GlobalCupertinoLocalizations.delegate,
          GlobalWidgetsLocalizations.delegate,
        ],
        supportedLocales: AppLocalizations.supportedLocales,
        home: const AdminProductionMapOrdersScreen(),
      ),
    );
    await tester.pumpAndSettle();

    expect(find.text('Ko‘chirish'), findsOneWidget);
    expect(find.byIcon(Icons.add_rounded), findsOneWidget);
    await tester.tap(find.text('Ko‘chirish'));
    await tester.pumpAndSettle();
    expect(find.byIcon(Icons.add_rounded), findsNothing);
    expect(find.textContaining('Move ok order'), findsOneWidget);
    expect(find.textContaining('Move blocked order'), findsNothing);
    await tester.tap(
      find.byKey(const ValueKey('move-boundary-apparatus-picker')),
    );
    await tester.pumpAndSettle();
    expect(find.text('Aparat tanlang'), findsOneWidget);
    expect(find.text('Tanlangan'), findsNothing);
    expect(find.text('Tanlanmagan'), findsOneWidget);
    await tester.tapAt(const Offset(20, 20));
    await tester.pumpAndSettle();

    await _dragOrderTitleToTopZone(
      tester,
      orderTitle: 'Move ok order',
      targetText: 'Move target order',
    );
    var maps = await MobileApi.instance.adminProductionMaps();
    expect(_apparatusTitle(maps, 'zakaz-move-ok'), '8 ta rangli bosma aparat');
    expect(find.textContaining('Move target order'), findsOneWidget);

    await _dragOrderHandleForKeyToTopZone(
      tester,
      key: const ValueKey(
        'move-order-8 ta rangli bosma aparat-zakaz-move-ok',
      ),
      targetText: 'Move target order',
    );
    expect(find.textContaining('Move ok order'), findsOneWidget);
    maps = await MobileApi.instance.adminProductionMaps();
    expect(_apparatusTitle(maps, 'zakaz-move-ok'), '7 ta rangli bosma aparat');
    expect(
      _apparatusTitles(maps, 'zakaz-move-ok'),
      isNot(contains('8 ta rangli bosma aparat')),
    );
    maps = await MobileApi.instance.adminProductionMaps();
    expect(_apparatusTitle(maps, 'zakaz-move-blocked'),
        '8 ta rangli bosma aparat');
    await tester.pump(const Duration(seconds: 3));
  });

  testWidgets(
    'opened orders move module hides cross-family Flexo and color orders',
    (tester) async {
      await TestModeController.instance.setEnabled(true);
      await MobileApi.instance.adminSaveProductionMap(
        _productionOrderMap(
          id: 'zakaz-ui-flexo-node-only',
          title: 'ABCD Family',
          productCode: 'ABCD Family',
          apparatusId: _flexoId,
          product: 'ABCD Family',
          orderNumber: '1119',
          rollCount: 7,
          widthMm: 765,
        ),
      );
      await MobileApi.instance.adminSaveProductionMap(
        _productionOrderMap(
          id: 'zakaz-ui-color-node-only',
          title: 'Imperator salyami',
          productCode: 'Imperator salyami',
          apparatusId: _print7Id,
          product: 'Imperator salyami',
          orderNumber: '0002',
          rollCount: 7,
          widthMm: 515,
        ),
      );
      await _usePhoneViewport(tester);
      await tester.pumpWidget(
        MaterialApp(
          theme: ThemeData(useMaterial3: true),
          locale: const Locale('uz'),
          localizationsDelegates: const [
            AppLocalizations.delegate,
            GlobalMaterialLocalizations.delegate,
            GlobalCupertinoLocalizations.delegate,
            GlobalWidgetsLocalizations.delegate,
          ],
          supportedLocales: AppLocalizations.supportedLocales,
          home: const AdminProductionMapOrdersScreen(),
        ),
      );
      await tester.pumpAndSettle();

      await tester.tap(find.text('Ko‘chirish'));
      await tester.pumpAndSettle();
      await tester.tap(
        find.byKey(const ValueKey('move-boundary-apparatus-picker')),
      );
      await tester.pumpAndSettle();
      await tester.tap(find.text('Flexo pechat').last);
      await tester.pumpAndSettle();

      expect(find.textContaining('ABCD Family'), findsNothing);
      expect(find.textContaining('Imperator salyami'), findsNothing);
      expect(
        find.text('7 ta rangli bosma aparat uchun zakaz yo‘q'),
        findsOneWidget,
      );
      expect(find.text('Flexo pechat uchun zakaz yo‘q'), findsOneWidget);
    },
  );

  testWidgets('opened orders move module transfers paused order with reason', (
    tester,
  ) async {
    await TestModeController.instance.setEnabled(true);
    const source = _print7Id;
    const target = _print8Id;
    const orderId = 'zakaz-paused-ui-transfer';
    const targetOrderId = 'zakaz-paused-ui-target';
    await MobileApi.instance.adminSaveProductionMap(
      _productionOrderMap(
        id: orderId,
        title: 'Paused UI transfer order',
        productCode: 'PUT-1',
        apparatusId: source,
        product: 'paused UI transfer product',
        rollCount: 7,
        widthMm: 650,
      ),
    );
    await MobileApi.instance.adminSaveProductionMap(
      _productionOrderMap(
        id: targetOrderId,
        title: 'Paused UI target order',
        productCode: 'PUT-2',
        apparatusId: target,
        product: 'paused UI target product',
        rollCount: 7,
        widthMm: 650,
      ),
    );
    await MobileApi.instance.adminSaveProductionMapSequence(
      apparatus: source,
      orderIds: const [orderId],
    );
    await MobileApi.instance.adminSaveProductionMapSequence(
      apparatus: target,
      orderIds: const [targetOrderId],
    );
    await MobileApi.instance.adminApparatusQueueActionResult(
      apparatus: source,
      orderId: orderId,
      action: 'start',
    );
    await MobileApi.instance.adminApparatusQueueActionResult(
      apparatus: source,
      orderId: orderId,
      action: 'pause',
      producedQty: 4,
    );

    await _usePhoneViewport(tester);
    await tester.pumpWidget(
      MaterialApp(
        theme: ThemeData(useMaterial3: true),
        locale: const Locale('uz'),
        localizationsDelegates: const [
          AppLocalizations.delegate,
          GlobalMaterialLocalizations.delegate,
          GlobalCupertinoLocalizations.delegate,
          GlobalWidgetsLocalizations.delegate,
        ],
        supportedLocales: AppLocalizations.supportedLocales,
        home: const AdminProductionMapOrdersScreen(),
      ),
    );
    await tester.pumpAndSettle();
    await tester.tap(find.text('Ko‘chirish'));
    await tester.pumpAndSettle();

    await _dragOrderHandleToBottomZone(
      tester,
      orderTitle: 'Paused UI transfer order',
      targetText: 'Paused UI target order',
    );
    expect(find.text('Avariya sababini kiriting'), findsOneWidget);
    await tester.enterText(
      find.byKey(const ValueKey('apparatus-transfer-reason')),
      '7 rangli pechat apparati buzildi',
    );
    await tester.tap(find.widgetWithText(FilledButton, 'Ko‘chirish'));
    await tester.pumpAndSettle();

    final snapshot = await MobileApi.instance.adminProductionMapQueueSnapshot();
    expect(snapshot.queueStates[source]?[orderId], isNull);
    expect(snapshot.queueStates[target]?[orderId], 'paused');
    final maps = await MobileApi.instance.adminProductionMaps();
    expect(_apparatusTitle(maps, orderId), '8 ta rangli bosma aparat');
    await tester.pump(const Duration(seconds: 3));
  });

  testWidgets('opened orders move module moves every selected pechat order', (
    tester,
  ) async {
    await TestModeController.instance.setEnabled(true);
    for (var index = 0; index < 2; index++) {
      await MobileApi.instance.adminSaveProductionMap(
        _productionOrderMap(
          id: 'zakaz-batch-move-$index',
          title: 'Batch move order ${index + 1}',
          productCode: 'BATCH-$index',
          apparatusId: _print7Id,
          product: 'batch move product ${index + 1}',
          rollCount: 7,
          widthMm: 650,
        ),
      );
    }
    for (var index = 2; index < 4; index++) {
      final map = _alternativeProductionOrderMap(
        id: 'zakaz-batch-move-$index',
        title: 'Batch move order ${index + 1}',
        productCode: 'BATCH-$index',
        product: 'batch move product ${index + 1}',
        apparatusIds: const [_print7Id, _print8Id],
        rollCount: 7,
        widthMm: 650,
      );
      await MobileApi.instance.adminSaveProductionMap(
        map.copyWith(
          nodes: [
            for (final node in map.nodes)
              node.kind == 'apparatus'
                  ? node.copyWith(
                      alternativeAssignedTitle: '7 ta rangli bosma aparat',
                      alternativeAssignedApparatusId: _print7Id,
                    )
                  : node,
          ],
        ),
      );
    }
    await MobileApi.instance.adminSaveProductionMap(
      _productionOrderMap(
        id: 'zakaz-batch-move-target',
        title: 'Batch move target order',
        productCode: 'BATCH-TARGET',
        apparatusId: _print8Id,
        product: 'batch move target product',
        rollCount: 7,
        widthMm: 650,
      ),
    );
    await _usePhoneViewport(tester);
    await tester.pumpWidget(
      MaterialApp(
        theme: ThemeData(useMaterial3: true),
        locale: const Locale('uz'),
        localizationsDelegates: const [
          AppLocalizations.delegate,
          GlobalMaterialLocalizations.delegate,
          GlobalCupertinoLocalizations.delegate,
          GlobalWidgetsLocalizations.delegate,
        ],
        supportedLocales: AppLocalizations.supportedLocales,
        home: const AdminProductionMapOrdersScreen(),
      ),
    );
    await tester.pumpAndSettle();

    await tester.tap(find.text('Ko‘chirish'));
    await tester.pumpAndSettle();
    for (var index = 0; index < 4; index++) {
      await _tapMoveOrderBadge(
        tester,
        key: ValueKey(
            'move-order-7 ta rangli bosma aparat-zakaz-batch-move-$index'),
      );
    }

    await _dragOrderHandleToBottomZone(
      tester,
      orderTitle: 'Batch move order 1',
      targetText: 'Batch move target order',
    );

    final maps = await MobileApi.instance.adminProductionMaps();
    for (var index = 0; index < 2; index++) {
      expect(
        _apparatusTitle(maps, 'zakaz-batch-move-$index'),
        '8 ta rangli bosma aparat',
      );
    }
    for (var index = 2; index < 4; index++) {
      expect(_alternativeAssignedTitles(maps, 'zakaz-batch-move-$index'), [
        '8 ta rangli bosma aparat',
        '8 ta rangli bosma aparat',
      ]);
    }
    await tester.pump(const Duration(seconds: 3));
  });

  testWidgets(
    'opened orders move module blocks 9-color rubber orders on 7-color pechat',
    (tester) async {
      await TestModeController.instance.setEnabled(true);
      await MobileApi.instance.adminSaveProductionMap(
        _productionOrderMap(
          id: 'zakaz-move-9-only',
          title: 'Nine color rubber order',
          productCode: 'MOVE-9',
          apparatusId: _print8Id,
          product: 'nine color product',
          rollCount: 7,
          widthMm: 1250,
        ),
      );
      await _usePhoneViewport(tester);
      await tester.pumpWidget(
        MaterialApp(
          theme: ThemeData(useMaterial3: true),
          locale: const Locale('uz'),
          localizationsDelegates: const [
            AppLocalizations.delegate,
            GlobalMaterialLocalizations.delegate,
            GlobalCupertinoLocalizations.delegate,
            GlobalWidgetsLocalizations.delegate,
          ],
          supportedLocales: AppLocalizations.supportedLocales,
          home: const AdminProductionMapOrdersScreen(),
        ),
      );
      await tester.pumpAndSettle();

      await tester.tap(find.text('Ko‘chirish'));
      await tester.pumpAndSettle();
      expect(find.textContaining('Nine color rubber order'), findsNothing);

      final maps = await MobileApi.instance.adminProductionMaps();
      expect(_apparatusTitle(maps, 'zakaz-move-9-only'),
          '8 ta rangli bosma aparat');
    },
  );
}
