// Generated by large_library_splitter.dart; keep changes in the source library.
part of 'admin_production_map_test_screen_test.dart';

void _registeradmin_production_map_test_screen_testCases13() {
  testWidgets(
    'opened orders move module keeps direct orders out of unassigned',
    (tester) async {
      await TestModeController.instance.setEnabled(true);
      await MobileApi.instance.adminSaveProductionMap(
        _productionOrderMap(
          id: 'zakaz-direct-pechat',
          title: 'Direct pechat order',
          productCode: 'DIRECT-7',
          apparatusId: _print7Id,
          product: 'direct product',
          rollCount: 7,
          widthMm: 650,
        ),
      );
      await _usePhoneViewport(tester);
      await tester.pumpWidget(
        MaterialApp(
          theme: ThemeData(useMaterial3: true),
          locale: const Locale('uz'),
          localizationsDelegates: const [
            AppLocalizations.delegate,
            GlobalMaterialLocalizations.delegate,
            GlobalCupertinoLocalizations.delegate,
            GlobalWidgetsLocalizations.delegate,
          ],
          supportedLocales: AppLocalizations.supportedLocales,
          home: const AdminProductionMapOrdersScreen(),
        ),
      );
      await tester.pumpAndSettle();

      await tester.tap(find.text('Ko‘chirish'));
      await tester.pumpAndSettle();
      expect(
        find.byKey(
          const ValueKey(
              'move-order-7 ta rangli bosma aparat-zakaz-direct-pechat'),
        ),
        findsOneWidget,
      );

      await tester.tap(
        find.byKey(const ValueKey('move-boundary-apparatus-picker')),
      );
      await tester.pumpAndSettle();
      await tester.tap(find.text('Tanlanmagan'));
      await tester.pumpAndSettle();
      expect(find.text('Tanlanmagan zakaz yo‘q'), findsOneWidget);
      expect(
        find.byKey(
          const ValueKey(
              'move-order-7 ta rangli bosma aparat-zakaz-direct-pechat'),
        ),
        findsNothing,
      );
      expect(
        find.byKey(
          const ValueKey('move-order-Tanlanmagan-zakaz-direct-pechat'),
        ),
        findsNothing,
      );
      final maps = await MobileApi.instance.adminProductionMaps();
      expect(_apparatusTitles(maps, 'zakaz-direct-pechat'), [
        '7 ta rangli bosma aparat',
      ]);
    },
  );

  testWidgets(
    'opened orders move module can assign an unassigned alternative to target',
    (tester) async {
      await TestModeController.instance.setEnabled(true);
      await MobileApi.instance.adminSaveProductionMap(
        _alternativeProductionOrderMap(
          id: 'zakaz-alt-unassigned-move',
          title: 'Unassigned alternative move order',
          productCode: 'ALT-UNASSIGNED-MOVE',
          product: 'unassigned alternative move product',
          apparatusIds: const [_print7Id, _print8Id],
          rollCount: 7,
          widthMm: 650,
        ),
      );
      await _usePhoneViewport(tester);
      await tester.pumpWidget(
        MaterialApp(
          theme: ThemeData(useMaterial3: true),
          locale: const Locale('uz'),
          localizationsDelegates: const [
            AppLocalizations.delegate,
            GlobalMaterialLocalizations.delegate,
            GlobalCupertinoLocalizations.delegate,
            GlobalWidgetsLocalizations.delegate,
          ],
          supportedLocales: AppLocalizations.supportedLocales,
          home: const AdminProductionMapOrdersScreen(),
        ),
      );
      await tester.pumpAndSettle();

      await tester.tap(find.text('Ko‘chirish'));
      await tester.pumpAndSettle();
      const orderKey = ValueKey(
        'move-order-7 ta rangli bosma aparat-zakaz-alt-unassigned-move',
      );
      expect(find.byKey(orderKey), findsOneWidget);
      expect(
        find.byKey(
          const ValueKey(
            'move-order-disabled-7 ta rangli bosma aparat-'
            'zakaz-alt-unassigned-move',
          ),
        ),
        findsNothing,
      );

      await _dragOrderHandleForKeyToBottomZone(
        tester,
        key: orderKey,
      );

      final maps = await MobileApi.instance.adminProductionMaps();
      expect(
        _alternativeAssignedTitles(maps, 'zakaz-alt-unassigned-move'),
        [
          '8 ta rangli bosma aparat',
          '8 ta rangli bosma aparat',
        ],
      );
      await tester.pump(const Duration(seconds: 2));
    },
  );

  testWidgets('opened orders move picker hides opposite selected apparatus', (
    tester,
  ) async {
    await TestModeController.instance.setEnabled(true);
    await _usePhoneViewport(tester);
    await tester.pumpWidget(
      MaterialApp(
        theme: ThemeData(useMaterial3: true),
        locale: const Locale('uz'),
        localizationsDelegates: const [
          AppLocalizations.delegate,
          GlobalMaterialLocalizations.delegate,
          GlobalCupertinoLocalizations.delegate,
          GlobalWidgetsLocalizations.delegate,
        ],
        supportedLocales: AppLocalizations.supportedLocales,
        home: const AdminProductionMapOrdersScreen(),
      ),
    );
    await tester.pumpAndSettle();

    await tester.tap(find.text('Ko‘chirish'));
    await tester.pumpAndSettle();

    await tester.tap(
      find.byKey(const ValueKey('move-boundary-apparatus-picker')),
    );
    await tester.pumpAndSettle();
    expect(find.textContaining('7 ta rangli bosma aparat'), findsNWidgets(2));
    Navigator.of(tester.element(find.text('Aparat tanlang'))).pop();
    await tester.pumpAndSettle();

    await tester.tap(find.byKey(const ValueKey('move-top-apparatus-picker')));
    await tester.pumpAndSettle();
    expect(find.textContaining('8 ta rangli bosma aparat'), findsNWidgets(2));
  });

  testWidgets('opened orders move top apparatus picker is centered', (
    tester,
  ) async {
    await TestModeController.instance.setEnabled(true);
    await _usePhoneViewport(tester);
    await tester.pumpWidget(
      MaterialApp(
        theme: ThemeData(useMaterial3: true),
        locale: const Locale('uz'),
        localizationsDelegates: const [
          AppLocalizations.delegate,
          GlobalMaterialLocalizations.delegate,
          GlobalCupertinoLocalizations.delegate,
          GlobalWidgetsLocalizations.delegate,
        ],
        supportedLocales: AppLocalizations.supportedLocales,
        home: const AdminProductionMapOrdersScreen(),
      ),
    );
    await tester.pumpAndSettle();

    await tester.tap(find.text('Ko‘chirish'));
    await tester.pumpAndSettle();

    final pickerRect = tester.getRect(
      find.descendant(
        of: find.byKey(const ValueKey('move-top-apparatus-picker')),
        matching: find.textContaining('7 ta rangli bosma aparat'),
      ),
    );
    final screenCenterX = tester.getSize(find.byType(MaterialApp)).width / 2;
    expect((pickerRect.center.dx - screenCenterX).abs(), lessThan(8));
  });

  testWidgets('opened orders move module boundary resizes zones', (
    tester,
  ) async {
    await TestModeController.instance.setEnabled(true);
    await MobileApi.instance.adminSaveProductionMap(
      _productionOrderMap(
        id: 'zakaz-resize-a',
        title: 'Resize top order',
        productCode: 'RESIZE-A',
        apparatusId: _print7Id,
        product: 'resize product a',
        rollCount: 7,
        widthMm: 650,
      ),
    );
    await MobileApi.instance.adminSaveProductionMap(
      _productionOrderMap(
        id: 'zakaz-resize-b',
        title: 'Resize bottom order',
        productCode: 'RESIZE-B',
        apparatusId: _print8Id,
        product: 'resize product b',
        rollCount: 7,
        widthMm: 650,
      ),
    );
    await _usePhoneViewport(tester);
    await tester.pumpWidget(
      MaterialApp(
        theme: ThemeData(useMaterial3: true),
        locale: const Locale('uz'),
        localizationsDelegates: const [
          AppLocalizations.delegate,
          GlobalMaterialLocalizations.delegate,
          GlobalCupertinoLocalizations.delegate,
          GlobalWidgetsLocalizations.delegate,
        ],
        supportedLocales: AppLocalizations.supportedLocales,
        home: const AdminProductionMapOrdersScreen(),
      ),
    );
    await tester.pumpAndSettle();

    await tester.tap(find.text('Ko‘chirish'));
    await tester.pumpAndSettle();
    final boundary = find.byKey(
      const ValueKey('move-boundary-apparatus-picker'),
    );
    final before = tester.getTopLeft(boundary).dy;
    final gesture = await tester.startGesture(tester.getCenter(boundary));
    await gesture.moveBy(const Offset(0, 160));
    await gesture.up();
    await tester.pumpAndSettle();

    expect(tester.getTopLeft(boundary).dy, greaterThan(before + 40));
  });
}
