// Generated by large_library_splitter.dart; keep changes in the source library.
part of 'admin_customer_detail_screen_test.dart';

void _registeradmin_customer_detail_screen_testCases01() {
  testWidgets('customer detail shows direct chat action', (tester) async {
    await tester.pumpWidget(
      MaterialApp(
        home: AdminCustomerDetailScreen(
          customerRef: 'CUSTOMER-001',
          chatTarget: const ChatDirectoryEntry(
            role: UserRole.customer,
            ref: 'CUSTOMER-001',
            displayName: 'Customer',
            avatarUrl: '',
          ),
          detailLoader: (_) async => const AdminCustomerDetail(
            ref: 'CUSTOMER-001',
            name: 'Customer',
            phone: '+998901234567',
            avatarUrl: '',
            code: '',
            codeLocked: false,
            codeRetryAfterSec: 0,
            assignedItems: [],
          ),
        ),
      ),
    );

    await tester.pump();
    await tester.pump(const Duration(milliseconds: 50));
    await tester.pump(const Duration(milliseconds: 250));

    expect(
      find.byKey(const ValueKey('admin-customer-detail-chat-action')),
      findsOneWidget,
    );
  });

  testWidgets('material detail shows direct chat action', (tester) async {
    await tester.pumpWidget(
      MaterialApp(
        home: AdminCustomerDetailScreen(
          customerRef: 'MAT-001',
          isMaterialTaminotchi: true,
          chatTarget: const ChatDirectoryEntry(
            role: UserRole.materialTaminotchi,
            ref: 'MAT-001',
            displayName: 'Materialchi',
            avatarUrl: '',
          ),
          detailLoader: (_) async => const AdminCustomerDetail(
            ref: 'MAT-001',
            name: 'Materialchi',
            phone: '+998901234567',
            avatarUrl: '',
            code: '',
            codeLocked: false,
            codeRetryAfterSec: 0,
            assignedItems: [],
          ),
        ),
      ),
    );

    await tester.pump();
    await tester.pump(const Duration(milliseconds: 50));
    await tester.pump(const Duration(milliseconds: 250));

    expect(
      find.byKey(const ValueKey('admin-customer-detail-chat-action')),
      findsOneWidget,
    );
    expect(find.text('Xabar yozish'), findsOneWidget);
  });

  testWidgets('admin customer detail renders loaded content', (tester) async {
    await tester.pumpWidget(
      MaterialApp(
        home: AdminCustomerDetailScreen(
          customerRef: 'comfi',
          customerManagementEnabled: true,
          detailLoader: (_) async => const AdminCustomerDetail(
            ref: 'comfi',
            name: 'comfi',
            phone: '+998901000333',
            avatarUrl: '',
            code: '30SFT8WLPTR9',
            codeLocked: false,
            codeRetryAfterSec: 0,
            assignedItems: [],
          ),
        ),
      ),
    );

    await tester.pump();
    await tester.pump(const Duration(milliseconds: 50));
    await tester.pump(const Duration(milliseconds: 250));

    expect(tester.takeException(), isNull);
    expect(find.text('Profil'), findsOneWidget);
    expect(find.byType(AdminDock), findsOneWidget);
    expect(find.text('comfi'), findsWidgets);
    expect(find.text('+998901000333'), findsOneWidget);
    expect(find.text('Ref'), findsNothing);
    expect(find.text('Admin boshqaruv'), findsNothing);

    await tester.tap(
      find.byKey(const ValueKey('admin-customer-detail-admin-toggle')),
    );
    await tester.pump(const Duration(milliseconds: 250));
    expect(find.text('Admin boshqaruv'), findsOneWidget);
    expect(find.text('30SFT8WLPTR9'), findsOneWidget);
    tester
        .widget<IconButton>(
          find.byKey(const ValueKey('admin-customer-detail-phone-action')),
        )
        .onPressed!();
    await tester.pumpAndSettle();
    expect(find.byType(AlertDialog), findsNothing);
    expect(
      find.byKey(const ValueKey('admin-customer-detail-phone-input')),
      findsOneWidget,
    );
  });

  testWidgets('admin customer detail renders with semantics enabled', (
    tester,
  ) async {
    final semantics = tester.ensureSemantics();

    await tester.pumpWidget(
      MaterialApp(
        home: AdminCustomerDetailScreen(
          customerRef: 'comfi',
          detailLoader: (_) async => const AdminCustomerDetail(
            ref: 'comfi',
            name: 'comfi',
            phone: '+998901000333',
            avatarUrl: '',
            code: '30SFT8WLPTR9',
            codeLocked: false,
            codeRetryAfterSec: 0,
            assignedItems: [],
          ),
        ),
      ),
    );

    await tester.pump();
    await tester.pump(const Duration(milliseconds: 50));
    await tester.pump(const Duration(milliseconds: 250));

    expect(tester.takeException(), isNull);
    expect(find.text('comfi'), findsWidgets);
    expect(find.text('+998901000333'), findsOneWidget);
    semantics.dispose();
  });

  testWidgets('material taminotchi detail keeps phone and code controls', (
    tester,
  ) async {
    String? savedPhone;
    var codeRegenerated = false;

    await tester.pumpWidget(
      MaterialApp(
        home: AdminCustomerDetailScreen(
          customerRef: 'MAT-001',
          title: 'Material taminotchisi',
          profileSubtitle: 'Material ta’minotchisi profili',
          emptyName: 'Material taminotchisi',
          namelessLabel: 'Nomsiz material ta’minotchisi',
          customerManagementEnabled: true,
          itemManagementEnabled: false,
          removeEnabled: false,
          isMaterialTaminotchi: true,
          detailLoader: (_) async => const AdminCustomerDetail(
            ref: 'MAT-001',
            name: 'Materialchi',
            phone: '+998901000333',
            avatarUrl: '',
            code: '70ABCDEF1234',
            codeLocked: false,
            codeRetryAfterSec: 0,
            assignedItems: [],
            assignedItemGroups: ['Rulon'],
            assignedWarehouses: ['Kalidor'],
          ),
          phoneUpdater: ({required phone, required ref}) async {
            savedPhone = phone;
            return AdminCustomerDetail(
              ref: ref,
              name: 'Materialchi',
              phone: phone,
              avatarUrl: '',
              code: '70ABCDEF1234',
              codeLocked: false,
              codeRetryAfterSec: 0,
              assignedItems: const [],
            );
          },
          codeRegenerator: (ref) async {
            codeRegenerated = true;
            return AdminCustomerDetail(
              ref: ref,
              name: 'Materialchi',
              phone: '+998901000333',
              avatarUrl: '',
              code: '70ZZZZZZZZZZ',
              codeLocked: false,
              codeRetryAfterSec: 0,
              assignedItems: const [],
            );
          },
        ),
      ),
    );

    await tester.pump();
    await tester.pump(const Duration(milliseconds: 50));
    await tester.pump(const Duration(milliseconds: 250));

    await tester.tap(
      find.byKey(const ValueKey('admin-customer-detail-admin-toggle')),
    );
    await tester.pump(const Duration(milliseconds: 250));
    expect(find.text('Admin boshqaruv'), findsOneWidget);
    expect(find.text('70ABCDEF1234'), findsOneWidget);
    expect(find.text('Mahsulot guruhlari'), findsOneWidget);
    expect(find.text('Biriktirilgan omborlar'), findsOneWidget);
    expect(find.text('Rulon'), findsOneWidget);
    expect(find.text('Kalidor'), findsOneWidget);
    expect(find.text('Biriktirilgan mahsulotlar'), findsNothing);
    expect(find.text('Tizimdan chiqarish'), findsNothing);

    tester
        .widget<IconButton>(
          find.byKey(const ValueKey('admin-customer-detail-phone-action')),
        )
        .onPressed!();
    await tester.pump(const Duration(milliseconds: 250));
    await tester.enterText(
      find.byKey(const ValueKey('admin-customer-detail-phone-input')),
      '+998909999999',
    );
    tester
        .widget<IconButton>(
          find.byKey(const ValueKey('admin-customer-detail-phone-action')),
        )
        .onPressed!();
    await tester.pump(const Duration(milliseconds: 250));
    expect(savedPhone, '+998909999999');
    expect(find.text('+998909999999'), findsWidgets);

    tester
        .widget<IconButton>(
          find.byKey(const ValueKey('admin-customer-detail-code-regenerate')),
        )
        .onPressed!();
    await tester.pump(const Duration(milliseconds: 250));
    expect(codeRegenerated, isTrue);
    expect(find.text('70ZZZZZZZZZZ'), findsOneWidget);
  });
}
