// Generated by large_library_splitter.dart; keep changes in the source library.
part of 'gscale_material_receipt_print_test.dart';

void _registergscale_material_receipt_print_testCases02() {
  test('material batch reprint uses aggregate weight and a batch QR', () {
    const prints = [
      MobileArchivePrintEntry(
        itemCode: 'CPP 1030/25',
        itemName: 'CPP 1030/25',
        qty: 23,
        grossQty: 23,
        netQty: 23,
        unit: 'kg',
        printedAt: '',
        draftName: 'MAT-STE-1',
        epc: '400100000000000000000001',
      ),
      MobileArchivePrintEntry(
        itemCode: 'CPP 1030/25',
        itemName: 'CPP 1030/25',
        qty: 23,
        grossQty: 23,
        netQty: 23,
        unit: 'kg',
        printedAt: '',
        draftName: 'MAT-STE-2',
        epc: '400100000000000000000002',
      ),
      MobileArchivePrintEntry(
        itemCode: 'CPP 1030/25',
        itemName: 'CPP 1030/25',
        qty: 23,
        grossQty: 23,
        netQty: 23,
        unit: 'kg',
        printedAt: '',
        draftName: 'MAT-STE-3',
        epc: '400100000000000000000003',
      ),
      MobileArchivePrintEntry(
        itemCode: 'CPP 1030/25',
        itemName: 'CPP 1030/25',
        qty: 23,
        grossQty: 23,
        netQty: 23,
        unit: 'kg',
        printedAt: '',
        draftName: 'MAT-STE-4',
        epc: '400100000000000000000004',
      ),
    ];
    const session = MobileArchiveSession(
      sessionId: 'batch-history-92',
      batchCode: '42A1234567890ABCDEF12345',
      active: false,
      itemCode: 'CPP 1030/25',
      itemName: 'CPP 1030/25',
      warehouse: 'Kalidor',
      startedAt: '',
      endedAt: '',
      totalQty: 92,
      grossQty: 92,
      netQty: 92,
      unit: 'kg',
      tareEnabled: false,
      tareKg: 0,
      printCount: 4,
      prints: prints,
    );

    final plan = buildMaterialBatchPrintPlan(session);
    final request = plan.toDriverRequest(printer: 'zebra');

    expect(plan.grossQty, 92);
    expect(plan.netQty, 92);
    expect(plan.qrPayload, 'RPS-BATCH:42A1234567890ABCDEF12345');
    expect(
      plan.toUsbRequest(printer: 'godex').largeQrLabelFooter(plan.qrPayload),
      'BATCH ID: 42A1234567890ABCDEF12345',
    );
    expect(prints.map((entry) => entry.epc), isNot(contains(plan.qrPayload)));
    expect(request['gross_qty'], 92);
    expect(request['print_mode'], 'label');
    expect(request['label_kind'], 'qolip_code');
    expect(request['print_count'], 1);
  });

  test('material batch QR keeps legacy fallback and rejects a corrupt code',
      () {
    const legacy = MobileArchiveSession(
      sessionId: 'legacy-batch-1',
      active: false,
      itemCode: 'ITEM-1',
      itemName: 'Green Tea',
      warehouse: 'Stores - A',
      startedAt: '',
      endedAt: '',
      totalQty: 1,
      grossQty: 1,
      netQty: 1,
      unit: 'kg',
      tareEnabled: false,
      tareKg: 0,
      printCount: 1,
      prints: [],
    );
    expect(
      buildMaterialBatchPrintPlan(legacy).qrPayload,
      'RPS-BATCH:LEGACY-BATCH-1',
    );

    const corrupt = MobileArchiveSession(
      sessionId: 'batch-2',
      batchCode: 'NOT-A-BATCH-CODE',
      active: false,
      itemCode: 'ITEM-1',
      itemName: 'Green Tea',
      warehouse: 'Stores - A',
      startedAt: '',
      endedAt: '',
      totalQty: 1,
      grossQty: 1,
      netQty: 1,
      unit: 'kg',
      tareEnabled: false,
      tareKg: 0,
      printCount: 1,
      prints: [],
    );
    expect(
      () => buildMaterialBatchPrintPlan(corrupt),
      throwsA(isA<StateError>()),
    );
  });

  testWidgets(
    'material control restores active manual batch without selected device',
    (tester) async {
      SharedPreferences.setMockInitialValues({});
      await saveOperatorControlDraft(
        const OperatorControlDraft(
          itemCode: 'STALE-ITEM',
          itemName: 'Stale product',
          warehouse: 'Wrong warehouse',
          printMode: 'rfid',
          printer: 'zebra',
          quantitySource: 'manual',
          manualQtyText: '',
          manualDuplicateText: '',
          babinaEnabled: false,
          babinaText: '',
          warehouseMode: 'manual',
          defaultWarehouse: '',
        ),
      );
      AppSession.instance.token = 'token';
      AppSession.instance.profile = const SessionProfile(
        role: UserRole.materialTaminotchi,
        displayName: 'Materialchi',
        legalName: '',
        ref: 'MAT-RECOVERY',
        phone: '+998900000001',
        avatarUrl: '',
        capabilities: ['rps.batch.manage', 'gscale.print'],
        assignedItemGroups: ['Rulon'],
        assignedWarehouses: ['Kalidor'],
      );
      var stateLoadCount = 0;
      GScaleRpsBatchUpdateRequest? capturedUpdate;
      const activeBatch = GScaleRpsBatchSession(
        id: 'batch-active-1',
        revision: 1,
        active: true,
        driverUrl: 'usb://local',
        itemCode: 'ITEM-1',
        itemName: 'Green Tea',
        warehouse: 'Kalidor',
        printer: 'godex',
        printMode: 'label',
        quantitySource: 'manual',
        manualQtyKg: 23,
        tareEnabled: false,
        tareKg: 0,
        widthMm: 783,
        micron: 18,
      );
      const offlinePrinter = UsbPrinterProfile(
        kind: UsbPrinterKind.godex,
        deviceName: 'usb:test',
        vendorId: 1,
        productId: 2,
        manufacturerName: 'GoDEX',
        productName: 'G500',
      );

      await tester.pumpWidget(
        MaterialApp(
          home: Scaffold(
            body: OperatorDashboardPage(
              server: null,
              printTransport: PrintTransport.offline,
              offlinePrinter: offlinePrinter,
              controlOnly: true,
              onExitMode: () async {},
              onChangeServer: () async {},
              rpsBatchStateLoader: () async {
                stateLoadCount++;
                return const GScaleRpsBatchResponse(
                  ok: true,
                  batch: activeBatch,
                );
              },
              rpsBatchUpdater: (request) async {
                capturedUpdate = request;
                return const GScaleRpsBatchResponse(
                  ok: true,
                  batch: GScaleRpsBatchSession(
                    id: 'batch-active-1',
                    revision: 2,
                    active: true,
                    driverUrl: 'usb://local',
                    itemCode: 'ITEM-1',
                    itemName: 'Green Tea',
                    warehouse: 'Kalidor',
                    printer: 'godex',
                    printMode: 'label',
                    quantitySource: 'manual',
                    manualQtyKg: 23,
                    tareEnabled: true,
                    tareKg: 0.78,
                    widthMm: 800,
                    micron: 20,
                  ),
                );
              },
            ),
          ),
        ),
      );
      await tester.pumpAndSettle();

      expect(stateLoadCount, 1);
      expect(find.text('Batch ma’lumoti'), findsNothing);
      expect(find.text('Green Tea • 783 mm • 18 mikron'), findsOneWidget);
      expect(
        find.text('Ombor: Kalidor • Qo‘lda kg • Babina: Yo‘q'),
        findsOneWidget,
      );
      expect(find.text('Tahrirlash'), findsNothing);
      expect(
        find.byTooltip('Batch ma’lumotini tahrirlash'),
        findsOneWidget,
      );
      expect(find.text('Mahsulot tanlang'), findsNothing);
      expect(find.text('Eni (mm)'), findsNothing);
      expect(find.text('Mikron'), findsNothing);
      expect(find.text('Ombor tanlang'), findsNothing);
      expect(find.text('STALE-ITEM'), findsNothing);
      expect(find.text('Wrong warehouse'), findsNothing);
      expect(
        tester
            .widget<FilledButton>(
              find.widgetWithText(FilledButton, 'Batch stop'),
            )
            .onPressed,
        isNotNull,
      );
      expect(
        find.widgetWithText(FilledButton, 'Batch start'),
        findsNothing,
      );

      await tester.tap(find.byTooltip('Batch ma’lumotini tahrirlash'));
      await tester.pump();

      expect(find.text('Batch ma’lumoti'), findsNothing);
      expect(find.text('Mahsulot tanlang'), findsOneWidget);
      expect(find.text('Eni (mm)'), findsOneWidget);
      expect(find.text('Mikron'), findsOneWidget);
      expect(find.text('Ombor tanlang'), findsOneWidget);
      expect(find.widgetWithText(FilledButton, 'Saqlash'), findsOneWidget);
      expect(find.text('Miqdor (kg)'), findsOneWidget);
      expect(find.text('Babina'), findsOneWidget);
      expect(find.byType(Switch), findsNWidgets(2));

      await tester.tap(find.byType(Switch).at(0));
      await tester.pump();
      await tester.tap(find.byType(Switch).at(0));
      await tester.pump();
      await tester.tap(find.byType(Switch).at(1));
      await tester.pump();
      expect(
        tester
            .widget<FilledButton>(
              find.widgetWithText(FilledButton, 'Saqlash'),
            )
            .onPressed,
        isNotNull,
      );
      await tester.enterText(
        find.widgetWithText(TextField, 'Babina og‘irligi'),
        '0.78',
      );

      await tester.enterText(
        find.widgetWithText(TextField, 'Eni (mm)'),
        '800',
      );
      await tester.enterText(
        find.widgetWithText(TextField, 'Mikron'),
        '20',
      );
      await tester.tap(find.widgetWithText(FilledButton, 'Saqlash'));
      await tester.pumpAndSettle();

      expect(capturedUpdate?.batchId, 'batch-active-1');
      expect(capturedUpdate?.expectedRevision, 1);
      expect(capturedUpdate?.itemCode, 'ITEM-1');
      expect(capturedUpdate?.warehouse, 'Kalidor');
      expect(capturedUpdate?.widthMm, 800);
      expect(capturedUpdate?.micron, 20);
      expect(capturedUpdate?.quantitySource, 'manual');
      expect(capturedUpdate?.tareEnabled, isTrue);
      expect(capturedUpdate?.tareKg, 0.78);
      expect(find.text('Batch ma’lumoti'), findsNothing);
      expect(find.text('Green Tea • 800 mm • 20 mikron'), findsOneWidget);
      expect(
        find.text('Ombor: Kalidor • Qo‘lda kg • Babina: 0.78 kg'),
        findsOneWidget,
      );
      expect(find.text('Mahsulot tanlang'), findsNothing);
      final babinaField = tester.widget<TextField>(
        find.widgetWithText(TextField, 'Babina og‘irligi'),
      );
      expect(babinaField.enabled, isTrue);
      await tester.enterText(
        find.widgetWithText(TextField, 'Babina og‘irligi'),
        '0.80',
      );

      await tester.enterText(
        find.widgetWithText(TextField, 'Qo‘lda brutto kg'),
        '23',
      );
      await tester.pump();

      expect(
        tester
            .widget<FilledButton>(
              find.widgetWithText(FilledButton, 'Chop etish'),
            )
            .onPressed,
        isNotNull,
      );
    },
  );
}
