// Generated by large_library_splitter.dart; keep changes in the source library.
part of 'inventory_movements_test.dart';

void _registerinventory_movements_testCases01() {
  test('inventory state rejects display-name apparatus identity', () {
    expect(
      () => InventoryLocation.fromJson(const {
        'id': 'inventory_location:state:legacy',
        'kind': 'state',
        'name': 'Legacy state',
        'apparatus': [
          {'id': 'Flexo pechat', 'name': 'Flexo pechat'},
        ],
      }),
      throwsFormatException,
    );
  });
}
