include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - third_party/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - linux/**

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_locals: true
