// Generated by large_library_splitter.dart; keep changes in the source library.
part of '../mobile_api.dart';

extension MobileApiAdminUsersWorkersAstPart02 on MobileApi {
  Future<AdminWorkerProfileDetail> adminWorkerProfileDetail(String id) async {
    if (await TestModeController.instance.isEnabled()) {
      final worker = await adminWorkerDetail(id);
      final groups = _testModeWorkerGroups
          .where((group) => group.workerIds.any((workerId) => workerId == id))
          .map(_hydrateTestModeWorkerGroup)
          .toList(growable: false);
      return AdminWorkerProfileDetail(
        worker: worker,
        assignedGroups: groups,
        activeSessions: const [],
        recentBatches: const [],
        recentLogs: const [],
      );
    }
    final response = await _sendAuthorized(
      () => _get(
        Uri.parse(
          '${MobileApi.baseUrl}/v1/mobile/admin/workers/profile-detail',
        ).replace(queryParameters: {'id': id}),
        headers: _headers(requireToken()),
      ),
    );
    if (response.statusCode != 200) {
      throw Exception('Admin worker profile detail failed');
    }
    return AdminWorkerProfileDetail.fromJson(
      jsonDecode(response.body) as Map<String, dynamic>,
    );
  }

  Future<AdminWorkerDeletionCheck> adminWorkerDeletionCheck(String id) async {
    if (await TestModeController.instance.isEnabled()) {
      final worker = _testModeWorkers.firstWhere(
        (worker) => worker.id == id,
        orElse: () => throw Exception('Admin worker not found'),
      );
      final groups = _testModeWorkerGroups.where(
        (group) => group.workerIds.any((workerId) => workerId == id),
      );
      final apparatuses = groups
          .map((group) => group.apparatus.trim())
          .where(
            (apparatus) =>
                apparatus.isNotEmpty && apparatus != 'worker-settings',
          )
          .toSet();
      final connections = <AdminWorkerDeletionDependency>[
        for (final group in groups)
          AdminWorkerDeletionDependency(
            kind: 'worker_group',
            label: group.groupCode,
            apparatus: group.apparatus,
            orderId: '',
            status: '',
          ),
        for (final apparatus in apparatuses)
          AdminWorkerDeletionDependency(
            kind: 'apparatus',
            label: apparatus,
            apparatus: apparatus,
            orderId: '',
            status: '',
          ),
      ];
      return AdminWorkerDeletionCheck(
        workerId: worker.id,
        workerName: worker.name,
        blocked: false,
        requiresConfirmation: connections.isNotEmpty,
        activeWork: const [],
        connections: connections,
      );
    }
    final response = await _sendAuthorized(
      () => _get(
        Uri.parse(
          '${MobileApi.baseUrl}/v1/mobile/admin/workers/delete-check',
        ).replace(queryParameters: {'id': id}),
        headers: _headers(requireToken()),
      ),
    );
    if (response.statusCode != 200) {
      throw _adminApiException(
        response,
        fallbackCode: 'worker_delete_check_failed',
        fallbackMessage: 'Ishchi ulanishlari tekshirilmadi',
      );
    }
    return AdminWorkerDeletionCheck.fromJson(
      (jsonDecode(response.body) as Map).cast<String, dynamic>(),
    );
  }

  Future<void> adminDeactivateWorker({
    required String id,
    required bool confirmConnections,
  }) async {
    if (await TestModeController.instance.isEnabled()) {
      final check = await adminWorkerDeletionCheck(id);
      if (check.blocked || check.requiresConfirmation && !confirmConnections) {
        throw AdminWorkerDeletionRejected(check);
      }
      for (var index = 0; index < _testModeWorkerGroups.length; index++) {
        final group = _testModeWorkerGroups[index];
        _testModeWorkerGroups[index] = group.copyWith(
          workerIds: group.workerIds
              .where((workerId) => workerId != id)
              .toList(growable: false),
        );
      }
      final workerExists = _testModeWorkers.any((worker) => worker.id == id);
      if (!workerExists) {
        throw Exception('Admin worker not found');
      }
      _testModeWorkers.removeWhere((worker) => worker.id == id);
      _testModeRoleAssignments.removeWhere(
        (assignment) =>
            assignment.principalRole == UserRole.aparatchi &&
            assignment.principalRef.trim() == id.trim(),
      );
      _testModeWorkerCodes.remove(id);
      return;
    }
    final response = await _sendAuthorized(
      () => _delete(
        Uri.parse('${MobileApi.baseUrl}/v1/mobile/admin/workers').replace(
          queryParameters: {
            'id': id,
            if (confirmConnections) 'confirm_connections': 'true',
          },
        ),
        headers: _headers(requireToken()),
      ),
    );
    if (response.statusCode == 409) {
      throw AdminWorkerDeletionRejected(
        AdminWorkerDeletionCheck.fromJson(
          (jsonDecode(response.body) as Map).cast<String, dynamic>(),
        ),
      );
    }
    if (response.statusCode != 200) {
      throw _adminApiException(
        response,
        fallbackCode: 'worker_delete_failed',
        fallbackMessage: 'Ishchi faolsizlantirilmadi',
      );
    }
  }

  Future<AdminWorkerDetail> adminRegenerateWorkerCode(String id) async {
    if (await TestModeController.instance.isEnabled()) {
      final worker = _testModeWorkers.firstWhere(
        (worker) => worker.id == id,
        orElse: () => throw Exception('Admin worker not found'),
      );
      final code =
          '40${DateTime.now().microsecondsSinceEpoch.toString().padLeft(10, '0').substring(0, 10)}';
      _testModeWorkerCodes[worker.id] = code;
      return AdminWorkerDetail(
        id: worker.id,
        name: worker.name,
        phone: worker.phone,
        avatarUrl: '',
        level: worker.level,
        code: code,
        codeLocked: false,
        codeRetryAfterSec: 0,
      );
    }
    final response = await _sendAuthorized(
      () => _post(
        Uri.parse(
          '${MobileApi.baseUrl}/v1/mobile/admin/workers/code/regenerate',
        ).replace(queryParameters: {'id': id}),
        headers: _headers(requireToken()),
      ),
    );
    if (response.statusCode != 200) {
      throw Exception('Admin worker code regenerate failed');
    }
    return AdminWorkerDetail.fromJson(
      jsonDecode(response.body) as Map<String, dynamic>,
    );
  }

  Future<List<AdminWorkerGroup>> adminWorkerGroups({
    String apparatusId = '',
  }) async {
    final normalizedApparatusId = _requireCanonicalApparatusId(
      apparatusId,
      allowEmpty: true,
    );
    if (await TestModeController.instance.isEnabled()) {
      final key = normalizedApparatusId;
      return _testModeWorkerGroups
          .where(
            (group) => key.isEmpty || group.apparatusId.trim() == key,
          )
          .map(_hydrateTestModeWorkerGroup)
          .toList(growable: false);
    }
    final response = await _sendAuthorized(
      () => _get(
        Uri.parse('${MobileApi.baseUrl}/v1/mobile/admin/worker-groups').replace(
          queryParameters: {
            if (normalizedApparatusId.isNotEmpty)
              'apparatus_id': normalizedApparatusId,
          },
        ),
        headers: _headers(requireToken()),
      ),
    );
    if (response.statusCode != 200) {
      throw Exception('Admin worker groups failed');
    }
    final json = await decodeJsonListPayload(response.body);
    return json
        .map((item) => AdminWorkerGroup.fromJson(item as Map<String, dynamic>))
        .toList(growable: false);
  }

  Future<AdminWorkerGroup> adminSaveWorkerGroup(
    AdminWorkerGroup group, {
    String? previousApparatusId,
    String? previousGroupCode,
  }) async {
    _requireCanonicalApparatusId(group.apparatusId);
    final validatedPreviousApparatusId = _requireCanonicalApparatusId(
      previousApparatusId ?? '',
      allowEmpty: true,
    );
    if (await TestModeController.instance.isEnabled()) {
      final normalized = _normalizeTestModeWorkerGroup(group);
      final key = normalized.apparatusId.trim();
      final code = normalized.groupCode.trim().toUpperCase();
      final previousKey = previousApparatusId?.trim();
      final previousCode = previousGroupCode == null
          ? null
          : previousGroupCode
              .trim()
              .split(RegExp(r'\s+'))
              .join(' ')
              .toUpperCase();
      final hasPreviousIdentity = previousKey != null &&
          previousKey.isNotEmpty &&
          previousCode != null &&
          previousCode.isNotEmpty;
      final previousExists = !hasPreviousIdentity ||
          _testModeWorkerGroups.any(
            (item) =>
                item.apparatusId.trim() == previousKey &&
                item.groupCode.trim().toUpperCase() == previousCode,
          );
      if (!previousExists) {
        throw const MobileApiException(
          code: 'worker_group_not_found',
          message: 'Guruh topilmadi',
        );
      }
      final isPreviousGroup = (AdminWorkerGroup item) {
        if (hasPreviousIdentity) {
          return item.apparatusId.trim() == previousKey &&
              item.groupCode.trim().toUpperCase() == previousCode;
        }
        return item.apparatusId.trim() == key &&
            item.groupCode.trim().toUpperCase() == code;
      };
      final duplicateName = _testModeWorkerGroups.any(
        (item) =>
            item.apparatusId.trim() == key &&
            item.groupCode.trim().toUpperCase() == code &&
            !isPreviousGroup(item),
      );
      if (duplicateName) {
        throw const MobileApiException(
          code: 'worker_group_name_exists',
          message: 'Bu guruh nomi allaqachon bor',
        );
      }
      final duplicate = _testModeWorkerGroups.any(
        (item) =>
            item.apparatusId.trim() == key &&
            !isPreviousGroup(item) &&
            item.workerIds.any(normalized.workerIds.toSet().contains),
      );
      if (duplicate) {
        throw const MobileApiException(
          code: 'worker_duplicated_in_group',
          message: 'Ishchi boshqa guruhga ulangan',
        );
      }
      _testModeWorkerGroups.removeWhere(isPreviousGroup);
      _testModeWorkerGroups.add(normalized);
      return _hydrateTestModeWorkerGroup(normalized);
    }
    final payload = group.toJson();
    final normalizedPreviousApparatusId = validatedPreviousApparatusId;
    final normalizedPreviousGroupCode = previousGroupCode?.trim() ?? '';
    if (normalizedPreviousApparatusId.isNotEmpty) {
      payload['previous_apparatus_id'] = normalizedPreviousApparatusId;
    }
    if (normalizedPreviousGroupCode.isNotEmpty) {
      payload['previous_group_code'] = normalizedPreviousGroupCode;
    }
    final response = await _sendAuthorized(
      () => _put(
        Uri.parse('${MobileApi.baseUrl}/v1/mobile/admin/worker-groups'),
        headers: _headers(requireToken())
          ..['Content-Type'] = 'application/json',
        body: jsonEncode(payload),
      ),
    );
    if (response.statusCode != 200) {
      throw Exception('Admin worker group save failed');
    }
    return AdminWorkerGroup.fromJson(
      jsonDecode(response.body) as Map<String, dynamic>,
    );
  }

  AdminWorkerGroup _normalizeTestModeWorkerGroup(AdminWorkerGroup group) {
    final canonical = _testModeRequiredApparatus(group.apparatusId);
    final workerIds = group.workerIds
        .map((id) => id.trim())
        .where((id) => id.isNotEmpty)
        .toSet()
        .toList(growable: false);
    final groupCode =
        group.groupCode.trim().split(RegExp(r'\s+')).join(' ').toUpperCase();
    return AdminWorkerGroup(
      apparatus: canonical.name.trim(),
      apparatusId: canonical.id.trim(),
      groupCode: groupCode,
      shift: group.shift.trim().isEmpty ? 'kunduz' : group.shift.trim(),
      startTime:
          group.startTime.trim().isEmpty ? '08:00' : group.startTime.trim(),
      endTime: group.endTime.trim().isEmpty ? '20:00' : group.endTime.trim(),
      workDaysPerWeek: group.workDaysPerWeek.clamp(1, 7).toInt(),
      startDay:
          group.startDay.trim().isEmpty ? 'monday' : group.startDay.trim(),
      accountingEnabled: group.accountingEnabled,
      workerIds: workerIds,
    );
  }

  AdminWorkerGroup _hydrateTestModeWorkerGroup(AdminWorkerGroup group) {
    return group.copyWith(
      workers: [
        for (final id in group.workerIds)
          for (final worker in _testModeWorkers)
            if (worker.id == id) worker,
      ],
    );
  }

  Future<AdminRoleAssignment> adminUpsertRoleAssignment(
    AdminRoleAssignment assignment,
  ) async {
    final invalidApparatusId = assignment.assignedApparatus.any(
      (item) => !isCanonicalApparatusId(item),
    );
    if (invalidApparatusId) {
      throw const MobileApiException(
        code: 'apparatus_id_invalid',
        message: 'Canonical apparatus ID noto‘g‘ri',
      );
    }
    if (await TestModeController.instance.isEnabled()) {
      final normalized = AdminRoleAssignment(
        principalRole: assignment.principalRole,
        principalRef: assignment.principalRef.trim(),
        roleId: assignment.roleId.trim(),
        assignedApparatus: assignment.assignedApparatus
            .map((item) => item.trim())
            .where(isCanonicalApparatusId)
            .toSet()
            .toList(growable: false),
        assignedItemGroups: assignment.assignedItemGroups
            .map((item) => item.trim())
            .where((item) => item.isNotEmpty)
            .toSet()
            .toList(growable: false),
      );
      final index = _testModeRoleAssignments.indexWhere(
        (item) =>
            item.principalRole == normalized.principalRole &&
            item.principalRef.trim() == normalized.principalRef,
      );
      if (index >= 0) {
        _testModeRoleAssignments[index] = normalized;
      } else {
        _testModeRoleAssignments.add(normalized);
      }
      return normalized;
    }
    final response = await _sendAuthorized(
      () => _put(
        Uri.parse('${MobileApi.baseUrl}/v1/mobile/admin/role-assignments'),
        headers: _headers(requireToken())
          ..['Content-Type'] = 'application/json',
        body: jsonEncode(assignment.toJson()),
      ),
    );
    if (response.statusCode != 200) {
      throw _adminApiException(
        response,
        fallbackCode: 'admin_role_assignment_save_failed',
        fallbackMessage: 'Role biriktirish saqlanmadi',
      );
    }
    return AdminRoleAssignment.fromJson(
      jsonDecode(response.body) as Map<String, dynamic>,
    );
  }
}
