// Generated by large_library_splitter.dart; keep changes in the source library.
part of '../mobile_api.dart';

extension MobileApiAdminSettingsMonitor on MobileApi {
  String get baseUrl => MobileApi.baseUrl;

  Future<AdminSettings> adminSettings() async {
    if (await TestModeController.instance.isEnabled()) {
      return TestModeDemoData.adminSettings;
    }
    final response = await _sendAuthorized(
      () => _get(
        Uri.parse('${MobileApi.baseUrl}/v1/mobile/admin/settings'),
        headers: _headers(requireToken()),
      ),
    );
    if (response.statusCode != 200) {
      throw Exception('Admin settings failed');
    }
    return AdminSettings.fromJson(
      jsonDecode(response.body) as Map<String, dynamic>,
    );
  }

  Future<AdminSettings> updateAdminSettings(AdminSettings settings) async {
    final response = await _sendAuthorized(
      () => _put(
        Uri.parse('${MobileApi.baseUrl}/v1/mobile/admin/settings'),
        headers: _headers(requireToken())
          ..['Content-Type'] = 'application/json',
        body: jsonEncode(settings.toJson()),
      ),
    );
    if (response.statusCode != 200) {
      throw Exception('Admin settings update failed');
    }
    return AdminSettings.fromJson(
      jsonDecode(response.body) as Map<String, dynamic>,
    );
  }

  Future<List<DispatchRecord>> adminActivity() async {
    final response = await _sendAuthorized(
      () => _get(
        Uri.parse('${MobileApi.baseUrl}/v1/mobile/admin/activity'),
        headers: _headers(requireToken()),
      ),
    );
    if (response.statusCode != 200) {
      throw Exception('Admin activity failed');
    }
    final json = await decodeJsonListPayload(response.body);
    return json
        .map((item) => DispatchRecord.fromJson(item as Map<String, dynamic>))
        .toList();
  }

  Future<AdminServerMonitorReport> adminServerMonitor() async {
    if (await TestModeController.instance.isEnabled()) {
      final now = DateTime.now().millisecondsSinceEpoch ~/ 1000;
      final seededSnapshot = AdminServerMonitorBackupSnapshot(
        id: 'test-backup-seed',
        status: 'ready',
        source: 'automatic',
        requestedBy: 'Backup Doctor',
        createdAtUnix: now - 1800,
        startedAtUnix: now - 1800,
        completedAtUnix: now - 1790,
        sizeBytes: 12 * 1024 * 1024,
        artifactName: 'mini_rs_erp_20260624_180448.dump',
        checksumSha256: List<String>.filled(64, 'a').join(),
        verified: true,
        error: '',
      );
      final snapshots = [seededSnapshot, ..._testModeBackupSnapshots];
      return AdminServerMonitorReport(
        server: AdminServerMonitorServer(
          bindAddr: '127.0.0.1:8081',
          startedAtUnix: DateTime.now().millisecondsSinceEpoch ~/ 1000,
          uptimeSeconds: 3600,
          status: 'running',
        ),
        database: const AdminServerMonitorDatabase(
          configured: true,
          reachable: true,
          status: 'online',
          pingMs: 12,
          error: '',
        ),
        backups: AdminServerMonitorBackups(
          directory: 'backups/mini_rs_erp_db',
          exists: true,
          fileCount: 1,
          latest: AdminServerMonitorBackupFile(
            name: 'mini_rs_erp_20260624_180448.dump',
            path: 'backups/mini_rs_erp_db/mini_rs_erp_20260624_180448.dump',
            sizeBytes: 12 * 1024 * 1024,
            modifiedAtUnix: DateTime.now().millisecondsSinceEpoch ~/ 1000,
            ageSeconds: 1800,
          ),
          files: [
            AdminServerMonitorBackupFile(
              name: 'mini_rs_erp_20260624_180448.dump',
              path: 'backups/mini_rs_erp_db/mini_rs_erp_20260624_180448.dump',
              sizeBytes: 12 * 1024 * 1024,
              modifiedAtUnix: DateTime.now().millisecondsSinceEpoch ~/ 1000,
              ageSeconds: 1800,
            ),
          ],
          snapshotCount: snapshots.where((item) => item.ready).length,
          latestSnapshot: snapshots.first,
          snapshots: snapshots,
          activeJob: null,
          healthy: true,
          error: '',
        ),
        runtime: const AdminServerMonitorRuntime(
          cpuPercent: 26,
          memoryPercent: 42,
          memoryUsedMb: 1720,
          memoryTotalMb: 4096,
          diskPath: '/home/wikki/mini_rs_erp_deploy/src',
          diskPercent: 38,
          diskUsedMb: 190000,
          diskTotalMb: 500000,
          diskAvailableMb: 310000,
          loadAverage: 0.7,
          sampleSeconds: 2,
        ),
      );
    }
    final response = await _sendAuthorized(
      () => _get(
        Uri.parse('${MobileApi.baseUrl}/v1/mobile/admin/system/monitor'),
        headers: _headers(requireToken()),
      ),
    );
    if (response.statusCode != 200) {
      throw const MobileApiException(
        code: 'admin_server_monitor',
        message: 'Server monitor yuklanmadi',
      );
    }
    return AdminServerMonitorReport.fromJson(
      jsonDecode(response.body) as Map<String, dynamic>,
    );
  }

  Future<AdminServerMonitorBackupSnapshot> adminStartBackup() async {
    if (await TestModeController.instance.isEnabled()) {
      final now = DateTime.now().millisecondsSinceEpoch ~/ 1000;
      final id = 'test-backup-$now-${_testModeBackupSnapshots.length}';
      final ready = AdminServerMonitorBackupSnapshot(
        id: id,
        status: 'ready',
        source: 'manual',
        requestedBy: AppSession.instance.profile?.displayName ?? 'Admin',
        createdAtUnix: now,
        startedAtUnix: now,
        completedAtUnix: now,
        sizeBytes: 1024,
        artifactName: 'mini_rs_erp_$now.dump',
        checksumSha256: List<String>.filled(64, 'b').join(),
        verified: true,
        error: '',
      );
      _testModeBackupSnapshots.insert(0, ready);
      return AdminServerMonitorBackupSnapshot(
        id: id,
        status: 'queued',
        source: 'manual',
        requestedBy: ready.requestedBy,
        createdAtUnix: now,
        startedAtUnix: 0,
        completedAtUnix: 0,
        sizeBytes: 0,
        artifactName: '',
        checksumSha256: '',
        verified: false,
        error: '',
      );
    }
    final response = await _sendAuthorized(
      () => _post(
        Uri.parse('${MobileApi.baseUrl}/v1/mobile/admin/system/backups'),
        headers: _headers(requireToken()),
      ),
    );
    Map<String, dynamic> payload = const {};
    if (response.body.trim().isNotEmpty) {
      try {
        payload = jsonDecode(response.body) as Map<String, dynamic>;
      } catch (_) {
        payload = const {};
      }
    }
    if (response.statusCode != 202) {
      throw MobileApiException(
        code: payload['error']?.toString() ?? 'backup_start_failed',
        message: _backupErrorMessage(payload['error']?.toString() ?? ''),
        statusCode: response.statusCode,
      );
    }
    return AdminServerMonitorBackupSnapshot.fromJson(payload);
  }

  Future<AdminServerMonitorBackupSnapshot> adminImportBackup({
    required String filename,
    required int contentLength,
    required Stream<List<int>> Function() openStream,
    void Function(int received, int total)? onProgress,
  }) async {
    final normalizedFilename = filename.trim();
    if (normalizedFilename.isEmpty ||
        contentLength <= 0 ||
        !normalizedFilename.toLowerCase().endsWith('.dump')) {
      throw const MobileApiException(
        code: 'backup_import_invalid',
        message: 'Backup fayli noto‘g‘ri',
      );
    }
    if (await TestModeController.instance.isEnabled()) {
      var received = 0;
      await for (final chunk in openStream()) {
        received += chunk.length;
        onProgress?.call(received, contentLength);
      }
      if (received != contentLength) {
        throw const MobileApiException(
          code: 'backup_import_invalid',
          message: 'Backup fayli to‘liq o‘qilmadi',
        );
      }
      final now = DateTime.now().millisecondsSinceEpoch ~/ 1000;
      final id = 'test-import-$now-${_testModeBackupSnapshots.length}';
      final ready = AdminServerMonitorBackupSnapshot(
        id: id,
        status: 'ready',
        source: 'imported',
        requestedBy: AppSession.instance.profile?.displayName ?? 'Admin',
        createdAtUnix: now,
        startedAtUnix: now,
        completedAtUnix: now,
        sizeBytes: contentLength,
        artifactName: normalizedFilename,
        checksumSha256: List<String>.filled(64, 'c').join(),
        verified: true,
        error: '',
      );
      _testModeBackupSnapshots.insert(0, ready);
      return ready;
    }

    final response = await _sendStreamedAuthorized(() async {
      final request = http.StreamedRequest(
        'POST',
        Uri.parse('${MobileApi.baseUrl}/v1/mobile/admin/system/backups/import'),
      )
        ..headers.addAll(_headers(requireToken()))
        ..headers['Content-Type'] = 'application/octet-stream'
        ..headers['X-Backup-Filename'] = normalizedFilename
        ..contentLength = contentLength;
      // Start the request before closing the sink. StreamedRequest.close() may
      // wait for a listener, so awaiting close before send() deadlocks forever.
      final responseFuture = request.send();
      var received = 0;
      try {
        await request.sink.addStream(
          openStream().map((chunk) {
            received += chunk.length;
            onProgress?.call(received, contentLength);
            if (received > contentLength) {
              throw const MobileApiException(
                code: 'backup_import_invalid',
                message: 'Backup fayli kutilgan hajmdan katta',
              );
            }
            return chunk;
          }),
        );
        if (received != contentLength) {
          throw const MobileApiException(
            code: 'backup_import_invalid',
            message: 'Backup fayli to‘liq o‘qilmadi',
          );
        }
        await request.sink.close();
      } catch (_) {
        try {
          await request.sink.close();
        } catch (_) {
          // Preserve the original upload error.
        }
        rethrow;
      }
      return responseFuture;
    });
    final body = await http.Response.fromStream(response);
    Map<String, dynamic> payload = const {};
    if (body.body.trim().isNotEmpty) {
      try {
        payload = jsonDecode(body.body) as Map<String, dynamic>;
      } catch (_) {
        payload = const {};
      }
    }
    if (body.statusCode != 202) {
      final code = payload['error']?.toString() ?? 'backup_import_failed';
      throw MobileApiException(
        code: code,
        message: _backupErrorMessage(code),
        statusCode: body.statusCode,
      );
    }
    return AdminServerMonitorBackupSnapshot.fromJson(payload);
  }

  Future<AdminBackupDownload> adminDownloadBackup(String backupId) async {
    final id = backupId.trim();
    if (id.isEmpty) {
      throw const MobileApiException(
        code: 'backup_not_found',
        message: 'Backup topilmadi',
      );
    }
    if (await TestModeController.instance.isEnabled()) {
      return AdminBackupDownload(
        filename: 'mini_rs_erp_test.dump',
        contentType: 'application/octet-stream',
        contentLength: 17,
        stream: Stream<List<int>>.value(utf8.encode('test-backup-bytes')),
      );
    }
    final uri = Uri.parse(
      '${MobileApi.baseUrl}/v1/mobile/admin/system/backups/${Uri.encodeComponent(id)}/download',
    );
    final response = await _sendMultipartAuthorized(() {
      final request = http.Request('GET', uri)
        ..headers.addAll(_headers(requireToken()));
      return request.send();
    });
    if (response.statusCode != 200) {
      final failed = await http.Response.fromStream(response);
      var code = 'backup_download_failed';
      if (failed.body.trim().isNotEmpty) {
        try {
          code = (jsonDecode(failed.body) as Map<String, dynamic>)['error']
                  ?.toString() ??
              code;
        } catch (_) {
          // Keep the stable fallback error code for non-JSON proxy errors.
        }
      }
      throw MobileApiException(
        code: code,
        message: _backupErrorMessage(code),
        statusCode: response.statusCode,
      );
    }
    return AdminBackupDownload(
      filename: _downloadFilename(
        response.headers['content-disposition'] ?? '',
      ),
      contentType:
          response.headers['content-type'] ?? 'application/octet-stream',
      contentLength: response.contentLength ?? 0,
      stream: response.stream,
    );
  }

  String _downloadFilename(String contentDisposition) {
    final match = RegExp(
      r'filename="?([^";]+)"?',
    ).firstMatch(contentDisposition);
    final filename = match?.group(1)?.trim() ?? '';
    return filename.isEmpty ? 'mini_rs_erp.dump' : filename;
  }

  String _backupErrorMessage(String code) {
    return switch (code) {
      'backup_already_running' => 'Backup olish allaqachon boshlangan',
      'backup_service_unavailable' => 'Backup xizmati hozir mavjud emas',
      'backup_not_ready' => 'Backup hali yuklab olishga tayyor emas',
      'backup_not_found' => 'Backup topilmadi',
      'backup_download_failed' => 'Backup yuklab olinmadi',
      'backup_import_invalid' =>
        'Backup fayli noto‘g‘ri yoki qo‘llab-quvvatlanmaydi',
      'backup_import_too_large' => 'Backup fayli juda katta',
      'backup_import_upload_failed' => 'Backup serverga yuklanmadi',
      'backup_import_upload_timeout' =>
        'Backup yuklash uzoq vaqt javobsiz qoldi',
      'backup_import_failed' => 'Backup import qilinmadi',
      'backup_service_failed' => 'Backup xizmati xatolik berdi',
      _ => 'Backup olish boshlanmadi',
    };
  }

  Uri adminServerMonitorLiveUri() {
    final Uri base = Uri.parse(MobileApi.baseUrl);
    final String scheme = base.scheme == 'https' ? 'wss' : 'ws';
    return base.replace(
      scheme: scheme,
      path: '/v1/mobile/admin/system/monitor/live',
      queryParameters: {'token': requireToken()},
    );
  }

  Stream<AdminServerMonitorLiveEvent> adminServerMonitorLiveEvents() async* {
    if (await TestModeController.instance.isEnabled()) {
      return;
    }
    await for (final event in withLiveStreamSilenceTimeout(
      connectSystemMonitorLive(adminServerMonitorLiveUri()),
    )) {
      final liveEvent = AdminServerMonitorLiveEvent.fromJson(event);
      if (liveEvent.report != null || liveEvent.latencyMs != null) {
        yield liveEvent;
      }
    }
  }
}
