// Generated by large_library_splitter.dart; keep changes in the source library.
part of '../mobile_api.dart';

extension MobileApiAdminProductionMapAstPart02 on MobileApi {
  Future<ProductionMapSaved> adminTransferProductionMapOrder({
    required String orderId,
    required String fromApparatus,
    required String toApparatus,
    required String reason,
    required String idempotencyKey,
  }) async {
    final normalizedOrderId = orderId.trim();
    final normalizedFrom = _requireCanonicalApparatusId(fromApparatus);
    final normalizedTo = _requireCanonicalApparatusId(toApparatus);
    final normalizedReason = reason.trim();
    final normalizedKey = idempotencyKey.trim();
    if (normalizedOrderId.isEmpty) {
      throw const MobileApiException(
        code: 'apparatus_transfer_order_not_paused',
        message: 'Avariya ko‘chirish ma’lumotlari to‘liq emas',
      );
    }
    if (normalizedReason.isEmpty) {
      throw const MobileApiException(
        code: 'apparatus_transfer_reason_required',
        message: 'Avariya sababini kiriting',
      );
    }
    if (normalizedKey.isEmpty || normalizedKey.length > 200) {
      throw const MobileApiException(
        code: 'apparatus_transfer_idempotency_required',
        message: 'Avariya ko‘chirish identifikatori mavjud emas',
      );
    }
    if (await TestModeController.instance.isEnabled()) {
      final sourceApparatus = _testModeRequiredApparatus(normalizedFrom);
      final targetApparatus = _testModeRequiredApparatus(normalizedTo);
      final existing = _testModeApparatusTransfers[normalizedKey];
      if (existing != null) {
        if (existing.orderId != normalizedOrderId ||
            existing.fromApparatus != normalizedFrom ||
            existing.toApparatus != normalizedTo) {
          throw const MobileApiException(
            code: 'apparatus_transfer_idempotency_conflict',
            message:
                'Avariya ko‘chirish identifikatori boshqa amalda ishlatilgan',
          );
        }
        return existing.saved;
      }
      if (normalizedFrom == normalizedTo) {
        throw const MobileApiException(
          code: 'move_not_allowed',
          message: 'Zakaz shu apparatda qolmoqda',
        );
      }
      final sourceKey = normalizedFrom;
      final targetKey = normalizedTo;
      if (sourceKey == targetKey) {
        throw const MobileApiException(
          code: 'move_not_allowed',
          message: 'Zakaz shu apparatda qolmoqda',
        );
      }
      final sourceStates = Map<String, String>.from(
        _testModeApparatusQueueStates[sourceKey] ?? const {},
      );
      final targetStates = Map<String, String>.from(
        _testModeApparatusQueueStates[targetKey] ?? const {},
      );
      if (apparatusQueueOrderStateFromRaw(sourceStates[normalizedOrderId]) !=
          ApparatusQueueOrderState.paused) {
        throw const MobileApiException(
          code: 'apparatus_transfer_order_not_paused',
          message: 'Ko‘chirishdan oldin orderni pause qiling',
        );
      }
      if (targetStates.containsKey(normalizedOrderId)) {
        throw const MobileApiException(
          code: 'apparatus_transfer_target_conflict',
          message: 'Order tanlangan apparatda allaqachon mavjud',
        );
      }
      final index = _testModeProductionMaps.indexWhere(
        (item) => item.map.id.trim() == normalizedOrderId,
      );
      if (index < 0) {
        throw const MobileApiException(
          code: 'map_not_found',
          message: 'Zakaz topilmadi',
        );
      }
      final current = _testModeProductionMaps[index];
      if (!productionMapCanMoveOrderToApparatus(
        nodes: current.map.nodes,
        fromApparatus: sourceApparatus,
        toApparatus: targetApparatus,
        rollCount: current.map.rollCount,
        widthMm: current.map.widthMm,
      )) {
        throw const MobileApiException(
          code: 'move_not_allowed',
          message: 'Zakaz bu aparatga tushmaydi',
        );
      }
      final nodes = productionMapReassignAlternativeApparatusAssignment(
            nodes: current.map.nodes,
            fromApparatus: sourceApparatus,
            toApparatus: targetApparatus,
          ) ??
          productionMapReassignApparatusNodes(
            nodes: current.map.nodes,
            fromApparatus: sourceApparatus,
            toApparatus: targetApparatus,
          );
      if (nodes == null) {
        throw const MobileApiException(
          code: 'move_not_allowed',
          message: 'Zakaz bu aparatga tushmaydi',
        );
      }
      final saved = ProductionMapSaved(
        map: current.map.copyWith(nodes: nodes),
        program: current.program,
      );
      final sourceSequence = List<String>.from(
        _testModeApparatusSequences[sourceKey] ?? const [],
      )..removeWhere((id) => id.trim() == normalizedOrderId);
      final targetSequence =
          List<String>.from(_testModeApparatusSequences[targetKey] ?? const [])
            ..removeWhere((id) => id.trim() == normalizedOrderId)
            ..add(normalizedOrderId);
      sourceStates.remove(normalizedOrderId);
      targetStates[normalizedOrderId] = 'paused';
      _testModeProductionMaps[index] = saved;
      _testModeApparatusSequences[sourceKey] = sourceSequence;
      _testModeApparatusSequences[targetKey] = targetSequence;
      _testModeApparatusQueueStates[sourceKey] = sourceStates;
      _testModeApparatusQueueStates[targetKey] = targetStates;
      _testModeMoveScheduleReservations(
        orderId: normalizedOrderId,
        fromApparatusId: sourceKey,
        toApparatusId: targetKey,
      );
      _testModeApparatusTransfers[normalizedKey] =
          _TestModeApparatusTransferReceipt(
        orderId: normalizedOrderId,
        fromApparatus: normalizedFrom,
        toApparatus: normalizedTo,
        saved: saved,
      );
      return saved;
    }
    final response = await _sendAuthorized(
      () => _post(
        Uri.parse(
          '${MobileApi.baseUrl}/v1/mobile/admin/production-maps/apparatus-transfer',
        ),
        headers: _headers(requireToken())
          ..['Content-Type'] = 'application/json',
        body: jsonEncode({
          'order_id': normalizedOrderId,
          'from_apparatus': normalizedFrom,
          'to_apparatus': normalizedTo,
          'reason': normalizedReason,
          'idempotency_key': normalizedKey,
        }),
      ),
    );
    if (response.statusCode != 200) {
      throw _adminProductionMapException(response, 'apparatus_transfer');
    }
    final payload = jsonDecode(response.body) as Map<String, dynamic>;
    final rawSaved = payload['saved'];
    if (rawSaved is! Map) {
      throw const MobileApiException(
        code: 'apparatus_transfer_invalid_response',
        message: 'Avariya ko‘chirish javobi noto‘g‘ri',
      );
    }
    return ProductionMapSaved.fromJson(rawSaved.cast<String, dynamic>());
  }

  Future<ProductionMapSaved> adminMoveProductionMapOrder({
    required String mapId,
    required String fromApparatus,
    required String toApparatus,
  }) async {
    final normalizedFrom = _requireCanonicalApparatusId(fromApparatus);
    final normalizedTo = _requireCanonicalApparatusId(toApparatus);
    if (await TestModeController.instance.isEnabled()) {
      final sourceApparatus = _testModeRequiredApparatus(normalizedFrom);
      final targetApparatus = _testModeRequiredApparatus(normalizedTo);
      final index = _testModeProductionMaps.indexWhere(
        (item) => item.map.id.trim() == mapId.trim(),
      );
      if (index < 0) {
        throw const MobileApiException(
          code: 'map_not_found',
          message: 'Zakaz topilmadi',
        );
      }
      final current = _testModeProductionMaps[index];
      _testModeEnsurePendingApparatusMove(
        orderId: current.map.id,
        fromApparatus: normalizedFrom,
      );
      if (!productionMapCanMoveOrderToApparatus(
        nodes: current.map.nodes,
        fromApparatus: sourceApparatus,
        toApparatus: targetApparatus,
        rollCount: current.map.rollCount,
        widthMm: current.map.widthMm,
      )) {
        throw const MobileApiException(
          code: 'move_not_allowed',
          message: 'Zakaz bu aparatga tushmaydi',
        );
      }
      final nodes = productionMapReassignAlternativeApparatusAssignment(
            nodes: current.map.nodes,
            fromApparatus: sourceApparatus,
            toApparatus: targetApparatus,
          ) ??
          productionMapReassignApparatusNodes(
            nodes: current.map.nodes,
            fromApparatus: sourceApparatus,
            toApparatus: targetApparatus,
          );
      if (nodes == null) {
        throw const MobileApiException(
          code: 'move_not_allowed',
          message: 'Zakaz bu aparatga tushmaydi',
        );
      }
      final saved = ProductionMapSaved(
        map: current.map.copyWith(nodes: nodes),
        program: current.program,
      );
      _testModeProductionMaps[index] = saved;
      return saved;
    }
    final response = await _sendAuthorized(
      () => _post(
        Uri.parse('${MobileApi.baseUrl}/v1/mobile/admin/production-maps/move'),
        headers: _headers(requireToken())
          ..['Content-Type'] = 'application/json',
        body: jsonEncode({
          'map_id': mapId,
          'from_apparatus': normalizedFrom,
          'to_apparatus': normalizedTo,
        }),
      ),
    );
    if (response.statusCode != 200) {
      throw _adminProductionMapException(response, 'production_map_move');
    }
    final payload = jsonDecode(response.body) as Map<String, dynamic>;
    return ProductionMapSaved.fromJson(
      (payload['saved'] as Map).cast<String, dynamic>(),
    );
  }

  Uri adminProductionMapLiveUri() {
    final Uri base = Uri.parse(MobileApi.baseUrl);
    final String scheme = base.scheme == 'https' ? 'wss' : 'ws';
    return base.replace(
      scheme: scheme,
      path: '/v1/mobile/admin/production-maps/live',
      queryParameters: {'token': requireToken()},
    );
  }

  Stream<AdminProductionMapLiveSnapshot> adminProductionMapLiveEvents() async* {
    if (await TestModeController.instance.isEnabled()) {
      return;
    }
    await for (final event in connectWarehouseLive(
      adminProductionMapLiveUri(),
    )) {
      if (event['ok'] == true) {
        yield AdminProductionMapLiveSnapshot.fromJson(event);
        continue;
      }
      final errorCode = event['error']?.toString().trim() ?? '';
      throw MobileApiException(
        code: errorCode.isEmpty ? 'production_map_live_failed' : errorCode,
        message: _adminProductionMapUnknownErrorMessage(
          code: errorCode,
          fallbackCode: 'production_map_live_failed',
          statusCode: 0,
        ),
      );
    }
  }

  Future<ProductionMapRunResult> adminRunProductionMap(
    ProductionMapRunRequest input,
  ) async {
    final response = await _sendAuthorized(
      () => _post(
        Uri.parse('${MobileApi.baseUrl}/v1/mobile/admin/production-maps/run'),
        headers: _headers(requireToken())
          ..['Content-Type'] = 'application/json',
        body: jsonEncode(input.toJson()),
      ),
    );
    if (response.statusCode != 200) {
      throw _adminProductionMapException(response, 'production_map_run');
    }
    return ProductionMapRunResult.fromJson(
      jsonDecode(response.body) as Map<String, dynamic>,
    );
  }
}

extension MobileApiAdminProductionMapOrderImage on MobileApi {
  /// Downloads the calculate-page photo linked to [orderId].
  ///
  /// Returns `null` when the order has no photo (fast server-side 404) so
  /// the detail sheet simply hides the image instead of failing.
  Future<List<int>?> adminProductionMapOrderImage(String orderId) async {
    final normalizedOrderId = orderId.trim();
    if (normalizedOrderId.isEmpty) return null;
    if (await TestModeController.instance.isEnabled()) return null;
    final response = await _sendAuthorized(
      () => _get(
        Uri.parse(
          '${MobileApi.baseUrl}/v1/mobile/admin/production-maps/order-image/view?order_id=${Uri.encodeQueryComponent(normalizedOrderId)}',
        ),
        headers: _headers(requireToken()),
      ),
    );
    if (response.statusCode == 404) return null;
    if (response.statusCode != 200 || response.bodyBytes.isEmpty) {
      throw _adminProductionMapException(
        response,
        'production_map_order_image',
      );
    }
    return response.bodyBytes;
  }
}
