// Generated by large_library_splitter.dart; keep changes in the source library.
part of '../mobile_api.dart';

class ProductionMapSaveWithOrderResult {
  const ProductionMapSaveWithOrderResult({
    required this.saved,
    required this.template,
  });

  final ProductionMapSaved saved;
  final CalculateOrderTemplate? template;
}

void _validateProductionMapQueueContract({
  required Map<String, List<String>> sequences,
  required Map<String, List<String>> visibleOrderIds,
  required Map<String, Map<String, String>> queueStates,
  required Map<String, Map<String, String>> stageStates,
  required Map<String, AdminApparatusQueuePolicy> queuePolicies,
  required Map<String, Map<String, AdminApparatusQueueOrderActionControl>>
      queueActionControls,
  required Map<String, List<AdminFrozenQueueOrder>> frozenOrdersByApparatus,
}) {
  for (final entry in [...sequences.entries, ...visibleOrderIds.entries]) {
    if (!isCanonicalApparatusId(entry.key.trim()) ||
        entry.value.any((orderId) => orderId.trim().isEmpty)) {
      throw _productionMapQueueContractException(
        'queue order map contains an invalid apparatus or order',
      );
    }
  }
  for (final entry in queuePolicies.entries) {
    if (!isCanonicalApparatusId(entry.key.trim()) ||
        entry.value.apparatusId.trim() != entry.key.trim()) {
      throw _productionMapQueueContractException(
        'queue_policies contains an invalid apparatus',
      );
    }
  }
  for (final entry in frozenOrdersByApparatus.entries) {
    if (!isCanonicalApparatusId(entry.key.trim()) ||
        entry.value.any(
          (order) =>
              order.apparatus.trim() != entry.key.trim() ||
              order.orderId.trim().isEmpty,
        )) {
      throw _productionMapQueueContractException(
        'frozen_orders_by_apparatus contains an invalid order',
      );
    }
  }
  for (final apparatusEntry in queueStates.entries) {
    if (!isCanonicalApparatusId(apparatusEntry.key.trim())) {
      throw _productionMapQueueContractException(
        'queue_states contains an invalid apparatus key',
      );
    }
    for (final stateEntry in apparatusEntry.value.entries) {
      final state = stateEntry.value.trim().toLowerCase();
      if (stateEntry.key.trim().isEmpty ||
          !_knownApparatusQueueStates.contains(state)) {
        throw _productionMapQueueContractException(
          'queue_states contains an unknown order state',
        );
      }
    }
  }
  for (final orderEntry in stageStates.entries) {
    if (orderEntry.key.trim().isEmpty) {
      throw _productionMapQueueContractException(
        'stage_states contains an invalid order key',
      );
    }
    for (final stageEntry in orderEntry.value.entries) {
      final state = stageEntry.value.trim().toLowerCase();
      if (stageEntry.key.trim().isEmpty ||
          !_knownApparatusQueueStates.contains(state)) {
        throw _productionMapQueueContractException(
          'stage_states contains an invalid stage state',
        );
      }
    }
  }
  for (final apparatusEntry in queueActionControls.entries) {
    if (!isCanonicalApparatusId(apparatusEntry.key.trim())) {
      throw _productionMapQueueContractException(
        'queue_action_controls contains an invalid apparatus key',
      );
    }
    for (final orderEntry in apparatusEntry.value.entries) {
      final control = orderEntry.value;
      if (orderEntry.key.trim().isEmpty || !control.contractValid) {
        throw _productionMapQueueContractException(
          'queue_action_controls contains an invalid order control',
        );
      }
      final queueState = queueStates[apparatusEntry.key]?[orderEntry.key];
      if (queueState != null &&
          queueState.trim().isNotEmpty &&
          queueState.trim().toLowerCase() !=
              control.state.trim().toLowerCase()) {
        throw _productionMapQueueContractException(
          'queue state and action control state disagree',
        );
      }
    }
  }
}

class AdminProductionMapLiveSnapshot {
  const AdminProductionMapLiveSnapshot({
    required this.maps,
    required this.sequences,
    required this.visibleOrderIds,
    required this.queueStates,
    required this.queuePolicies,
    this.queueActionControls = const {},
    this.stageStates = const {},
    required this.completedOrders,
    required this.completionRequests,
    required this.completionRequestDecisions,
    required this.orderControls,
    this.orderCustomers = const {},
    this.orderStatuses = const {},
    this.frozenOrdersByApparatus = const {},
    this.revision,
  });

  final List<ProductionMapSaved> maps;
  final Map<String, List<String>> sequences;
  final Map<String, List<String>> visibleOrderIds;
  final Map<String, Map<String, String>> queueStates;
  final Map<String, Map<String, String>> stageStates;
  final Map<String, AdminApparatusQueuePolicy> queuePolicies;
  final Map<String, Map<String, AdminApparatusQueueOrderActionControl>>
      queueActionControls;
  final List<AdminCompletedQueueOrder> completedOrders;
  final List<AdminCompletionRequestNotification> completionRequests;
  final List<AdminCompletionRequestDecisionNotification>
      completionRequestDecisions;
  final Map<String, AdminOrderControlState> orderControls;
  final Map<String, String> orderCustomers;
  final Map<String, AdminProductionOrderStatusDetail> orderStatuses;
  final Map<String, List<AdminFrozenQueueOrder>> frozenOrdersByApparatus;

  /// Monotonic snapshot revision from the backend `rev` field.
  /// Null when an old backend does not send it (fail-safe legacy path).
  final int? revision;

  factory AdminProductionMapLiveSnapshot.fromJson(Map<String, dynamic> json) {
    final visibleOrderIds = _parseRequiredProductionMapVisibleOrderIds(json);
    _requireProductionMapSnapshotShape(json, includesMaps: true);
    final mapsRaw = json['maps'];
    final completedRaw = json['completed_orders'];
    final completionRequestsRaw = json['completion_requests'];
    final completionRequestDecisionsRaw = json['completion_request_decisions'];
    final orderControls = _parseAdminOrderControls(json['order_controls']);
    final snapshot = AdminProductionMapLiveSnapshot(
      maps: parseProductionMapSnapshotMaps(mapsRaw),
      sequences: MobileApi.instance.parseApparatusSequenceMap(
        json['sequences'],
      ),
      visibleOrderIds: visibleOrderIds,
      queueStates: MobileApi.instance.parseApparatusQueueStateMap(
        json['queue_states'],
      ),
      stageStates: _parseProductionMapStageStates(json['stage_states']),
      queuePolicies: MobileApi.instance.parseApparatusQueuePolicyMap(
        json['queue_policies'],
      ),
      queueActionControls: _parseAdminQueueActionControls(
        json['queue_action_controls'],
      ),
      completedOrders: [
        if (completedRaw is List)
          for (final item in completedRaw)
            AdminCompletedQueueOrder.fromJson(
              (item as Map).cast<String, dynamic>(),
            ),
      ],
      completionRequests: [
        if (completionRequestsRaw is List)
          for (final item in completionRequestsRaw)
            AdminCompletionRequestNotification.fromJson(
              (item as Map).cast<String, dynamic>(),
            ),
      ],
      completionRequestDecisions: [
        if (completionRequestDecisionsRaw is List)
          for (final item in completionRequestDecisionsRaw)
            AdminCompletionRequestDecisionNotification.fromJson(
              (item as Map).cast<String, dynamic>(),
            ),
      ],
      orderControls: orderControls,
      orderCustomers: _stringMapOfStrings(json['order_customers']),
      orderStatuses: _parseAdminOrderStatuses(json['order_statuses']),
      frozenOrdersByApparatus: _parseAdminFrozenOrdersByApparatus(
        json['frozen_orders_by_apparatus'],
      ),
      revision: parseProductionMapSnapshotRevisionFromJson(json),
    );
    snapshot.validateContract();
    return snapshot;
  }

  void validateContract() {
    _validateProductionMapQueueContract(
      sequences: sequences,
      visibleOrderIds: visibleOrderIds,
      queueStates: queueStates,
      stageStates: stageStates,
      queuePolicies: queuePolicies,
      queueActionControls: queueActionControls,
      frozenOrdersByApparatus: frozenOrdersByApparatus,
    );
  }
}
