// Generated by large_library_splitter.dart; keep changes in the source library.
part of '../mobile_api.dart';

class _TestModeApparatusTransferReceipt {
  const _TestModeApparatusTransferReceipt({
    required this.orderId,
    required this.fromApparatus,
    required this.toApparatus,
    required this.saved,
  });

  final String orderId;
  final String fromApparatus;
  final String toApparatus;
  final ProductionMapSaved saved;
}

void setMobileApiTestModeForceProductionMapMenuLoadFailure(bool value) {
  _testModeForceProductionMapMenuLoadFailure = value;
}

void setMobileApiTestModeForceProductionMapQueueSnapshotLoadFailure(
    bool value) {
  _testModeForceProductionMapQueueSnapshotLoadFailure = value;
}

void setMobileApiTestModeForceCompletedProductionMapOrdersLoadFailure(
    bool value) {
  _testModeForceCompletedProductionMapOrdersLoadFailure = value;
}

void setMobileApiTestModeQueueActionControlFixture({
  required String apparatus,
  required String orderId,
  required AdminApparatusQueueOrderActionControl control,
}) {
  final normalizedApparatus = _requireCanonicalApparatusId(apparatus);
  final normalizedOrderId = orderId.trim();
  if (normalizedOrderId.isEmpty) return;
  _testModeQueueActionControlFixtures.putIfAbsent(
    normalizedApparatus,
    () => {},
  )[normalizedOrderId] = control;
}

void setMobileApiTestModeProductionMapStageStates({
  required String orderId,
  required Map<String, String> states,
}) {
  final normalizedOrderId = orderId.trim();
  if (normalizedOrderId.isEmpty) return;
  _testModeProductionMapStageStates[normalizedOrderId] = {
    for (final entry in states.entries)
      if (entry.key.trim().isNotEmpty) entry.key.trim(): entry.value.trim(),
  };
}

String _requireCanonicalApparatusId(
  String apparatusId, {
  bool allowEmpty = false,
}) {
  final normalized = apparatusId.trim();
  if ((allowEmpty && normalized.isEmpty) ||
      isCanonicalApparatusId(normalized)) {
    return normalized;
  }
  throw const MobileApiException(
    code: 'apparatus_id_invalid',
    message: 'Canonical apparatus ID noto‘g‘ri',
  );
}

List<String> _requireCanonicalApparatusIdList(Object? raw) {
  if (raw == null) return const [];
  if (raw is! List) {
    throw const MobileApiException(
      code: 'apparatus_id_invalid',
      message: 'Canonical apparatus ID ro‘yxati noto‘g‘ri',
    );
  }
  final result = <String>[];
  for (final item in raw) {
    final apparatusId = _requireCanonicalApparatusId(item.toString());
    if (!result.contains(apparatusId)) result.add(apparatusId);
  }
  return List<String>.unmodifiable(result);
}

void _requireCanonicalProductionMapApparatusIds(
  ProductionMapDefinition map,
) {
  for (final node in map.nodes) {
    final apparatusId = node.apparatusId.trim();
    final assignedId = node.alternativeAssignedApparatusId.trim();
    if ((node.kind == 'apparatus' && !isCanonicalApparatusId(apparatusId)) ||
        (apparatusId.isNotEmpty && !isCanonicalApparatusId(apparatusId)) ||
        (assignedId.isNotEmpty && !isCanonicalApparatusId(assignedId))) {
      throw const MobileApiException(
        code: 'production_map_apparatus_id_invalid',
        message: 'Production map canonical apparatus ID talab qiladi',
      );
    }
  }
}

AdminApparatus _testModeRequiredApparatus(String apparatusId) {
  final normalizedId = _requireCanonicalApparatusId(apparatusId);
  for (final apparatus in _testModeApparatusCatalog()) {
    if (apparatus.id.trim() == normalizedId) {
      return apparatus;
    }
  }
  throw const MobileApiException(
    code: 'apparatus_not_found',
    message: 'Aparat topilmadi',
  );
}

String _testModeEffectiveNodeApparatusId(ProductionMapNode node) {
  final assigned = node.alternativeAssignedApparatusId.trim();
  return assigned.isEmpty ? node.apparatusId.trim() : assigned;
}

AdminApparatusCapacityProfile _testModeProfileForApparatus({
  required String apparatusId,
}) {
  final canonical = _testModeRequiredApparatus(apparatusId);
  final normalizedId = canonical.id.trim();
  for (final profile in _testModeApparatusCapacityProfiles.values) {
    if (profile.apparatusId.trim() == normalizedId) {
      return profile;
    }
  }
  final inferredCapabilities = canonical.capabilities;
  final inferredProfiles = canonical.capabilityProfiles;
  return AdminApparatusCapacityProfile(
    apparatusId: normalizedId,
    apparatus: canonical.name.trim(),
    capabilities: inferredCapabilities,
    capabilityLevels: inferredProfiles.isEmpty
        ? {for (final capability in inferredCapabilities) capability: 1}
        : {
            for (final profile in inferredProfiles)
              if (profile.isValidAt(_testModeUnixSeconds()))
                profile.code: profile.level,
          },
  );
}

class _TestModeScheduledCandidate {
  const _TestModeScheduledCandidate({
    required this.index,
    required this.candidate,
    required this.profile,
    required this.reservedDurationMinutes,
    required this.startsAtUnix,
    required this.endsAtUnix,
  });

  final int index;
  final AdminApparatusScheduleCandidate candidate;
  final AdminApparatusCapacityProfile profile;
  final int reservedDurationMinutes;
  final int startsAtUnix;
  final int endsAtUnix;
}

({int startsAtUnix, int endsAtUnix})? _testModeFindScheduleSlot({
  required AdminApparatusCapacityProfile profile,
  required String apparatusId,
  required int earliestStartUnix,
  required int? latestEndUnix,
  required int reservedDurationMinutes,
}) {
  var cursor = earliestStartUnix < 60 ? 60 : earliestStartUnix;
  cursor = ((cursor + 59) ~/ 60) * 60;
  final horizon = cursor + 366 * 24 * 60 * 60;
  while (cursor < horizon) {
    final end = cursor + reservedDurationMinutes * 60;
    if (latestEndUnix != null && end > latestEndUnix) {
      return null;
    }
    if (!_testModeFitsWorkingWindow(profile, cursor, end)) {
      cursor += 60;
      continue;
    }
    final downtime = _testModeApparatusDowntimes.values.any(
      (item) =>
          item.active &&
          item.apparatusId.trim() == apparatusId &&
          _testModeIntervalsOverlap(
            cursor,
            end,
            item.startsAtUnix,
            item.endsAtUnix,
          ),
    );
    if (downtime) {
      cursor += 60;
      continue;
    }
    final conflicts = _testModeApparatusScheduleReservations.values
        .where(
          (item) =>
              (item.status == 'planned' || item.status == 'active') &&
              item.apparatusId.trim() == apparatusId &&
              _testModeIntervalsOverlap(
                cursor,
                end,
                item.startsAtUnix,
                item.endsAtUnix,
              ),
        )
        .length;
    final activeQueueOrderIds = <String>{};
    final apparatusStates =
        _testModeApparatusQueueStates[apparatusId] ?? const <String, String>{};
    for (final state in apparatusStates.entries) {
      if (apparatusQueueOrderStateFromRaw(state.value) ==
          ApparatusQueueOrderState.inProgress) {
        activeQueueOrderIds.add(state.key.trim());
      }
    }
    final scheduledActiveOrderIds = _testModeApparatusScheduleReservations
        .values
        .where(
          (item) =>
              item.status == 'active' && item.apparatusId.trim() == apparatusId,
        )
        .map((item) => item.orderId.trim())
        .toSet();
    final unscheduledActiveRuns = activeQueueOrderIds
        .where((orderId) => !scheduledActiveOrderIds.contains(orderId))
        .length;
    if (profile.finiteCapacity &&
        conflicts + unscheduledActiveRuns >= profile.capacitySlots) {
      cursor += 60;
      continue;
    }
    return (startsAtUnix: cursor, endsAtUnix: end);
  }
  return null;
}

AdminApparatusScheduleReservation _testModeScheduleApparatusOrder({
  required String orderId,
  required String apparatusId,
  required String apparatus,
  required int earliestStartUnix,
  required int? latestEndUnix,
  required int durationMinutes,
  required int priority,
  required String source,
  required String reason,
  required String idempotencyKey,
  required List<AdminApparatusCapabilityRequirement> capabilityRequirements,
  required List<AdminApparatusScheduleCandidate> candidateApparatuses,
}) {
  final normalizedOrderId = orderId.trim();
  final sourceApparatus = _testModeRequiredApparatus(apparatusId);
  final normalizedId = sourceApparatus.id.trim();
  if (normalizedOrderId.isEmpty ||
      durationMinutes <= 0 ||
      earliestStartUnix <= 0 ||
      idempotencyKey.trim().isEmpty) {
    throw const MobileApiException(
      code: 'schedule_input_invalid',
      message: 'Jadval ma’lumotlari to‘liq emas',
    );
  }
  if (!_testModeProductionMaps.any(
    (saved) => saved.map.id.trim() == normalizedOrderId,
  )) {
    throw const MobileApiException(
      code: 'map_not_found',
      message: 'Zakaz topilmadi',
    );
  }
  for (final existing in _testModeApparatusScheduleReservations.values) {
    if (existing.idempotencyKey.trim() == idempotencyKey.trim()) {
      if (existing.orderId != normalizedOrderId ||
          existing.apparatusId != normalizedId) {
        throw const MobileApiException(
          code: 'schedule_idempotency_conflict',
          message: 'Bu idempotency kaliti boshqa jadvalga tegishli',
        );
      }
      return existing;
    }
  }
  final map = _testModeProductionMaps
      .firstWhere((saved) => saved.map.id.trim() == normalizedOrderId)
      .map;
  final candidates = <AdminApparatusScheduleCandidate>[];
  final seenCandidateKeys = <String>{};
  void addCandidate(String id) {
    final canonical = _testModeRequiredApparatus(id);
    final normalizedCandidateId = canonical.id.trim();
    if (!seenCandidateKeys.add(normalizedCandidateId)) return;
    candidates.add(
      AdminApparatusScheduleCandidate(
        apparatusId: normalizedCandidateId,
        apparatus: canonical.name.trim(),
      ),
    );
  }

  addCandidate(normalizedId);
  for (final candidate in candidateApparatuses) {
    addCandidate(candidate.apparatusId);
  }

  var routeCandidateCount = 0;
  var supportedCandidateCount = 0;
  var capabilityNotSupported = false;
  var capabilityLevelInsufficient = false;
  _TestModeScheduledCandidate? best;
  for (var index = 0; index < candidates.length; index++) {
    final candidate = candidates[index];
    final candidateApparatus =
        _testModeRequiredApparatus(candidate.apparatusId);
    if (!_testModeCandidateAllowedForOrder(
      map,
      sourceApparatus,
      candidateApparatus,
    )) {
      continue;
    }
    routeCandidateCount++;
    final profile = _testModeProfileForApparatus(
      apparatusId: candidate.apparatusId,
    );
    var supported = true;
    for (final requirement in capabilityRequirements) {
      final code = requirement.code.trim().toLowerCase();
      if (code.isEmpty) continue;
      final level = profile.capabilityLevels[code] ??
          (profile.capabilities.any((item) => item.toLowerCase() == code)
              ? 1
              : 0);
      if (level == 0) {
        capabilityNotSupported = true;
        supported = false;
        break;
      }
      if (level < requirement.minLevel) {
        capabilityLevelInsufficient = true;
        supported = false;
        break;
      }
    }
    if (!supported) continue;
    supportedCandidateCount++;
    final efficiency = profile.efficiencyPercent.clamp(1, 200);
    final runMinutes = (durationMinutes * 100 + efficiency - 1) ~/ efficiency;
    final reservedDuration =
        runMinutes + profile.setupMinutes + profile.cleanupMinutes;
    final slot = _testModeFindScheduleSlot(
      profile: profile,
      apparatusId: candidate.apparatusId,
      earliestStartUnix: earliestStartUnix,
      latestEndUnix: latestEndUnix,
      reservedDurationMinutes: reservedDuration,
    );
    if (slot == null) continue;
    final currentBest = best;
    final isBetter = currentBest == null ||
        slot.startsAtUnix < currentBest.startsAtUnix ||
        (slot.startsAtUnix == currentBest.startsAtUnix &&
            index < currentBest.index);
    if (isBetter) {
      best = _TestModeScheduledCandidate(
        index: index,
        candidate: candidate,
        profile: profile,
        reservedDurationMinutes: reservedDuration,
        startsAtUnix: slot.startsAtUnix,
        endsAtUnix: slot.endsAtUnix,
      );
    }
  }
  if (routeCandidateCount == 0) {
    throw const MobileApiException(
      code: 'move_not_allowed',
      message: 'Aparat bu order yo‘nalishiga mos emas',
    );
  }
  final selected = best;
  if (selected == null) {
    if (supportedCandidateCount == 0 && capabilityNotSupported) {
      throw const MobileApiException(
        code: 'capability_not_supported',
        message: 'Aparat bu capability’ni qo‘llamaydi',
      );
    }
    if (supportedCandidateCount == 0 && capabilityLevelInsufficient) {
      throw const MobileApiException(
        code: 'capability_level_insufficient',
        message: 'Aparat capability darajasi yetarli emas',
      );
    }
  } else {
    final reservation = AdminApparatusScheduleReservation(
      reservationId: 'apparatus-reservation:${idempotencyKey.trim()}',
      idempotencyKey: idempotencyKey.trim(),
      orderId: normalizedOrderId,
      apparatusId: selected.candidate.apparatusId,
      apparatus: selected.candidate.apparatus,
      startsAtUnix: selected.startsAtUnix,
      endsAtUnix: selected.endsAtUnix,
      requestedDurationMinutes: durationMinutes,
      reservedDurationMinutes: selected.reservedDurationMinutes,
      status: 'planned',
      priority: priority,
      source: source.trim(),
      reason: reason.trim(),
      capabilityRequirements: capabilityRequirements,
      createdAtUnix: _testModeUnixSeconds(),
    );
    _testModeApparatusScheduleReservations[reservation.reservationId] =
        reservation;
    return reservation;
  }
  throw const MobileApiException(
    code: 'capacity_no_working_window',
    message: 'Aparat uchun bo‘sh slot topilmadi',
  );
}
