// Generated by large_library_splitter.dart; keep changes in the source library.
part of '../mobile_api.dart';

extension MobileApiInventoryMovementsAstPart03 on MobileApi {
  Future<InventoryTransfer> inventoryTransferAction({
    required String transferId,
    required String action,
    required String idempotencyKey,
    String note = '',
  }) async {
    final normalizedAction = action.trim().toLowerCase();
    const allowed = {'approve', 'reject', 'dispatch', 'receive', 'cancel'};
    if (transferId.trim().isEmpty ||
        !allowed.contains(normalizedAction) ||
        idempotencyKey.trim().isEmpty) {
      throw const MobileApiException(
        code: 'inventory_transfer_action_invalid',
        message: 'Transfer amali noto‘g‘ri',
      );
    }
    if (await TestModeController.instance.isEnabled()) {
      final index = _testModeInventoryTransfers.indexWhere(
        (item) => item.id == transferId.trim(),
      );
      if (index < 0) {
        throw const MobileApiException(
          code: 'inventory_transfer_not_found',
          message: 'Transfer topilmadi',
          statusCode: 404,
        );
      }
      final current = _testModeInventoryTransfers[index];
      final now = DateTime.now().millisecondsSinceEpoch ~/ 1000;
      final actorName = AppSession.instance.profile?.displayName ?? '';
      final internalTransfer = _testModeActorManagesTransferInternally(
        current.sourceWarehouse,
        current.destinationWarehouse,
      );
      final updated = switch (normalizedAction) {
        'approve'
            when current.status == InventoryTransferStatus.requested &&
                internalTransfer =>
          current.copyWith(
            status: InventoryTransferStatus.received,
            approvedByName: actorName,
            dispatchedByName: actorName,
            receivedByName: actorName,
            approvedAtUnix: now,
            dispatchedAtUnix: now,
            receivedAtUnix: now,
          ),
        'approve' when current.status == InventoryTransferStatus.requested =>
          current.copyWith(
            status: InventoryTransferStatus.approved,
            approvedByName: actorName,
            approvedAtUnix: now,
          ),
        'reject' when current.status == InventoryTransferStatus.requested =>
          current.copyWith(
            status: InventoryTransferStatus.rejected,
            rejectedByName: actorName,
            rejectedAtUnix: now,
          ),
        'dispatch'
            when current.status == InventoryTransferStatus.approved &&
                internalTransfer =>
          current.copyWith(
            status: InventoryTransferStatus.received,
            dispatchedByName: actorName,
            receivedByName: actorName,
            dispatchedAtUnix: now,
            receivedAtUnix: now,
          ),
        'dispatch' when current.status == InventoryTransferStatus.approved =>
          current.copyWith(
            status: InventoryTransferStatus.inTransit,
            dispatchedByName: actorName,
            dispatchedAtUnix: now,
          ),
        'receive' when current.status == InventoryTransferStatus.inTransit =>
          current.copyWith(
            status: InventoryTransferStatus.received,
            receivedByName: actorName,
            receivedAtUnix: now,
          ),
        'cancel'
            when current.status == InventoryTransferStatus.requested ||
                current.status == InventoryTransferStatus.approved =>
          current.copyWith(
            status: InventoryTransferStatus.cancelled,
            cancelledByName: actorName,
            cancelledAtUnix: now,
          ),
        _ => throw const MobileApiException(
            code: 'inventory_transfer_transition_invalid',
            message: 'Transfer bu bosqichda o‘zgartirilmaydi',
            statusCode: 409,
          ),
      };
      _testModeInventoryTransfers[index] = updated;
      if (updated.status == InventoryTransferStatus.rejected ||
          updated.status == InventoryTransferStatus.cancelled) {
        _releaseTestModeTransferAssets(updated);
      } else if (updated.status == InventoryTransferStatus.inTransit) {
        _markTestModeTransferAssetsInTransit(updated);
      } else if (updated.status == InventoryTransferStatus.received) {
        _receiveTestModeTransferAssets(updated);
      }
      return updated;
    }
    final response = await _sendAuthorized(
      () => _post(
        Uri.parse(
          '${MobileApi.baseUrl}/v1/mobile/admin/inventory/transfers/'
          '${Uri.encodeComponent(transferId.trim())}/'
          '${Uri.encodeComponent(normalizedAction)}',
        ),
        headers: _headers(requireToken())
          ..['Content-Type'] = 'application/json',
        body: jsonEncode({
          'idempotency_key': idempotencyKey.trim(),
          if (note.trim().isNotEmpty) 'note': note.trim(),
        }),
      ),
    );
    return _decodeInventoryMutation<InventoryTransfer>(
      response,
      InventoryTransfer.fromJson,
      fallbackCode: 'inventory_transfer_action_failed',
      fallbackMessage: 'Transfer yangilanmadi',
    );
  }
}
