// Generated by large_library_splitter.dart; keep changes in the source library.
part of 'qolip_home_screen.dart';

class _QolipGridTable extends StatelessWidget {
  const _QolipGridTable({
    required this.letters,
    required this.rowCount,
    required this.byCell,
    required this.searchQuery,
    required this.onCellTap,
    required this.onCellLongPress,
  });

  final List<String> letters;
  final int rowCount;
  final Map<String, List<QolipLocationEntry>> byCell;
  final String searchQuery;
  final void Function(String cellLabel, List<QolipLocationEntry> items)
      onCellTap;
  final void Function(String cellLabel) onCellLongPress;

  @override
  Widget build(BuildContext context) {
    final scheme = Theme.of(context).colorScheme;
    return Material(
      color: scheme.surface,
      elevation: 2,
      shadowColor: scheme.shadow.withValues(alpha: 0.14),
      surfaceTintColor: Colors.transparent,
      borderRadius: BorderRadius.circular(18),
      clipBehavior: Clip.antiAlias,
      child: Padding(
        padding: const EdgeInsets.all(8),
        child: Column(
          children: [
            Row(
              children: [
                const SizedBox(width: 42, height: 36),
                for (final letter in letters)
                  Padding(
                    padding: const EdgeInsets.symmetric(horizontal: 2),
                    child: _GridHeaderCell(label: letter, isColumn: true),
                  ),
              ],
            ),
            const SizedBox(height: 4),
            for (var rowNumber = 1; rowNumber <= rowCount; rowNumber++)
              Padding(
                padding: const EdgeInsets.only(bottom: 4),
                child: Row(
                  children: [
                    _GridHeaderCell(label: '$rowNumber', isColumn: false),
                    for (final letter in letters)
                      Padding(
                        padding: const EdgeInsets.symmetric(horizontal: 2),
                        child: _GridDataCell(
                          cellLabel: '$letter$rowNumber',
                          items: byCell['$letter$rowNumber'] ?? const [],
                          searchQuery: searchQuery,
                          onTap: onCellTap,
                          onLongPress: () =>
                              onCellLongPress('$letter$rowNumber'),
                        ),
                      ),
                  ],
                ),
              ),
          ],
        ),
      ),
    );
  }
}

enum _QolipStatChipTone { normal, warning }

class _QolipStatChip extends StatelessWidget {
  const _QolipStatChip({
    required this.icon,
    required this.label,
    this.tone = _QolipStatChipTone.normal,
  });

  final IconData icon;
  final String label;
  final _QolipStatChipTone tone;

  @override
  Widget build(BuildContext context) {
    final scheme = Theme.of(context).colorScheme;
    final background = tone == _QolipStatChipTone.warning
        ? scheme.errorContainer.withValues(alpha: 0.55)
        : scheme.primaryContainer.withValues(alpha: 0.45);
    final foreground = tone == _QolipStatChipTone.warning
        ? scheme.onErrorContainer
        : scheme.onPrimaryContainer;
    return DecoratedBox(
      decoration: BoxDecoration(
        color: background,
        borderRadius: BorderRadius.circular(999),
      ),
      child: Padding(
        padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 6),
        child: Row(
          mainAxisSize: MainAxisSize.min,
          children: [
            Icon(icon, size: 16, color: foreground),
            const SizedBox(width: 6),
            Text(
              label,
              style: Theme.of(context).textTheme.labelMedium?.copyWith(
                    color: foreground,
                    fontWeight: FontWeight.w700,
                  ),
            ),
          ],
        ),
      ),
    );
  }
}

class _GridHeaderCell extends StatelessWidget {
  const _GridHeaderCell({required this.label, required this.isColumn});

  final String label;
  final bool isColumn;

  @override
  Widget build(BuildContext context) {
    final scheme = Theme.of(context).colorScheme;
    return SizedBox(
      width: isColumn ? 76 : 42,
      height: 36,
      child: DecoratedBox(
        decoration: BoxDecoration(
          color: isColumn
              ? scheme.primaryContainer.withValues(alpha: 0.55)
              : scheme.surfaceContainerHighest,
          borderRadius: BorderRadius.circular(10),
        ),
        child: Center(
          child: Text(
            label,
            style: Theme.of(context).textTheme.labelLarge?.copyWith(
                  fontWeight: FontWeight.w800,
                  color: isColumn
                      ? scheme.onPrimaryContainer
                      : scheme.onSurfaceVariant,
                ),
          ),
        ),
      ),
    );
  }
}

class _GridDataCell extends StatelessWidget {
  const _GridDataCell({
    required this.cellLabel,
    required this.items,
    required this.searchQuery,
    required this.onTap,
    required this.onLongPress,
  });

  final String cellLabel;
  final List<QolipLocationEntry> items;
  final String searchQuery;
  final void Function(String cellLabel, List<QolipLocationEntry> items) onTap;
  final VoidCallback onLongPress;

  @override
  Widget build(BuildContext context) {
    final scheme = Theme.of(context).colorScheme;
    final l10n = context.l10n;
    final filled = items.isNotEmpty;
    final qty = items.fold<int>(0, (sum, item) => sum + item.quantity);
    final title = filled ? items.first.itemName : '';
    final matchCount = qolipContainerSearchMatchCount(items, searchQuery);
    final highlighted = matchCount > 0;
    final green = const Color(0xFF2E7D32);
    final background = highlighted
        ? Color.alphaBlend(
            green.withValues(alpha: 0.22),
            scheme.secondaryContainer,
          )
        : filled
            ? scheme.secondaryContainer
            : scheme.surfaceContainerHighest.withValues(alpha: 0.45);
    final foreground = highlighted ? green : scheme.onSecondaryContainer;

    return Material(
      key: ValueKey<String>('qolip-grid-cell-$cellLabel'),
      color: background,
      elevation: filled ? 1 : 0,
      shadowColor: scheme.shadow.withValues(alpha: 0.12),
      surfaceTintColor: Colors.transparent,
      borderRadius: BorderRadius.circular(12),
      clipBehavior: Clip.antiAlias,
      child: InkWell(
        onTap: () => onTap(cellLabel, items),
        onLongPress: onLongPress,
        child: SizedBox(
          width: 76,
          height: 64,
          child: Padding(
            padding: const EdgeInsets.all(8),
            child: filled
                ? Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Row(
                        children: [
                          Icon(Icons.layers_rounded,
                              size: 14, color: foreground),
                          const SizedBox(width: 4),
                          Expanded(
                            child: Text(
                              title,
                              maxLines: 1,
                              overflow: TextOverflow.ellipsis,
                              style: Theme.of(context)
                                  .textTheme
                                  .labelSmall
                                  ?.copyWith(
                                    color: foreground,
                                    fontWeight: FontWeight.w800,
                                  ),
                            ),
                          ),
                          if (highlighted) ...[
                            const SizedBox(width: 4),
                            _QolipSearchBadge(count: matchCount),
                          ],
                        ],
                      ),
                      const Spacer(),
                      Text(
                        l10n.qolipQuantityShort(qty),
                        style: Theme.of(context).textTheme.labelSmall?.copyWith(
                              color: foreground,
                              fontWeight: FontWeight.w700,
                            ),
                      ),
                    ],
                  )
                : Center(
                    child: Icon(
                      Icons.add_box_outlined,
                      size: 18,
                      color: scheme.outlineVariant.withValues(alpha: 0.75),
                    ),
                  ),
          ),
        ),
      ),
    );
  }
}

class _QolipSearchBadge extends StatelessWidget {
  const _QolipSearchBadge({required this.count});

  final int count;

  @override
  Widget build(BuildContext context) {
    return DecoratedBox(
      decoration: const BoxDecoration(
        color: Color(0xFF2E7D32),
        shape: BoxShape.circle,
      ),
      child: SizedBox.square(
        dimension: 18,
        child: Center(
          child: Text(
            '$count',
            style: Theme.of(context).textTheme.labelSmall?.copyWith(
                  color: Colors.white,
                  fontWeight: FontWeight.w900,
                  height: 1,
                ),
          ),
        ),
      ),
    );
  }
}

class _QolipCellActionTile extends StatelessWidget {
  const _QolipCellActionTile({
    required this.item,
    required this.selected,
    required this.onLongPress,
    this.onTap,
    required this.onTake,
    required this.onMove,
  });

  final QolipLocationEntry item;
  final bool selected;
  final VoidCallback onLongPress;
  final VoidCallback? onTap;
  final VoidCallback? onTake;
  final VoidCallback? onMove;

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final scheme = theme.colorScheme;
    final l10n = context.l10n;
    final title = item.itemName.trim().isEmpty ? item.qolipCode : item.itemName;
    return Material(
      color: selected
          ? scheme.secondaryContainer
          : scheme.surfaceContainerHighest.withValues(alpha: 0.64),
      borderRadius: BorderRadius.circular(12),
      clipBehavior: Clip.antiAlias,
      child: InkWell(
        onTap: onTap,
        onLongPress: onLongPress,
        child: Padding(
          padding: const EdgeInsets.fromLTRB(12, 10, 10, 10),
          child: Row(
            children: [
              Icon(Icons.layers_rounded, size: 20, color: scheme.primary),
              const SizedBox(width: 10),
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      title,
                      maxLines: 1,
                      overflow: TextOverflow.ellipsis,
                      style: theme.textTheme.titleSmall?.copyWith(
                        fontWeight: FontWeight.w700,
                      ),
                    ),
                    const SizedBox(height: 2),
                    Text(
                      '${item.qolipCode} • ${item.size} • ${l10n.qolipCount(item.quantity)}',
                      maxLines: 1,
                      overflow: TextOverflow.ellipsis,
                      style: theme.textTheme.bodySmall?.copyWith(
                        color: selected
                            ? scheme.onSecondaryContainer
                            : scheme.onSurfaceVariant,
                      ),
                    ),
                  ],
                ),
              ),
              if (selected) ...[
                const SizedBox(width: 6),
                Icon(
                  Icons.check_circle_rounded,
                  color: scheme.primary,
                ),
              ] else ...[
                const SizedBox(width: 6),
                FilledButton.tonal(
                  onPressed: onMove,
                  style: FilledButton.styleFrom(
                    visualDensity: VisualDensity.compact,
                    padding: const EdgeInsets.symmetric(horizontal: 10),
                    minimumSize: const Size(0, 34),
                  ),
                  child: Text(l10n.qolipText('home.move')),
                ),
                const SizedBox(width: 6),
                FilledButton.tonal(
                  onPressed: onTake,
                  style: FilledButton.styleFrom(
                    visualDensity: VisualDensity.compact,
                    padding: const EdgeInsets.symmetric(horizontal: 12),
                    minimumSize: const Size(0, 34),
                  ),
                  child: Text(l10n.qolipText('home.take')),
                ),
              ],
            ],
          ),
        ),
      ),
    );
  }
}
