// Generated by large_library_splitter.dart; keep changes in the source library.
part of 'qolip_home_screen.dart';

extension __QolipHomeScreenStateAstPart01 on _QolipHomeScreenState {
  TabController _ensureBlockTabController(int length) {
    final existing = _blockTabController;
    if (existing != null && existing.length == length) {
      return existing;
    }
    final previousIndex = existing?.index ?? 0;
    final initialIndex = previousIndex < 0
        ? 0
        : previousIndex >= length
            ? length - 1
            : previousIndex;
    existing?.dispose();
    final controller = TabController(
      length: length,
      initialIndex: initialIndex,
      vsync: this,
      animationDuration: const Duration(milliseconds: 220),
    );
    _blockTabController = controller;
    return controller;
  }

  void _handleLocationsChanged() {
    if (!mounted) {
      return;
    }
    setState(() {
      for (final key in _locationGenerations.keys.toList(growable: false)) {
        _locationGenerations[key] = _locationGenerations[key]! + 1;
      }
      _locations.clear();
    });
    _refreshSearchMatches();
  }

  Future<QolipBlocksResult> _loadBlocks() async {
    final result = await MobileApi.instance.qolipBlocksData();
    final blocks = result.blocks
        .where((block) => block.name.trim().isNotEmpty)
        .toList(growable: false);
    final orderedBlocks = await _applySavedBlockOrder(blocks);
    _orderedBlocks = orderedBlocks;
    _supportsCrossBlockMove = result.supportsCrossBlockMove;
    if (_searchQuery.isNotEmpty) {
      _refreshSearchMatches();
    }
    return QolipBlocksResult(
      warehouses: result.warehouses
          .where((warehouse) => warehouse.trim().isNotEmpty)
          .toList(growable: false),
      blocks: orderedBlocks,
      supportsCrossBlockMove: result.supportsCrossBlockMove,
    );
  }

  Future<void> _reloadBlocks() async {
    setState(() {
      for (final key in _locationGenerations.keys.toList(growable: false)) {
        _locationGenerations[key] = _locationGenerations[key]! + 1;
      }
      _locations.clear();
      _resolvedLocations.clear();
      _blockSearchMatchCounts = const <String, int>{};
      _orderedBlocks = const <QolipBlock>[];
      _blocksFuture = _loadBlocks();
    });
    await _blocksFuture;
  }

  Future<List<QolipBlock>> _applySavedBlockOrder(
    List<QolipBlock> blocks,
  ) async {
    final preferences = await SharedPreferences.getInstance();
    final savedKeys = preferences
            .getStringList(_QolipHomeScreenState._blockOrderPreferenceKey) ??
        const <String>[];
    final byKey = <String, QolipBlock>{
      for (final block in blocks) _blockKey(block): block,
    };
    final ordered = <QolipBlock>[];
    for (final key in savedKeys) {
      final block = byKey.remove(key);
      if (block != null) {
        ordered.add(block);
      }
    }
    ordered.addAll(byKey.values);
    return ordered;
  }

  Future<void> _saveBlockOrder(List<QolipBlock> blocks) async {
    final preferences = await SharedPreferences.getInstance();
    await preferences.setStringList(
      _QolipHomeScreenState._blockOrderPreferenceKey,
      blocks.map(_blockKey).toList(growable: false),
    );
  }

  String _blockKey(QolipBlock block) => block.name.trim().toLowerCase();

  void _reorderBlocks(
    TabController controller,
    int oldIndex,
    int newIndex,
  ) {
    if (oldIndex < 0 ||
        newIndex < 0 ||
        oldIndex >= _orderedBlocks.length ||
        newIndex >= _orderedBlocks.length) {
      return;
    }
    final insertionIndex = newIndex;
    if (oldIndex == insertionIndex || insertionIndex < 0) {
      return;
    }
    final currentIndex = controller.index;
    final nextIndex = reorderedTabIndex(
      currentIndex,
      oldIndex: oldIndex,
      newIndex: insertionIndex,
    );
    final reordered = [..._orderedBlocks];
    final block = reordered.removeAt(oldIndex);
    reordered.insert(insertionIndex, block);
    setState(() => _orderedBlocks = reordered);
    unawaited(_saveBlockOrder(reordered));
    WidgetsBinding.instance.addPostFrameCallback((_) {
      if (mounted && controller.index != nextIndex) {
        controller.index = nextIndex;
      }
    });
  }

  Future<List<QolipLocationEntry>> _locationsFor(String block) {
    final key = block.trim().toLowerCase();
    return _locations.putIfAbsent(
      key,
      () => _startLocationLoad(block, key),
    );
  }

  Future<List<QolipLocationEntry>> _startLocationLoad(
    String block,
    String key,
  ) {
    final generation = (_locationGenerations[key] ?? 0) + 1;
    _locationGenerations[key] = generation;
    return _loadLocations(block, key, generation);
  }

  Future<List<QolipLocationEntry>> _loadLocations(
    String block,
    String key,
    int generation,
  ) async {
    final locations = List<QolipLocationEntry>.unmodifiable(
      await MobileApi.instance.qolipLocations(block),
    );
    if (_locationGenerations[key] == generation) {
      _resolvedLocations[key] = locations;
    }
    return locations;
  }

  Future<List<QolipLocationEntry>> _refreshBlockAndWait(String block) {
    final key = block.trim().toLowerCase();
    final next = _startLocationLoad(block, key);
    setState(() {
      _locations[key] = next;
    });
    unawaited(_refreshSearchAfter(next));
    return next;
  }

  void _refreshBlock(String block) {
    unawaited(_refreshBlockAndWait(block));
  }

  Future<Map<String, List<QolipLocationEntry>>> _refreshMovedBlocks(
    Iterable<String> blocks,
  ) async {
    final namesByKey = <String, String>{};
    for (final block in blocks) {
      final name = block.trim();
      if (name.isNotEmpty) {
        namesByKey.putIfAbsent(name.toLowerCase(), () => name);
      }
    }
    final entries = await Future.wait(
      namesByKey.entries.map((entry) async {
        return MapEntry(entry.key, await _refreshBlockAndWait(entry.value));
      }),
    );
    return Map<String, List<QolipLocationEntry>>.fromEntries(entries);
  }

  void _showBlockTab(QolipBlock block) {
    final index = _orderedBlocks.indexWhere(
      (item) =>
          item.name.trim().toLowerCase() == block.name.trim().toLowerCase(),
    );
    final controller = _blockTabController;
    if (controller != null && index >= 0 && index < controller.length) {
      controller.animateTo(index);
    }
  }

  Future<void> _refreshSearchAfter(
    Future<List<QolipLocationEntry>> future,
  ) async {
    try {
      await future;
    } catch (_) {
      return;
    }
    _refreshSearchMatches();
  }

  void _openDrawerRoute(String route) {
    final current = ModalRoute.of(context)?.settings.name;
    if (current == route) {
      return;
    }
    Navigator.of(context).pushReplacementNamed(route);
  }

  void _onSearchChanged(String value) {
    final query = value.trim();
    _searchDebounce?.cancel();
    _searchGeneration++;
    setState(() {
      _searchQuery = query;
      _blockSearchMatchCounts = query.isEmpty
          ? const <String, int>{}
          : qolipBlockSearchMatchCounts(_resolvedLocations, query);
    });
    if (query.isNotEmpty) {
      final generation = _searchGeneration;
      _searchDebounce = Timer(
        const Duration(milliseconds: 160),
        () => unawaited(_loadBlockSearchMatches(query, generation)),
      );
    }
  }

  void _refreshSearchMatches() {
    final query = _searchQuery;
    if (!mounted || query.isEmpty) {
      return;
    }
    final generation = ++_searchGeneration;
    unawaited(_loadBlockSearchMatches(query, generation));
  }

  Future<void> _loadBlockSearchMatches(
    String query,
    int generation,
  ) async {
    final blocks = List<QolipBlock>.of(_orderedBlocks);
    final entries = await Future.wait(
      blocks.map((block) async {
        final key = _blockKey(block);
        try {
          return MapEntry<String, List<QolipLocationEntry>?>(
            key,
            await _locationsFor(block.name),
          );
        } catch (_) {
          return MapEntry<String, List<QolipLocationEntry>?>(key, null);
        }
      }),
    );
    if (!mounted || generation != _searchGeneration || query != _searchQuery) {
      return;
    }
    final locationsByBlock = <String, List<QolipLocationEntry>>{
      for (final entry in entries)
        if (entry.value != null) entry.key: entry.value!,
    };
    setState(() {
      _blockSearchMatchCounts = qolipBlockSearchMatchCounts(
        locationsByBlock,
        query,
      );
    });
  }

  Future<void> _printCellQr(
    QolipBlock block,
    String rowLetter,
    int columnNumber,
  ) async {
    final option = await showQolipPrinterPicker(context);
    if (!mounted || option == null) {
      return;
    }
    try {
      final printer = option.transport.isLocal
          ? option.transport.isBluetooth
              ? option.bluetoothPrinter!.printer
              : option.offlinePrinter!.printer
          : qolipPrinterChoiceForDriver(
              kind: option.printerKind,
              label: option.printerLabel,
            );
      final result = await MobileApi.instance.qolipPrintCellQr(
        block: block,
        rowLetter: rowLetter,
        columnNumber: columnNumber,
        driverUrl: option.driverUrl,
        printer: printer,
        printMode: option.transport.isLocal
            ? option.transport.isBluetooth
                ? option.bluetoothPrinter!.printMode
                : option.offlinePrinter!.printMode
            : printer == 'godex'
                ? 'label'
                : 'rfid',
        printTransport: option.transport,
      );
      if (option.transport.isLocal) {
        await PrintService.printRps(
          result.printJob,
          printerProfile: option.offlinePrinter,
          bluetoothPrinter: option.bluetoothPrinter,
          transport: option.transport,
        );
      }
      final cellQr = result.cellQr;
      if (!mounted) {
        return;
      }
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text(
            context.l10n.qolipText(
              'home.cell_qr_printed',
              values: {
                'cell': cellQr.locationLabel,
                'payload': cellQr.qrPayload,
              },
            ),
          ),
        ),
      );
    } catch (_) {
      if (!mounted) {
        return;
      }
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text(context.l10n.qolipText('home.qr_print_failed')),
        ),
      );
    }
  }

  Future<int?> _promptMoveQuantity(QolipLocationEntry item) async {
    if (item.quantity <= 1) {
      return 1;
    }
    final controller = TextEditingController(text: '${item.quantity}');
    final result = await showDialog<int>(
      context: context,
      builder: (context) {
        String? errorText;
        return StatefulBuilder(
          builder: (context, setDialogState) {
            return AlertDialog(
              title: Text(context.l10n.qolipText('home.mold_count')),
              content: TextField(
                controller: controller,
                autofocus: true,
                keyboardType: TextInputType.number,
                inputFormatters: [FilteringTextInputFormatter.digitsOnly],
                decoration: InputDecoration(
                  helperText: context.l10n.qolipText(
                    'home.max_count',
                    values: {'count': item.quantity},
                  ),
                  errorText: errorText,
                ),
              ),
              actions: [
                AppDialogActionRow(
                  cancelLabel: context.l10n.qolipText('action.cancel'),
                  confirmLabel: context.l10n.qolipText('action.continue'),
                  gap: 8,
                  vertical: true,
                  onCancel: () => Navigator.of(context).pop(),
                  onConfirm: () {
                    final qty = int.tryParse(controller.text.trim()) ?? 0;
                    if (qty <= 0) {
                      setDialogState(
                        () => errorText = context.l10n.qolipText(
                          'home.invalid_count',
                        ),
                      );
                      return;
                    }
                    if (qty > item.quantity) {
                      setDialogState(
                        () => errorText = context.l10n.qolipText(
                          'home.only_count',
                          values: {'count': item.quantity},
                        ),
                      );
                      return;
                    }
                    Navigator.of(context).pop(qty);
                  },
                ),
              ],
            );
          },
        );
      },
    );
    controller.dispose();
    return result;
  }
}
