// Generated by large_library_splitter.dart; keep changes in the source library.
part of 'qolip_location_transfer_screen.dart';

class QolipLocationTransferScreen extends StatefulWidget {
  const QolipLocationTransferScreen({super.key});

  @override
  State<QolipLocationTransferScreen> createState() =>
      _QolipLocationTransferScreenState();
}
