// Generated by large_library_splitter.dart; keep changes in the source library.
part of 'chat_detail_screen.dart';

class ChatDetailScreen extends StatefulWidget {
  const ChatDetailScreen({super.key, required this.conversation});

  final ChatConversation conversation;

  @override
  State<ChatDetailScreen> createState() => _ChatDetailScreenState();
}

enum _ChatTimelineItemKind {
  loadOlder,
  dateDivider,
  message,
  pendingMedia,
}

class _ChatTimelineItem {
  const _ChatTimelineItem.loadOlder()
      : kind = _ChatTimelineItemKind.loadOlder,
        date = null,
        message = null,
        pendingMedia = null,
        mine = false,
        compactTop = false,
        isLastInGroup = false;

  const _ChatTimelineItem.dateDivider(DateTime value)
      : kind = _ChatTimelineItemKind.dateDivider,
        date = value,
        message = null,
        pendingMedia = null,
        mine = false,
        compactTop = false,
        isLastInGroup = false;

  const _ChatTimelineItem.message(
    ChatMessage value, {
    required this.mine,
    required this.compactTop,
    required this.isLastInGroup,
  })  : kind = _ChatTimelineItemKind.message,
        date = null,
        message = value,
        pendingMedia = null;

  const _ChatTimelineItem.pendingMedia(ChatPendingMedia value)
      : kind = _ChatTimelineItemKind.pendingMedia,
        date = null,
        message = null,
        pendingMedia = value,
        mine = false,
        compactTop = false,
        isLastInGroup = false;

  final _ChatTimelineItemKind kind;
  final DateTime? date;
  final ChatMessage? message;
  final ChatPendingMedia? pendingMedia;
  final bool mine;
  final bool compactTop;
  final bool isLastInGroup;
}

class _MediaPickerSelection {
  const _MediaPickerSelection(this.kind, this.source);

  final ChatMediaKind kind;
  final ImageSource source;
}

class _ChatMediaPickerSheet extends StatelessWidget {
  const _ChatMediaPickerSheet();

  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Padding(
        padding: const EdgeInsets.fromLTRB(12, 0, 12, 12),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            _MediaPickerTile(
              icon: Icons.photo_library_outlined,
              label: 'Galereyadan rasm',
              onTap: () => _pop(
                context,
                ChatMediaKind.image,
                ImageSource.gallery,
              ),
            ),
            _MediaPickerTile(
              icon: Icons.camera_alt_outlined,
              label: 'Rasmga olish',
              onTap: () =>
                  _pop(context, ChatMediaKind.image, ImageSource.camera),
            ),
            _MediaPickerTile(
              icon: Icons.video_library_outlined,
              label: 'Galereyadan video',
              onTap: () => _pop(
                context,
                ChatMediaKind.video,
                ImageSource.gallery,
              ),
            ),
            _MediaPickerTile(
              icon: Icons.videocam_outlined,
              label: 'Video yozish',
              onTap: () =>
                  _pop(context, ChatMediaKind.video, ImageSource.camera),
            ),
          ],
        ),
      ),
    );
  }

  void _pop(
    BuildContext context,
    ChatMediaKind kind,
    ImageSource source,
  ) {
    Navigator.of(context).pop(_MediaPickerSelection(kind, source));
  }
}

class _MediaPickerTile extends StatelessWidget {
  const _MediaPickerTile({
    required this.icon,
    required this.label,
    required this.onTap,
  });

  final IconData icon;
  final String label;
  final VoidCallback onTap;

  @override
  Widget build(BuildContext context) {
    return ListTile(
      leading: Icon(icon),
      title: Text(label),
      onTap: onTap,
    );
  }
}

class _ConversationTitle extends StatelessWidget {
  const _ConversationTitle({
    required this.conversation,
    required this.connected,
  });

  final ChatConversation conversation;
  final bool connected;

  @override
  Widget build(BuildContext context) {
    final scheme = Theme.of(context).colorScheme;
    return Column(
      mainAxisSize: MainAxisSize.min,
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          conversation.displayTitle,
          maxLines: 1,
          overflow: TextOverflow.ellipsis,
          style: Theme.of(context).textTheme.titleMedium?.copyWith(
                fontWeight: FontWeight.w700,
              ),
        ),
        Text(
          connected ? 'Onlayn' : 'Ulanmoqda…',
          style: Theme.of(context).textTheme.labelMedium?.copyWith(
                color: scheme.onSurfaceVariant,
              ),
        ),
      ],
    );
  }
}

class _ChatParticipantProfileAction extends StatelessWidget {
  const _ChatParticipantProfileAction({
    required this.participant,
    required this.onTap,
  });

  final ChatPrincipal? participant;
  final VoidCallback onTap;

  @override
  Widget build(BuildContext context) {
    final name = participant?.displayName.trim().isNotEmpty == true
        ? participant!.displayName
        : 'Suhbat';
    return Semantics(
      button: true,
      label: '$name profili',
      child: AppShellIconAction(
        size: 44,
        iconWidget: ChatAvatar(
          name: name,
          avatarUrl: participant?.avatarUrl ?? '',
          radius: 17,
        ),
        onTap: participant == null ? () {} : onTap,
      ),
    );
  }
}
