// Generated by large_library_splitter.dart; keep changes in the source library.
part of 'admin_warehouses_screen.dart';

class _WarehouseDetailsTabState extends State<_WarehouseDetailsTab> {
  static const int _pageSize = 80;
  static const double _loadMoreExtent = 420;

  final ScrollController _itemsScrollController = ScrollController();
  late final TextEditingController _itemsSearchController;
  late final bool _ownsItemsSearchController;
  Timer? _itemsSearchDebounce;
  List<AdminWarehouseStockItem> _items = const <AdminWarehouseStockItem>[];
  List<QolipProduct> _qolipProducts = const <QolipProduct>[];
  String _itemsQuery = '';
  bool _initialItemsLoading = false;
  bool _loadingMoreItems = false;
  bool _hasMoreItems = false;
  Object? _itemsError;
  int _itemsRequestGeneration = 0;
  String? _editingStockBarcode;

  bool get _isQolipWarehouse =>
      widget.showQolipWarehouseProducts &&
      (_isQolipWarehouseName(widget.warehouse) ||
          _warehouseNameMatches(widget.qolipWarehouseNames, widget.warehouse));

  @override
  void initState() {
    super.initState();
    _ownsItemsSearchController = widget.searchController == null;
    _itemsSearchController = widget.searchController ?? TextEditingController();
    _itemsScrollController.addListener(_handleItemsScroll);
    unawaited(_loadFirstItemsPage());
  }

  @override
  void didUpdateWidget(covariant _WarehouseDetailsTab oldWidget) {
    super.didUpdateWidget(oldWidget);
    final oldIsQolipWarehouse = oldWidget.showQolipWarehouseProducts &&
        (_isQolipWarehouseName(oldWidget.warehouse) ||
            _warehouseNameMatches(
              oldWidget.qolipWarehouseNames,
              oldWidget.warehouse,
            ));
    final isQolipWarehouse = _isQolipWarehouse;
    if (oldWidget.warehouse != widget.warehouse ||
        oldIsQolipWarehouse != isQolipWarehouse) {
      _itemsSearchDebounce?.cancel();
      final queryToClear = _itemsSearchController.text;
      if (queryToClear.isNotEmpty) {
        WidgetsBinding.instance.addPostFrameCallback((_) {
          if (mounted && _itemsSearchController.text == queryToClear) {
            _itemsSearchController.clear();
          }
        });
      }
      _itemsQuery = '';
      unawaited(_loadFirstItemsPage());
    }
  }

  @override
  void dispose() {
    _itemsSearchDebounce?.cancel();
    _itemsScrollController.removeListener(_handleItemsScroll);
    _itemsScrollController.dispose();
    if (_ownsItemsSearchController) {
      _itemsSearchController.dispose();
    }
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final future = widget.detailFuture;
    final selectedWarehouse = widget.warehouse?.trim() ?? '';
    final filter = _WarehouseFilterBar(
      selectedWarehouse: selectedWarehouse,
      warehouses: widget.summaries,
      expanded: widget.filterExpanded,
      onToggle: widget.onFilterToggle,
      onChanged: widget.onWarehouseChanged,
    );
    Widget buildScaffold(
      List<Widget> children, {
      List<Widget> leading = const [],
      ScrollController? controller,
    }) {
      return ColoredBox(
        color: AppTheme.shellStart(context),
        child: ListView(
          controller: controller,
          padding: EdgeInsets.fromLTRB(4, 4, 4, widget.bottomPadding),
          children: [
            ...leading,
            filter,
            ...children,
          ],
        ),
      );
    }

    if (widget.summaries.isEmpty) {
      return buildScaffold([
        SizedBox(height: 24),
        Center(child: Text(context.l10n.adminText('warehouse.empty'))),
      ]);
    }
    if (widget.warehouse == null ||
        widget.warehouse!.trim().isEmpty ||
        future == null) {
      return buildScaffold([
        SizedBox(height: 24),
        Center(child: Text(context.l10n.adminText('warehouse.no_selection'))),
      ]);
    }
    return FutureBuilder<_WarehouseInventorySection?>(
      future: future,
      builder: (context, snapshot) {
        final current = snapshot.data ??
            const _WarehouseInventorySection(
              rawStock: <AdminRawMaterialStockEntry>[],
              reservations: <AdminRawMaterialAssignment>[],
              apparatus: <AdminApparatus>[],
            );
        final availableRawStock = _availableRawStock(current.rawStock);
        final reservedRawStock = _reservedRawStock(current.rawStock);
        _WarehouseSummarySection? selectedSummary;
        for (final summary in widget.summaries) {
          if (summary.warehouse.trim().toLowerCase() ==
              selectedWarehouse.toLowerCase()) {
            selectedSummary = summary;
            break;
          }
        }
        final isQolipWarehouse = _isQolipWarehouse;
        final qolipProductGroups = isQolipWarehouse
            ? _groupAdminQolipProducts(_qolipProducts)
            : const <_AdminQolipProductGroup>[];
        final availableCount = isQolipWarehouse
            ? qolipProductGroups.length
            : selectedSummary?.productCount ??
                (_items.length + availableRawStock.length);
        final reservedCount = _bandTabEntryCount(
          reservedRawStock,
          current.reservations,
        );
        final availableChildren = <Widget>[
          if (widget.searchController == null)
            SearchBar(
              controller: _itemsSearchController,
              hintText: context.l10n.adminText('warehouse.products_search'),
              constraints: const BoxConstraints(minHeight: 54),
              padding: const WidgetStatePropertyAll<EdgeInsetsGeometry>(
                EdgeInsets.symmetric(horizontal: 16),
              ),
              leading: Icon(
                Icons.search_rounded,
                color: Theme.of(context).colorScheme.onSurfaceVariant,
              ),
              elevation: const WidgetStatePropertyAll<double>(0),
              onChanged: _handleItemsSearchChanged,
            ),
          if (_initialItemsLoading)
            const Padding(
              padding: EdgeInsets.only(top: 28),
              child: Center(child: AppLoadingIndicator()),
            )
          else if (_itemsError != null && _items.isEmpty)
            Padding(
              padding: const EdgeInsets.only(top: 16),
              child: Center(
                child: OutlinedButton.icon(
                  onPressed: _loadFirstItemsPage,
                  icon: const Icon(Icons.refresh_rounded),
                  label: Text(context.l10n.adminText('action.retry')),
                ),
              ),
            )
          else if (isQolipWarehouse && qolipProductGroups.isNotEmpty)
            _AdminQolipProductListModule(groups: qolipProductGroups)
          else if (!isQolipWarehouse && _items.isNotEmpty)
            _WarehouseItemListModule(
              items: _items,
            )
          else if (isQolipWarehouse)
            Padding(
              padding: EdgeInsets.only(top: 16),
              child: Center(
                child: Text(
                  context.l10n.adminText('warehouse.no_mold_products'),
                ),
              ),
            )
          else if (availableRawStock.isEmpty)
            Padding(
              padding: EdgeInsets.only(top: 16),
              child: Center(
                child: Text(context.l10n.adminText('warehouse.no_products')),
              ),
            ),
          if (availableRawStock.isNotEmpty)
            _WarehouseRawStockListModule(
              stock: availableRawStock,
              canEdit: widget.allowRawStockEdit
                  ? (stock) => _canEditRawMaterialStock(
                        stock,
                        current.reservations,
                      )
                  : null,
              onEdit: widget.allowRawStockEdit
                  ? (stock) => unawaited(_editRawStock(stock))
                  : null,
              onQr: widget.allowRawStockEdit
                  ? (stock) => unawaited(_showRawStockQr(stock))
                  : null,
            ),
          if (_loadingMoreItems)
            const Padding(
              padding: EdgeInsets.all(14),
              child: AppLoadingIndicator(size: 48, glyphSize: 28),
            )
          else if (_itemsError != null && _items.isNotEmpty)
            Padding(
              padding: const EdgeInsets.all(12),
              child: OutlinedButton.icon(
                onPressed: _loadNextItemsPage,
                icon: const Icon(Icons.refresh_rounded),
                label: Text(context.l10n.adminText('action.load_more')),
              ),
            )
          else if (_hasMoreItems)
            Padding(
              padding: const EdgeInsets.all(12),
              child: Text(
                context.l10n.adminText('warehouse.load_more_hint'),
                textAlign: TextAlign.center,
                style: Theme.of(context).textTheme.bodySmall?.copyWith(
                      color: Theme.of(context).colorScheme.onSurfaceVariant,
                    ),
              ),
            ),
        ];
        final reservedChildren = <Widget>[
          if (current.reservations.isNotEmpty)
            _WarehouseReservationListModule(
              reservations: current.reservations,
              apparatus: current.apparatus,
            )
          else if (reservedRawStock.isNotEmpty)
            _WarehouseRawStockListModule(
              stock: reservedRawStock,
              onQr: widget.allowRawStockEdit
                  ? (stock) => unawaited(_showRawStockQr(stock))
                  : null,
            ),
        ];
        final hasReserved = reservedChildren.isNotEmpty;
        final stockTabs = <Tab>[
          Tab(
            height: 38,
            text: context.l10n.adminText(
              'warehouse.available',
              values: {'count': availableCount},
            ),
          ),
        ];
        final stockTabChildren = <List<Widget>>[availableChildren];
        if (hasReserved) {
          stockTabs.add(
            Tab(
              height: 38,
              text: context.l10n.adminText(
                'warehouse.reserved',
                values: {'count': reservedCount},
              ),
            ),
          );
          stockTabChildren.add(reservedChildren);
        }
        return DefaultTabController(
          key: ValueKey<String>(
            '${selectedWarehouse.toLowerCase()}:${stockTabs.length}',
          ),
          length: stockTabs.length,
          child: Builder(
            builder: (context) {
              final stockController = DefaultTabController.of(context);
              return AnimatedBuilder(
                animation: stockController,
                builder: (context, _) {
                  final selectedIndex =
                      stockController.index < stockTabChildren.length
                          ? stockController.index
                          : stockTabChildren.length - 1;
                  final visibleChildren = stockTabChildren[selectedIndex];
                  return buildScaffold([
                    const SizedBox(height: 8),
                    if (visibleChildren.isEmpty)
                      Padding(
                        padding: EdgeInsets.only(top: 16),
                        child: Center(
                          child: Text(
                            context.l10n.adminText('warehouse.no_products'),
                          ),
                        ),
                      )
                    else ...[
                      for (var index = 0;
                          index < visibleChildren.length;
                          index++) ...[
                        if (index > 0) const SizedBox(height: 16),
                        visibleChildren[index],
                      ],
                    ],
                  ],
                      leading: [
                        AdminSurfaceTabBar(
                          controller: stockController,
                          tabs: stockTabs,
                        ),
                      ],
                      controller:
                          selectedIndex == 0 ? _itemsScrollController : null);
                },
              );
            },
          ),
        );
      },
    );
  }
}
