// Generated by large_library_splitter.dart; keep changes in the source library.
part of 'admin_production_map_orders_screen.dart';

extension __ReadOnlyOrderDetailSheetStateAstPart01
    on _ReadOnlyOrderDetailSheetState {
  String _defaultQuickScanStatus() {
    final openingWipRequired =
        _queueActionControl?.interaction?.openingWipMode ==
            AdminQueuePreviousWipMode.scanRequired;
    final waitingCount = _availableOpeningWipBatches.length;
    if (openingWipRequired && waitingCount > 0) {
      return context.l10n.productionText(
        'worker.opening_wip.scanner_prompt',
        values: {'count': waitingCount},
      );
    }
    return context.l10n.productionText('worker.scanner.prompt');
  }

  /// Loads the calculate-page photo for the sheet header. Missing photos are
  /// normal (old orders): the API returns null on 404 and the header hides.
  Future<void> _loadOrderImage() async {
    final map = widget.order.map;
    if (map.id.trim().isEmpty || map.imageId.trim().isEmpty) return;
    setState(() => _orderImageLoading = true);
    try {
      final bytes =
          await MobileApi.instance.adminProductionMapOrderImage(map.id);
      if (!mounted) return;
      setState(() {
        _orderImageBytes = bytes;
        _orderImageLoading = false;
      });
    } catch (error) {
      if (!mounted) return;
      debugPrint('Order image load failed: $error');
      setState(() => _orderImageLoading = false);
    }
  }

  Future<void> _loadInteractionContractAndSections() async {    if (!_queueActionContractSynchronized) {
      try {
        final refreshed = await _loadCurrentQueueActionControl();
        if (!mounted) return;
        if (refreshed?.isConsistentWith(
              _orderControlState,
              queueState: _queueStates[widget.order.map.id.trim()],
            ) ==
            true) {
          setState(() => _queueActionControl = refreshed);
        } else {
          debugPrint(
            'Invalid production interaction contract for '
            '${widget.order.map.id.trim()} at '
            '${widget.apparatus?.name.trim() ?? ''}',
          );
          setState(() => _queueActionControl = null);
          _showSheetNotice(
            context.l10n.productionText('worker.error.sync'),
          );
        }
      } catch (error) {
        if (!mounted) return;
        debugPrint('Production interaction contract refresh failed: $error');
        setState(() => _queueActionControl = null);
        _showSheetNotice(
          context.l10n.productionText('worker.error.sync'),
        );
      }
    }
    if (!mounted) return;
    await Future.wait([
      _loadMaterialAssignments(),
      _loadInputProgressBatches(),
      _loadQolipRequirements(),
    ]);
  }

  Future<_MaterialAssignmentsSnapshot> _fetchMaterialAssignments({
    required String orderId,
    required String apparatus,
    required List<String> materialBarcodes,
  }) async {
    final isMaterialTaminotchi =
        AppSession.instance.profile?.role == UserRole.materialTaminotchi;
    late final List<AdminRawMaterialAssignment> assignments;
    var startAssignments = const <AdminRawMaterialAssignment>[];
    var intakeCandidates = const <AdminRawMaterialAssignment>[];
    AdminRawMaterialStartRequirements? requirements;
    if (apparatus.isEmpty || isMaterialTaminotchi) {
      assignments = await MobileApi.instance.adminRawMaterialAssignments(
        orderId: orderId,
        apparatus: isMaterialTaminotchi ? '' : apparatus,
      );
    } else {
      final interaction = _queueActionControl?.interaction;
      if (_queueActionContractSynchronized &&
          interaction?.startMaterialsMode ==
              AdminQueueStartMaterialsMode.scanRequired) {
        requirements =
            await MobileApi.instance.adminRawMaterialStartRequirements(
          orderId: orderId,
          apparatus: apparatus,
          materialBarcodes: materialBarcodes,
        );
        assignments = requirements.assignments
            .where(
              (assignment) => assignment.apparatus.trim() == apparatus,
            )
            .toList(growable: false);
        startAssignments = requirements.startAssignments
            .where(
              (assignment) => assignment.apparatus.trim() == apparatus,
            )
            .toList(growable: false);
      } else {
        assignments = await MobileApi.instance.adminRawMaterialAssignments(
          orderId: orderId,
          apparatus: apparatus,
        );
        if (_queueActionContractSynchronized &&
            interaction?.materialIntakeAllowed == true) {
          intakeCandidates =
              await MobileApi.instance.adminRawMaterialIntakeCandidates(
            orderId: orderId,
            apparatus: apparatus,
          );
        }
      }
    }
    return _MaterialAssignmentsSnapshot(
      assignments: assignments,
      startAssignments: startAssignments,
      intakeCandidateAssignments: intakeCandidates,
      requirements: requirements,
    );
  }

  void _applyMaterialAssignmentsSnapshot(
    _MaterialAssignmentsSnapshot snapshot,
  ) {
    final eligibleBarcodes = snapshot.requirements == null
        ? null
        : snapshot.startAssignments
            .map((assignment) => _materialBarcodeKey(assignment.barcode))
            .toSet();
    setState(() {
      _materialAssignments = snapshot.assignments;
      _startAssignments = snapshot.startAssignments;
      _intakeCandidateAssignments = snapshot.intakeCandidateAssignments;
      _materialStartRequirements = snapshot.requirements;
      if (eligibleBarcodes != null) {
        _scannedMaterialBarcodes.removeWhere(
          (barcode) => !eligibleBarcodes.contains(barcode),
        );
      }
      _materialsLoading = false;
      _materialsError = '';
    });
  }

  bool _materialContextIsCurrent(String orderId, String apparatus) {
    return mounted &&
        widget.order.map.id.trim() == orderId &&
        (widget.apparatus?.id.trim() ?? '') == apparatus;
  }

  Future<bool> _loadMaterialAssignments({bool showLoading = true}) async {
    final loadGeneration = ++_materialLoadGeneration;
    final orderId = widget.order.map.id.trim();
    final apparatus = widget.apparatus?.id.trim() ?? '';
    if (mounted) {
      setState(() {
        if (showLoading) {
          _materialsLoading = true;
        }
        _materialsError = '';
      });
    }
    try {
      final snapshot = await _fetchMaterialAssignments(
        orderId: orderId,
        apparatus: apparatus,
        materialBarcodes: _scannedMaterialBarcodes.toList(growable: false),
      );
      if (!mounted ||
          loadGeneration != _materialLoadGeneration ||
          widget.order.map.id.trim() != orderId ||
          (widget.apparatus?.id.trim() ?? '') != apparatus) {
        return false;
      }
      _applyMaterialAssignmentsSnapshot(snapshot);
      return true;
    } catch (error) {
      if (!mounted || loadGeneration != _materialLoadGeneration) {
        return false;
      }
      setState(() {
        _materialAssignments = const [];
        _startAssignments = const [];
        _intakeCandidateAssignments = const [];
        _materialStartRequirements = null;
        _materialsLoading = false;
        _materialsError = _readOnlyQueueActionErrorText(error, context.l10n);
      });
      return false;
    }
  }

  List<AdminRawMaterialAssignment> _startMaterialAssignments() {
    if (_materialStartRequirements == null) {
      // Training materials are attached to the training order even when the
      // backend intentionally hides the normal start-material gate.
      return _isTrainingOrder ? _materialAssignments : const [];
    }
    return _startAssignments;
  }

  Future<void> _unlinkMaterialAssignment(
    AdminRawMaterialAssignment assignment,
  ) async {
    if (!_allowMaterialUnlink ||
        !_rawMaterialAssignmentCanBeUnlinked(assignment) ||
        _unlinkingMaterialBarcode.isNotEmpty) {
      return;
    }
    final confirmed = await showM3ConfirmDialog(
          context: context,
          title: context.l10n.productionText('worker.material.unlink.title'),
          message: context.l10n.productionText(
            'worker.material.unlink.message',
          ),
          cancelLabel: context.l10n.productionText('worker.action.cancel'),
          confirmLabel: context.l10n.productionText(
            'worker.material.unlink.confirm',
          ),
          destructive: true,
          verticalActions: true,
          confirmButtonKey:
              const ValueKey('production-material-confirm-unlink'),
        ) ??
        false;
    if (!confirmed || !mounted) {
      return;
    }
    final barcode = _materialBarcodeKey(assignment.barcode);
    setState(() => _unlinkingMaterialBarcode = barcode);
    try {
      await MobileApi.instance.adminUnlinkRawMaterialAssignment(
        orderId: assignment.orderId,
        barcode: assignment.barcode,
      );
      await _loadMaterialAssignments(showLoading: false);
      if (mounted) {
        _showSheetNotice(
          context.l10n.productionText('worker.material.unlink.success'),
        );
      }
    } on MobileApiException catch (error) {
      if (mounted) {
        _showSheetNotice(error.message);
      }
    } catch (_) {
      if (mounted) {
        _showSheetNotice(
          context.l10n.productionText('worker.material.unlink.failed'),
        );
      }
    } finally {
      if (mounted) {
        setState(() => _unlinkingMaterialBarcode = '');
      }
    }
  }

  Future<void> _loadQolipRequirements() async {
    final apparatus = widget.apparatus?.id.trim() ?? '';
    final orderId = widget.order.map.id.trim();
    if (!_queueActionContractSynchronized ||
        _queueActionControl?.interaction?.qolipMode !=
            AdminQueueQolipMode.scanRequired) {
      return;
    }
    if (mounted) {
      setState(() {
        _qolipRequirementsLoading = true;
        _qolipRequirementsError = '';
      });
    }
    try {
      final validation =
          await MobileApi.instance.adminProductionMapQolipRequirements(
        apparatus: apparatus,
        orderId: orderId,
      );
      if (!mounted ||
          widget.apparatus?.id.trim() != apparatus ||
          widget.order.map.id.trim() != orderId) {
        return;
      }
      setState(() {
        _replaceRequiredQolips(validation.requiredQolips);
        _qolipRequirementsLoading = false;
        _qolipRequirementsError = '';
      });
    } catch (error) {
      if (!mounted ||
          widget.apparatus?.id.trim() != apparatus ||
          widget.order.map.id.trim() != orderId) {
        return;
      }
      setState(() {
        _requiredQolips.clear();
        _qolipRequirementsLoading = false;
        _qolipRequirementsError = _readOnlyQueueActionErrorText(
          error,
          context.l10n,
        );
      });
    }
  }

  void _replaceRequiredQolips(
    Iterable<AdminProductionMapRequiredQolip> qolips,
  ) {
    _requiredQolips
      ..clear()
      ..addEntries(
        qolips.where((qolip) => qolip.qolipCode.trim().isNotEmpty).map(
              (qolip) => MapEntry(
                qolip.qolipCode.trim().toLowerCase(),
                qolip,
              ),
            ),
      );
  }

  bool _completionNeedsFullReport(String action) {
    return action == 'complete' &&
        (_queueActionControl?.completeRequiresFullReport ?? true);
  }

  Future<AdminApparatusQueueOrderActionControl?>
      _loadCurrentQueueActionControl() async {
    final apparatus = widget.apparatus?.id.trim() ?? '';
    final orderId = widget.order.map.id.trim();
    if (apparatus.isEmpty || orderId.isEmpty) {
      return null;
    }
    final snapshot = await MobileApi.instance
        .adminProductionMapQueueSnapshot()
        .timeout(_queueActionControlRefreshTimeout);
    final control = snapshot.queueActionControls[apparatus]?[orderId];
    final nextQueueStates = snapshot.queueStates[apparatus];
    final nextStageStates = snapshot.stageStates[orderId];
    final nextOrderControl = snapshot.orderControlFor(orderId);
    if (mounted) {
      setState(() {
        _queueStates = Map<String, String>.from(nextQueueStates ?? const {});
        _stageStates = Map<String, String>.from(nextStageStates ?? const {});
        _orderControls = Map<String, AdminOrderControlState>.from(
          snapshot.orderControls,
        );
        _orderControlState = nextOrderControl;
      });
    }
    if (control?.isConsistentWith(
          nextOrderControl,
          queueState: snapshot.queueStates[apparatus]?[orderId],
        ) !=
        true) {
      return null;
    }
    return control;
  }

  Future<AdminProductionOrderFreezeDetails?>
      _loadAuthoritativeFreezeRequest() async {
    try {
      final control = await _loadCurrentQueueActionControl();
      if (!mounted) return null;
      final request = control?.freezeRequest;
      final apparatus = widget.apparatus?.id.trim() ?? '';
      final initialRequestId = widget.initialPauseRequestId.trim();
      final valid = control != null &&
          control.state.trim() == 'in_progress' &&
          request != null &&
          request.status.trim() == 'pending' &&
          request.requestId.trim().isNotEmpty &&
          request.targetSessionId.trim().isNotEmpty &&
          request.targetApparatus.trim() == apparatus &&
          (initialRequestId.isEmpty ||
              request.requestId.trim() == initialRequestId);
      if (!valid) {
        _showSheetNotice(
          context.l10n.productionText(
            'worker.freeze.safe_stop.metadata_missing',
          ),
        );
        return null;
      }
      setState(() => _queueActionControl = control);
      return request;
    } catch (_) {
      if (mounted) {
        _showSheetNotice(
          context.l10n.productionText(
            'worker.freeze.safe_stop.metadata_missing',
          ),
        );
      }
      return null;
    }
  }
}
