// Generated by large_library_splitter.dart; keep changes in the source library.
part of 'admin_production_map_orders_screen.dart';

class _MaterialAssignmentsSnapshot {
  const _MaterialAssignmentsSnapshot({
    required this.assignments,
    required this.startAssignments,
    required this.intakeCandidateAssignments,
    required this.requirements,
  });

  final List<AdminRawMaterialAssignment> assignments;
  final List<AdminRawMaterialAssignment> startAssignments;
  final List<AdminRawMaterialAssignment> intakeCandidateAssignments;
  final AdminRawMaterialStartRequirements? requirements;
}

class _ReadOnlyOrderDetailSheet extends StatefulWidget {
  const _ReadOnlyOrderDetailSheet({
    required this.order,
    this.apparatusCatalog = const [],
    this.baseMetraj,
    this.orderKg,
    this.customerName,
    this.apparatus,
    this.canManageQueue = false,
    this.workerMode = false,
    this.initialQueueStates = const {},
    this.queueStatesByApparatus = const {},
    this.stageStatesByOrderId = const {},
    this.queueActionControl,
    this.queuePolicy = ApparatusQueuePolicy.strictSequence,
    this.sequenceOrderIds = const [],
    this.visibleOrderIds = const [],
    this.onQueueAction,
    this.progressDriverUrlPicker,
    this.initialOrderControls = const {},
    this.initialOrderSwitchBatch,
    this.initialPauseRequestId = '',
    this.startPauseOnOpen = false,
    this.startWorkerHandoffOnOpen = false,
    this.startAstatkaOnOpen = false,
    this.startRollRemovalOnOpen = false,
    this.startResumeOnOpen = false,
  });

  final ProductionMapSaved order;
  final List<AdminApparatus> apparatusCatalog;
  final double? baseMetraj;
  final double? orderKg;
  final String? customerName;
  final AdminApparatus? apparatus;
  final bool canManageQueue;
  final bool workerMode;
  final Map<String, String> initialQueueStates;
  final Map<String, Map<String, String>> queueStatesByApparatus;
  final Map<String, Map<String, String>> stageStatesByOrderId;
  final AdminApparatusQueueOrderActionControl? queueActionControl;
  final ApparatusQueuePolicy queuePolicy;
  final List<String> sequenceOrderIds;
  final List<String> visibleOrderIds;
  final _ReadOnlyQueueActionCallback? onQueueAction;
  final Future<String?> Function(BuildContext context)? progressDriverUrlPicker;
  final Map<String, AdminOrderControlState> initialOrderControls;
  final AdminProgressBatch? initialOrderSwitchBatch;
  final String initialPauseRequestId;
  final bool startPauseOnOpen;
  final bool startWorkerHandoffOnOpen;
  final bool startAstatkaOnOpen;
  final bool startRollRemovalOnOpen;
  final bool startResumeOnOpen;

  @override
  State<_ReadOnlyOrderDetailSheet> createState() =>
      _ReadOnlyOrderDetailSheetState();
}
