// Generated by large_library_splitter.dart; keep changes in the source library.
part of 'admin_notifications_screen.dart';

class _CompletionRequestDetails extends StatelessWidget {
  const _CompletionRequestDetails({
    required this.request,
    required this.apparatusLabel,
    required this.deciding,
    required this.onApprove,
    required this.onReject,
  });

  final AdminCompletionRequestNotification request;
  final String apparatusLabel;
  final bool deciding;
  final VoidCallback onApprove;
  final VoidCallback onReject;

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final scheme = theme.colorScheme;
    final l10n = context.l10n;
    final lines = <String>[
      if (request.orderTitle.trim().isNotEmpty)
        l10n.adminText(
          'notification.item_line',
          values: {'value': request.orderTitle.trim()},
        ),
      if (request.productCode.trim().isNotEmpty)
        l10n.adminText(
          'notification.code_line',
          values: {'value': request.productCode.trim()},
        ),
      if (apparatusLabel.trim().isNotEmpty)
        l10n.adminText(
          'notification.apparatus_line',
          values: {'value': apparatusLabel.trim()},
        ),
      l10n.adminText(
        'notification.worker_line',
        values: {
          'value': _actorLabel(
            displayName: request.workerDisplayName,
            role: request.workerRole,
            ref: request.workerRef,
            l10n: l10n,
          ),
        },
      ),
      if (_timeLabel(request.createdAtUnix).isNotEmpty)
        l10n.adminText(
          'notification.time_line',
          values: {'value': _timeLabel(request.createdAtUnix)},
        ),
    ];
    final zeroMetricLabels = _zeroMetricLabels(
      request.zeroMetricCodes,
      l10n,
    );

    return Padding(
      padding: const EdgeInsets.fromLTRB(60, 0, 14, 14),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          for (final line in lines)
            Padding(
              padding: const EdgeInsets.only(bottom: 6),
              child: Text(
                line,
                style: theme.textTheme.bodySmall?.copyWith(
                  color: scheme.onSurfaceVariant,
                  height: 1.25,
                  fontWeight: FontWeight.w600,
                ),
              ),
            ),
          if (zeroMetricLabels.isNotEmpty) ...[
            const SizedBox(height: 2),
            Text(
              l10n.adminText('notification.zero_metrics'),
              style: theme.textTheme.labelLarge?.copyWith(
                color: scheme.error,
                fontWeight: FontWeight.w800,
              ),
            ),
            const SizedBox(height: 3),
            Text(
              zeroMetricLabels.join(', '),
              style: theme.textTheme.bodySmall?.copyWith(
                color: scheme.onSurfaceVariant,
                height: 1.25,
                fontWeight: FontWeight.w700,
              ),
            ),
            const SizedBox(height: 10),
          ],
          if (request.description.trim().isNotEmpty)
            Text(
              request.description.trim(),
              style: theme.textTheme.bodyMedium?.copyWith(
                height: 1.35,
                fontWeight: FontWeight.w800,
                color: scheme.onSurface,
              ),
            ),
          const SizedBox(height: 14),
          if (request.decisionRequired) ...[
            Text(
              l10n.adminText('notification.approval_question'),
              style: theme.textTheme.titleSmall?.copyWith(
                fontWeight: FontWeight.w800,
                color: scheme.onSurface,
              ),
            ),
            const SizedBox(height: 10),
            Row(
              children: [
                Expanded(
                  child: OutlinedButton(
                    onPressed: deciding ? null : onReject,
                    child: Text(l10n.adminText('notification.reject')),
                  ),
                ),
                const SizedBox(width: 10),
                Expanded(
                  child: FilledButton(
                    onPressed: deciding ? null : onApprove,
                    child: deciding
                        ? const SizedBox.square(
                            dimension: 18,
                            child: CircularProgressIndicator(strokeWidth: 2),
                          )
                        : Text(l10n.adminText('notification.confirm')),
                  ),
                ),
              ],
            ),
          ],
        ],
      ),
    );
  }
}

String _requestDisplayCode(
  AdminCompletionRequestNotification request,
  AppLocalizations l10n,
) {
  final orderNumber = request.orderNumber.trim();
  if (orderNumber.isNotEmpty) {
    return orderNumber;
  }
  final orderId = request.orderId.trim();
  if (orderId.isNotEmpty) {
    return orderId;
  }
  return l10n.adminText('notification.order_fallback');
}

String _actorLabel({
  required String displayName,
  required String role,
  required String ref,
  required AppLocalizations l10n,
}) {
  final name = displayName.trim();
  if (name.isNotEmpty) {
    return name;
  }
  final workerRef = ref.trim();
  if (workerRef.isNotEmpty) {
    return workerRef;
  }
  final workerRole = role.trim();
  if (workerRole.isNotEmpty) {
    return workerRole;
  }
  return l10n.adminText('notification.worker_fallback');
}

String _timeLabel(int unix) => formatUnixSecondsLocalDateTime(unix);

List<String> _zeroMetricLabels(
  List<String> codes,
  AppLocalizations l10n,
) {
  final labels = <String, String>{
    'produced_qty': l10n.productionText('worker.qr.passport.produced_quantity'),
    'gross_qty': l10n.productionText('worker.daily.field.weight'),
    'return_ink_kg': l10n.productionText('worker.qr.passport.returned_ink'),
    'lamination_print_leftover_rolls':
        l10n.productionText('worker.daily.field.print_leftover'),
    'lamination_film_leftover_rolls':
        l10n.productionText('worker.daily.field.film_leftover'),
    'rezka_bosma_waste': l10n.productionText('worker.daily.field.print_waste'),
    'rezka_lamination_waste':
        l10n.productionText('worker.daily.field.lamination_waste'),
    'rezka_edge_waste': l10n.productionText('worker.daily.field.edge_waste'),
    'total_waste': l10n.productionText('worker.daily.field.total_waste'),
    'finished_goods_kg':
        l10n.productionText('worker.qr.passport.finished_weight'),
    'finished_goods_meter':
        l10n.productionText('worker.qr.passport.finished_length'),
  };
  return [
    for (final code in codes) labels[code.trim()] ?? code.trim(),
  ].where((label) => label.isNotEmpty).toList(growable: false);
}
