// Generated by large_library_splitter.dart; keep changes in the source library.
part of 'admin_production_map_orders_screen.dart';

class _OpeningWipQrTile extends StatelessWidget {
  const _OpeningWipQrTile({
    required this.previousStage,
    required this.apparatusCatalog,
    required this.ready,
    required this.batch,
    required this.availableBatches,
    required this.loading,
    required this.error,
  });

  final String previousStage;
  final List<AdminApparatus> apparatusCatalog;
  final bool ready;
  final AdminOpeningWipBatch? batch;
  final List<AdminOpeningWipBatch> availableBatches;
  final bool loading;
  final String error;

  @override
  Widget build(BuildContext context) {
    final progressBatches = availableBatches
        .map((item) => _openingWipAsProgressBatch(item, previousStage))
        .toList(growable: false);
    final selectedProgressBatch = batch == null
        ? null
        : _openingWipAsProgressBatch(batch!, previousStage);
    return _PreviousProgressQrTile(
      key: const ValueKey('production-order-opening-wip-input'),
      previousStage: previousStage,
      apparatusCatalog: apparatusCatalog,
      ready: ready,
      batch: selectedProgressBatch,
      availableBatches: progressBatches,
      loading: loading,
      error: error,
    );
  }
}

AdminProgressBatch _openingWipAsProgressBatch(
  AdminOpeningWipBatch batch,
  String sourceApparatus, {
  AdminOpeningWipIntake? intake,
  String nextApparatus = '',
}) {
  final wipStatus = batch.wipStatus.trim().toLowerCase();
  final producedQty =
      batch.finishedGoodsMeter ?? batch.quantity ?? batch.finishedGoodsKg ?? 0;
  final uom = batch.finishedGoodsMeter != null
      ? 'm'
      : batch.uom.trim().isNotEmpty
          ? batch.uom.trim()
          : 'kg';
  final flowStatus = switch (wipStatus) {
    'in_use' => 'in_progress',
    'processed' => 'consumed_by_next_stage',
    _ when nextApparatus.trim().isEmpty => 'free_wip',
    _ => 'waiting_next_stage',
  };
  return AdminProgressBatch(
    batchId: batch.batchId,
    sessionId: _workerWipFirstNotEmpty([
      batch.usedBySessionId,
      batch.processedBySessionId,
      batch.intakeId,
    ]),
    apparatus: sourceApparatus,
    orderId: batch.orderId,
    action: '',
    status: batch.wipStatus,
    producedQty: producedQty,
    uom: uom,
    qrPayload: batch.qrPayload,
    labelItemCode: batch.labelItemCode,
    labelItemName: batch.labelItemName,
    executorName: intake?.actorDisplayName ?? '',
    diameter: batch.diameter,
    finishedGoodsKg: batch.finishedGoodsKg,
    bobinaKg: batch.bobinaKg,
    finishedGoodsMeter: batch.finishedGoodsMeter,
    description: intake?.note ?? '',
    workerRole: intake?.actorRole ?? '',
    workerRef: intake?.actorRef ?? '',
    workerDisplayName: intake?.actorDisplayName ?? '',
    wipStatus: wipStatus,
    statusDetail: AdminProgressBatchStatusDetail(
      workStatus: 'completed',
      wipStatus: wipStatus,
      flowStatus: flowStatus,
    ),
    currentApparatus: sourceApparatus,
    currentApparatusKey: sourceApparatus,
    nextApparatus: nextApparatus,
    usedBySessionId: batch.usedBySessionId,
    usedByApparatus: batch.usedByApparatus,
    processedBySessionId: batch.processedBySessionId,
    processedByApparatus: batch.processedByApparatus,
    startedAtUnix: batch.createdAtUnix,
    completedAtUnix: batch.updatedAtUnix,
    payloadJson: const {'input_wip_source_kind': 'opening_wip'},
  );
}

class _PreviousProgressQrTile extends StatelessWidget {
  const _PreviousProgressQrTile({
    super.key,
    required this.previousStage,
    required this.apparatusCatalog,
    required this.ready,
    required this.batch,
    required this.availableBatches,
    required this.loading,
    required this.error,
  });

  final String previousStage;
  final List<AdminApparatus> apparatusCatalog;
  final bool ready;
  final AdminProgressBatch? batch;
  final List<AdminProgressBatch> availableBatches;
  final bool loading;
  final String error;

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final scheme = theme.colorScheme;
    final progressBatch = batch;
    final batchQty = progressBatch == null
        ? ''
        : _productionMapQtyLabel(progressBatch.producedQty);
    return Container(
      padding: const EdgeInsets.fromLTRB(12, 12, 12, 12),
      decoration: BoxDecoration(
        color: ready
            ? scheme.primaryContainer.withValues(alpha: 0.45)
            : scheme.surfaceContainerHighest,
        borderRadius: BorderRadius.circular(12),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Container(
                width: 40,
                height: 40,
                decoration: BoxDecoration(
                  color: ready
                      ? scheme.primary.withValues(alpha: 0.14)
                      : scheme.surface,
                  borderRadius: BorderRadius.circular(12),
                ),
                child: Icon(
                  ready ? Icons.check_rounded : Icons.qr_code_scanner_rounded,
                  color: ready ? scheme.primary : scheme.onSurfaceVariant,
                  size: 22,
                ),
              ),
              const SizedBox(width: 12),
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      ready
                          ? context.l10n.productionText(
                              'worker.progress.previous.confirmed',
                            )
                          : context.l10n.productionText(
                              'worker.progress.previous.qr',
                            ),
                      style: theme.textTheme.bodyLarge?.copyWith(
                        fontWeight: FontWeight.w700,
                      ),
                    ),
                    const SizedBox(height: 4),
                    Text(
                      ready && progressBatch != null
                          ? '${canonicalApparatusDisplayLabel(progressBatch.apparatus, apparatusCatalog)} • $batchQty ${progressBatch.uom}'
                          : canonicalApparatusDisplayLabel(
                              previousStage,
                              apparatusCatalog,
                            ),
                      maxLines: 2,
                      overflow: TextOverflow.ellipsis,
                      style: theme.textTheme.bodySmall?.copyWith(
                        color: scheme.onSurfaceVariant,
                        fontWeight: FontWeight.w500,
                      ),
                    ),
                  ],
                ),
              ),
            ],
          ),
          const SizedBox(height: 10),
          const SizedBox(height: 12),
          _InputProgressBatchList(
            previousStage: previousStage,
            apparatusCatalog: apparatusCatalog,
            selectedBatch: progressBatch,
            batches: availableBatches,
            loading: loading,
            error: error,
          ),
        ],
      ),
    );
  }
}

class _InputProgressBatchList extends StatelessWidget {
  const _InputProgressBatchList({
    required this.previousStage,
    required this.apparatusCatalog,
    required this.selectedBatch,
    required this.batches,
    required this.loading,
    required this.error,
  });

  final String previousStage;
  final List<AdminApparatus> apparatusCatalog;
  final AdminProgressBatch? selectedBatch;
  final List<AdminProgressBatch> batches;
  final bool loading;
  final String error;

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final scheme = theme.colorScheme;
    final openCount = batches.where(_progressBatchCanBeScanned).length;
    final usedCount = batches.length - openCount;
    return Container(
      padding: const EdgeInsets.fromLTRB(10, 10, 10, 10),
      decoration: BoxDecoration(
        color: scheme.surface.withValues(alpha: 0.72),
        borderRadius: BorderRadius.circular(12),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          Text(
            context.l10n.productionText('worker.progress.products'),
            style: theme.textTheme.bodyMedium?.copyWith(
              fontWeight: FontWeight.w800,
            ),
          ),
          const SizedBox(height: 3),
          Text(
            _inputProgressSummaryText(
              l10n: context.l10n,
              previousStageLabel: canonicalApparatusDisplayLabel(
                previousStage,
                apparatusCatalog,
              ),
              total: batches.length,
              open: openCount,
              used: usedCount,
            ),
            maxLines: 3,
            overflow: TextOverflow.ellipsis,
            style: theme.textTheme.bodySmall?.copyWith(
              color: scheme.onSurfaceVariant,
              fontWeight: FontWeight.w600,
            ),
          ),
          if (loading) ...[
            const SizedBox(height: 10),
            LinearProgressIndicator(color: scheme.primary),
          ] else if (error.trim().isNotEmpty) ...[
            const SizedBox(height: 10),
            Text(
              error,
              style: theme.textTheme.bodySmall?.copyWith(
                color: scheme.error,
                fontWeight: FontWeight.w700,
              ),
            ),
          ] else if (batches.isEmpty) ...[
            const SizedBox(height: 10),
            Text(
              context.l10n.productionText(
                'worker.progress.none',
                values: {
                  'stage': canonicalApparatusDisplayLabel(
                    previousStage,
                    apparatusCatalog,
                  ),
                },
              ),
              style: theme.textTheme.bodySmall?.copyWith(
                color: scheme.onSurfaceVariant,
                fontWeight: FontWeight.w700,
              ),
            ),
          ] else ...[
            const SizedBox(height: 10),
            for (var index = 0; index < batches.length; index++) ...[
              if (index > 0) const SizedBox(height: 8),
              _InputProgressBatchTile(
                batch: batches[index],
                apparatusCatalog: apparatusCatalog,
                selected: selectedBatch != null &&
                    (selectedBatch!.batchId.trim() ==
                            batches[index].batchId.trim() ||
                        selectedBatch!.qrPayload.trim().toUpperCase() ==
                            batches[index].qrPayload.trim().toUpperCase()),
              ),
            ],
          ],
        ],
      ),
    );
  }
}
