// Generated by large_library_splitter.dart; keep changes in the source library.
part of 'admin_customer_detail_screen.dart';

class _AdminCustomerDetailCard extends StatelessWidget {
  const _AdminCustomerDetailCard({
    required this.detail,
    required this.statusLabel,
    required this.profileSubtitle,
    required this.namelessLabel,
    required this.customerManagementEnabled,
    required this.itemManagementEnabled,
    required this.removeEnabled,
    required this.isMaterialTaminotchi,
    required this.chatTarget,
    required this.warehouseEditor,
    required this.expanded,
    required this.savingPhone,
    required this.regeneratingCode,
    required this.removing,
    required this.addingItem,
    required this.editingMaterialItemGroups,
    required this.removingItemCode,
    required this.onExpandedChanged,
    required this.onSavePhone,
    required this.onAddItem,
    required this.onRemoveItem,
    required this.onEditMaterialItemGroups,
    required this.onRegenerateCode,
    required this.onCopyCode,
    required this.onRemove,
  });

  final AdminCustomerDetail detail;
  final String statusLabel;
  final String profileSubtitle;
  final String namelessLabel;
  final bool customerManagementEnabled;
  final bool itemManagementEnabled;
  final bool removeEnabled;
  final bool isMaterialTaminotchi;
  final ChatDirectoryEntry? chatTarget;
  final Widget? warehouseEditor;
  final bool expanded;
  final bool savingPhone;
  final bool regeneratingCode;
  final bool removing;
  final bool addingItem;
  final bool editingMaterialItemGroups;
  final String? removingItemCode;
  final ValueChanged<bool> onExpandedChanged;
  final Future<void> Function(AdminCustomerDetail detail, String phone)
      onSavePhone;
  final Future<void> Function() onAddItem;
  final Future<bool> Function(SupplierItem item) onRemoveItem;
  final Future<void> Function() onEditMaterialItemGroups;
  final Future<void> Function() onRegenerateCode;
  final Future<void> Function(String code) onCopyCode;
  final Future<void> Function() onRemove;

  @override
  Widget build(BuildContext context) {
    final l10n = context.l10n;
    final theme = Theme.of(context);
    final scheme = theme.colorScheme;
    final phone = detail.phone.trim();
    final initials = _customerInitials(detail.name);

    return Column(
      crossAxisAlignment: CrossAxisAlignment.stretch,
      children: [
        SizedBox(
          height: 204,
          child: Stack(
            clipBehavior: Clip.none,
            children: [
              Positioned.fill(
                top: 112,
                child: ColoredBox(color: scheme.surface),
              ),
              const Positioned(
                left: 0,
                right: 0,
                top: 0,
                height: 112,
                child: ColoredBox(color: Colors.black),
              ),
              Positioned(
                right: 14,
                top: 14,
                child: AppStatusChip(label: statusLabel),
              ),
              Positioned(
                left: 16,
                top: 74,
                child: AdminProfileAvatar(
                  avatarUrl: detail.avatarUrl,
                  fallbackText: initials,
                ),
              ),
              Positioned(
                left: 124,
                right: 16,
                top: 140,
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      detail.name.trim().isEmpty ? namelessLabel : detail.name,
                      maxLines: 1,
                      overflow: TextOverflow.ellipsis,
                      style: theme.textTheme.headlineSmall?.copyWith(
                        fontWeight: FontWeight.w800,
                        height: 1.08,
                      ),
                    ),
                    const SizedBox(height: 6),
                    Text(
                      profileSubtitle,
                      maxLines: 1,
                      overflow: TextOverflow.ellipsis,
                      style: theme.textTheme.bodySmall?.copyWith(
                        color: scheme.onSurfaceVariant,
                      ),
                    ),
                  ],
                ),
              ),
            ],
          ),
        ),
        Padding(
          padding: const EdgeInsets.fromLTRB(16, 2, 16, 16),
          child: Row(
            crossAxisAlignment: CrossAxisAlignment.end,
            children: [
              Expanded(
                child: Wrap(
                  spacing: 8,
                  runSpacing: 8,
                  children: [
                    ProfileInfoChip(
                      icon: Icons.phone_rounded,
                      label: phone.isEmpty
                          ? l10n.adminText('profile.phone_missing')
                          : phone,
                    ),
                    if (isMaterialTaminotchi) ...[
                      ProfileInfoChip(
                        icon: Icons.category_outlined,
                        label: l10n.adminText(
                          'detail.groups_count',
                          values: {'count': detail.assignedItemGroups.length},
                        ),
                      ),
                      ProfileInfoChip(
                        icon: Icons.warehouse_outlined,
                        label: l10n.adminText(
                          'detail.warehouses_count',
                          values: {'count': detail.assignedWarehouses.length},
                        ),
                      ),
                    ] else
                      ProfileInfoChip(
                        icon: Icons.shopping_bag_rounded,
                        label: l10n.adminText(
                          'detail.items_count',
                          values: {'count': detail.assignedItems.length},
                        ),
                      ),
                    if (chatTarget != null)
                      ChatProfileActionButton(
                        key: const ValueKey(
                          'admin-customer-detail-chat-action',
                        ),
                        target: chatTarget!,
                      ),
                  ],
                ),
              ),
              if (customerManagementEnabled) ...[
                const SizedBox(width: 8),
                IconButton(
                  key: const ValueKey('admin-customer-detail-admin-toggle'),
                  tooltip: expanded
                      ? l10n.adminText('profile.controls_close')
                      : l10n.adminText('profile.controls_open'),
                  onPressed: () => onExpandedChanged(!expanded),
                  icon: AnimatedRotation(
                    turns: expanded ? 0.5 : 0,
                    duration: const Duration(milliseconds: 180),
                    curve: Curves.easeOutCubic,
                    child: Icon(
                      Icons.keyboard_arrow_down_rounded,
                      color: scheme.onSurfaceVariant,
                    ),
                  ),
                ),
              ],
            ],
          ),
        ),
        AnimatedSize(
          duration: const Duration(milliseconds: 180),
          curve: Curves.easeOutCubic,
          alignment: Alignment.topCenter,
          child: expanded
              ? Padding(
                  padding: const EdgeInsets.fromLTRB(16, 0, 16, 16),
                  child: _AdminCustomerPanel(
                    detail: detail,
                    itemManagementEnabled: itemManagementEnabled,
                    removeEnabled: removeEnabled,
                    isMaterialTaminotchi: isMaterialTaminotchi,
                    warehouseEditor: warehouseEditor,
                    savingPhone: savingPhone,
                    regeneratingCode: regeneratingCode,
                    removing: removing,
                    addingItem: addingItem,
                    editingMaterialItemGroups: editingMaterialItemGroups,
                    removingItemCode: removingItemCode,
                    onSavePhone: onSavePhone,
                    onAddItem: onAddItem,
                    onRemoveItem: onRemoveItem,
                    onEditMaterialItemGroups: onEditMaterialItemGroups,
                    onRegenerateCode: onRegenerateCode,
                    onCopyCode: onCopyCode,
                    onRemove: onRemove,
                  ),
                )
              : const SizedBox.shrink(),
        ),
      ],
    );
  }
}
