// Generated by large_library_splitter.dart; keep changes in the source library.
part of 'admin_production_map_orders_screen.dart';

class _RawMaterialBalanceSummary extends StatelessWidget {
  const _RawMaterialBalanceSummary({required this.balances});

  final List<_RawMaterialBalance> balances;

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final scheme = theme.colorScheme;
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(12),
      decoration: BoxDecoration(
        color: scheme.secondaryContainer.withValues(alpha: 0.55),
        borderRadius: BorderRadius.circular(12),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            context.l10n.productionText('worker.material.balance'),
            style: theme.textTheme.labelLarge?.copyWith(
              color: scheme.onSecondaryContainer,
              fontWeight: FontWeight.w800,
            ),
          ),
          const SizedBox(height: 6),
          for (var index = 0; index < balances.length; index++) ...[
            if (index > 0) const SizedBox(height: 4),
            Text(
              context.l10n.productionText(
                'worker.material.balance.summary',
                values: {
                  'received':
                      '${formatRawQuantity(balances[index].receivedQty)} ${balances[index].uom}',
                  'used':
                      '${formatRawQuantity(balances[index].consumedQty)} ${balances[index].uom}',
                  'remaining':
                      '${formatRawQuantity(balances[index].remainingQty)} ${balances[index].uom}',
                },
              ),
              style: theme.textTheme.bodySmall?.copyWith(
                color: scheme.onSecondaryContainer,
                fontWeight: FontWeight.w700,
              ),
            ),
          ],
        ],
      ),
    );
  }
}

class _AssignedMaterialTile extends StatelessWidget {
  const _AssignedMaterialTile({
    required this.assignment,
    required this.scanned,
    required this.allowUnlink,
    required this.onUnlink,
    required this.unlinking,
  });

  final AdminRawMaterialAssignment assignment;
  final bool scanned;
  final bool allowUnlink;
  final VoidCallback? onUnlink;
  final bool unlinking;

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final scheme = theme.colorScheme;
    final title = assignment.itemName.trim().isEmpty
        ? assignment.itemCode.trim()
        : assignment.itemName.trim();
    final details = <String>[];
    void addDetail(String value) {
      final normalized = value.trim();
      if (normalized.isEmpty ||
          details.any(
            (item) => item.toLowerCase() == normalized.toLowerCase(),
          )) {
        return;
      }
      details.add(normalized);
    }

    final itemCode = assignment.itemCode.trim();
    if (itemCode.isNotEmpty && itemCode.toLowerCase() != title.toLowerCase()) {
      final titlePrefix = title.toLowerCase();
      final codeLower = itemCode.toLowerCase();
      final remainder = title.isNotEmpty && codeLower.startsWith(titlePrefix)
          ? itemCode.substring(title.length).trim()
          : itemCode;
      addDetail(remainder.replaceFirst(RegExp(r'^[•·|,/-]+\s*'), ''));
    }
    addDetail(assignment.itemGroup);
    addDetail(assignment.barcode);
    final materialStateVisible = allowUnlink;
    final statusText = materialStateVisible
        ? _rawMaterialAssignmentStatusText(assignment, context.l10n)
        : '';

    var primary = title;
    if (primary.isEmpty && details.isNotEmpty) {
      primary = details.removeAt(0);
    }
    final consumed =
        materialStateVisible && _rawMaterialAssignmentIsConsumed(assignment);
    final locked =
        materialStateVisible && _rawMaterialAssignmentIsLocked(assignment);
    final canUnlink = allowUnlink &&
        onUnlink != null &&
        _rawMaterialAssignmentCanBeUnlinked(assignment);
    final muted = consumed || (locked && !scanned);
    final normalizedBarcode = assignment.barcode.trim().toUpperCase();
    return Container(
      padding: const EdgeInsets.fromLTRB(12, 10, 12, 10),
      decoration: BoxDecoration(
        color: muted
            ? scheme.surface.withValues(alpha: 0.5)
            : scanned
                ? scheme.primaryContainer.withValues(alpha: 0.45)
                : scheme.surfaceContainerHighest,
        borderRadius: BorderRadius.circular(12),
      ),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Container(
            width: 36,
            height: 36,
            decoration: BoxDecoration(
              color: muted
                  ? scheme.surface.withValues(alpha: 0.7)
                  : scanned
                      ? scheme.primary.withValues(alpha: 0.14)
                      : scheme.surface,
              borderRadius: BorderRadius.circular(12),
            ),
            child: Icon(
              consumed
                  ? Icons.check_circle_outline_rounded
                  : scanned
                      ? Icons.check_rounded
                      : Icons.science_outlined,
              color: consumed
                  ? scheme.onSurfaceVariant.withValues(alpha: 0.65)
                  : scanned
                      ? scheme.primary
                      : scheme.onSurfaceVariant,
              size: 20,
            ),
          ),
          const SizedBox(width: 12),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text.rich(
                  TextSpan(
                    children: [
                      if (primary.isNotEmpty)
                        TextSpan(
                          text: primary,
                          style: theme.textTheme.bodyMedium?.copyWith(
                            color: muted
                                ? scheme.onSurface.withValues(alpha: 0.55)
                                : null,
                            fontWeight: FontWeight.w700,
                          ),
                        ),
                      if (details.isNotEmpty)
                        TextSpan(
                          text:
                              '${primary.isEmpty ? '' : ' • '}${details.join(' • ')}',
                          style: theme.textTheme.bodySmall?.copyWith(
                            color: scheme.onSurfaceVariant,
                            fontWeight: FontWeight.w500,
                          ),
                        ),
                    ],
                  ),
                  maxLines: 2,
                  overflow: TextOverflow.ellipsis,
                ),
                if (statusText.isNotEmpty) ...[
                  const SizedBox(height: 2),
                  Text(
                    statusText,
                    style: theme.textTheme.labelSmall?.copyWith(
                      color: muted
                          ? scheme.onSurfaceVariant.withValues(alpha: 0.65)
                          : scheme.primary,
                      fontWeight: FontWeight.w700,
                    ),
                  ),
                ],
              ],
            ),
          ),
          if (allowUnlink) ...[
            const SizedBox(width: 4),
            IconButton(
              key: ValueKey('raw-material-unlink-$normalizedBarcode'),
              tooltip: canUnlink
                  ? context.l10n.productionText('worker.material.unlink')
                  : context.l10n.productionText(
                      'worker.material.unlink.disabled',
                      values: {
                        'status': statusText.isEmpty
                            ? context.l10n.productionText(
                                'worker.materials.attached',
                              )
                            : statusText,
                      },
                    ),
              onPressed: canUnlink && !unlinking ? onUnlink : null,
              icon: unlinking
                  ? const SizedBox.square(
                      dimension: 18,
                      child: CircularProgressIndicator(strokeWidth: 2),
                    )
                  : const Icon(Icons.link_off_rounded),
            ),
          ],
        ],
      ),
    );
  }
}
