// Generated by large_library_splitter.dart; keep changes in the source library.
part of 'admin_production_map_orders_screen.dart';

class _ApparatusTransferReasonDialog extends StatefulWidget {
  const _ApparatusTransferReasonDialog({
    required this.orderCount,
    required this.from,
    required this.to,
  });

  final int orderCount;
  final AdminApparatus from;
  final AdminApparatus to;

  @override
  State<_ApparatusTransferReasonDialog> createState() =>
      _ApparatusTransferReasonDialogState();
}

class _ApparatusTransferReasonDialogState
    extends State<_ApparatusTransferReasonDialog> {
  late final TextEditingController _controller;
  String _validationMessage = '';

  @override
  void initState() {
    super.initState();
    _controller = TextEditingController();
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return AlertDialog(
      insetPadding: const EdgeInsets.symmetric(horizontal: 20, vertical: 24),
      title: Text(context.l10n.adminText('production.transfer.title')),
      content: SingleChildScrollView(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            Text(
              context.l10n.adminText(
                'production.transfer.message',
                values: {
                  'count': widget.orderCount,
                  'from': widget.from.name,
                  'to': widget.to.name,
                },
              ),
            ),
            const SizedBox(height: 12),
            TextField(
              key: const ValueKey('apparatus-transfer-reason'),
              controller: _controller,
              autofocus: true,
              maxLines: 3,
              maxLength: 500,
              decoration: InputDecoration(
                labelText: context.l10n.adminText(
                  'production.transfer.reason',
                ),
                hintText: context.l10n.adminText(
                  'production.transfer.hint',
                ),
                errorText:
                    _validationMessage.isEmpty ? null : _validationMessage,
              ),
            ),
          ],
        ),
      ),
      actionsPadding: const EdgeInsets.fromLTRB(20, 0, 20, 20),
      actions: [
        SizedBox(
          width: double.infinity,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              FilledButton(
                onPressed: () {
                  final reason = _controller.text.trim();
                  if (reason.isEmpty) {
                    setState(() {
                      _validationMessage = context.l10n.adminText(
                        'production.transfer.required',
                      );
                    });
                    return;
                  }
                  Navigator.of(context).pop(reason);
                },
                child: Text(
                  context.l10n.adminText('production.transfer.move'),
                ),
              ),
              const SizedBox(height: 10),
              OutlinedButton(
                onPressed: () => Navigator.of(context).pop(),
                child: Text(context.l10n.adminText('action.cancel')),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
