// Generated by large_library_splitter.dart; keep changes in the source library.
part of 'admin_progress_qr_scan_screen.dart';

extension __AdminProgressQrScanScreenStateAstPart01
    on _AdminProgressQrScanScreenState {
  Future<void> _loadApparatusCatalog() async {
    try {
      final apparatus = await MobileApi.instance.adminApparatus(limit: 10000);
      if (!mounted) {
        return;
      }
      setState(() => _apparatusCatalog = apparatus);
    } catch (_) {
      // QR identity remains the exact ApparatusId when display projection fails.
    }
  }

  String _statusText(AppLocalizations l10n) {
    return switch (_scanStatus) {
      _QrScanStatus.prompt => l10n.productionText(
          'worker.scanner.progress_prompt',
        ),
      _QrScanStatus.cameraFailed => l10n.productionText(
          'worker.scanner.camera_failed',
        ),
      _QrScanStatus.invalidQr => l10n.productionText(
          'worker.scanner.invalid_qr',
        ),
      _QrScanStatus.loading => l10n.productionText('worker.scanner.lookup'),
      _QrScanStatus.reportReady => l10n.productionText(
          'worker.scanner.report_ready',
        ),
      _QrScanStatus.paddonReady => l10n.productionText(
          'worker.scanner.paddon_ready',
        ),
      _QrScanStatus.materialReady => l10n.productionText(
          'worker.scanner.material_ready',
        ),
      _QrScanStatus.error => _errorText(l10n),
    };
  }

  String _errorText(AppLocalizations l10n) {
    final code = _scanErrorCode;
    if (code == 'progress_batch_not_found' ||
        code == 'progress_batch_not_accepted') {
      return l10n.productionErrorMessage(
        code!,
        fallback: l10n.productionText('worker.scanner.report_failed'),
      );
    }
    return l10n.productionText('worker.scanner.report_failed');
  }

  Future<void> _startScanner() async {
    final session = _scannerSession;
    if (!mounted || session == null) {
      return;
    }
    final started = await session.retry();
    if (!mounted) {
      return;
    }
    setState(() {
      _processing = false;
      _scanErrorCode = started || session.phase != ReliableScannerPhase.error
          ? null
          : 'camera_failed';
      _scanStatus = started || session.phase != ReliableScannerPhase.error
          ? _QrScanStatus.prompt
          : _QrScanStatus.cameraFailed;
    });
  }

  Future<void> _stopScanner() async {
    final session = _scannerSession;
    if (session == null) {
      return;
    }
    await session.stop();
  }

  Future<void> _handleDetect(BarcodeCapture capture) async {
    if (_processing ||
        _report != null ||
        _paddonReport != null ||
        _rawMaterialReport != null) {
      return;
    }
    final qrPayload = _extractQrPayload(_firstBarcodeValue(capture));
    if (qrPayload.isEmpty) {
      setState(() => _scanStatus = _QrScanStatus.invalidQr);
      return;
    }
    await _handleQrPayload(qrPayload);
  }

  Future<void> _handleQrPayload(String qrPayload) async {
    final normalized = qrPayload.trim();
    if (normalized.isEmpty) {
      if (mounted) {
        setState(() => _scanStatus = _QrScanStatus.invalidQr);
      }
      return;
    }
    if (widget.scanOnly) {
      if (mounted) {
        setState(() => _processing = true);
      }
      await _stopScanner();
      if (mounted) {
        Navigator.of(context).pop(normalized);
      }
      return;
    }
    await _lookupQrPayload(normalized);
  }

  Future<void> _lookupQrPayload(String qrPayload) async {
    if (_processing) {
      return;
    }
    final normalized = qrPayload.trim();
    if (normalized.isEmpty) {
      setState(() => _scanStatus = _QrScanStatus.invalidQr);
      return;
    }
    setState(() {
      _processing = true;
      _scanStatus = _QrScanStatus.loading;
      _scanErrorCode = null;
    });
    await _stopScanner();
    try {
      final report = await MobileApi.instance.adminProgressQrReport(normalized);
      if (!mounted) {
        return;
      }
      setState(() {
        _report = report;
        _processing = false;
        _scanStatus = _QrScanStatus.reportReady;
      });
    } catch (error) {
      if (_shouldTryPaddonLookup(normalized)) {
        try {
          final paddonReport = await MobileApi.instance.adminPaddonQrReport(
            normalized,
          );
          if (!mounted) {
            return;
          }
          setState(() {
            _paddonReport = paddonReport;
            _processing = false;
            _scanStatus = _QrScanStatus.paddonReady;
          });
          return;
        } catch (_) {
          // This five-digit QR may still belong to another flow.
        }
      }
      if (_shouldTryRawMaterialLookup(error)) {
        try {
          final rawReport = await MobileApi.instance.adminRawMaterialLookup(
            barcode: normalized,
          );
          if (!mounted) {
            return;
          }
          setState(() {
            _rawMaterialReport = rawReport;
            _processing = false;
            _scanStatus = _QrScanStatus.materialReady;
          });
          return;
        } catch (_) {
          // Show the original QR error below.
        }
      }
      if (!mounted) {
        return;
      }
      setState(() {
        _processing = false;
        _scanStatus = _QrScanStatus.error;
        _scanErrorCode = error is MobileApiException ? error.code : null;
      });
      await _startScanner();
    }
  }

  Future<void> _showManualQrDialog() async {
    final value = await showDialog<String>(
      context: context,
      builder: (context) {
        return AlertDialog(
          title: Text(
            context.l10n.productionText('worker.scanner.manual.title'),
          ),
          content: TextField(
            controller: _manualQrController,
            autofocus: true,
            decoration: InputDecoration(
              labelText: context.l10n.productionText(
                'worker.scanner.manual.payload',
              ),
              hintText: '4001...',
            ),
            textInputAction: TextInputAction.done,
            onSubmitted: (value) => Navigator.of(context).pop(value),
          ),
          actions: [
            TextButton(
              onPressed: () => Navigator.of(context).pop(),
              child: Text(context.l10n.productionText('worker.action.cancel')),
            ),
            FilledButton(
              onPressed: () =>
                  Navigator.of(context).pop(_manualQrController.text),
              child: Text(
                context.l10n.productionText('worker.scanner.manual.verify'),
              ),
            ),
          ],
        );
      },
    );
    if (value == null || !mounted) {
      return;
    }
    await _handleQrPayload(_extractQrPayload(value));
  }

  void _scanAgain() {
    setState(() {
      _report = null;
      _paddonReport = null;
      _rawMaterialReport = null;
      _scanErrorCode = null;
      _scanStatus = _QrScanStatus.prompt;
    });
    unawaited(_startScanner());
  }

  Future<void> _shareCurrentReport() async {
    if (_sharing) {
      return;
    }
    final report = _report;
    final rawMaterialReport = _rawMaterialReport;
    if (report == null && rawMaterialReport == null) {
      return;
    }
    setState(() => _sharing = true);
    try {
      final bytes = report != null
          ? AdminProgressQrScanPdf.buildProgress(
              report,
              l10n: context.l10n,
              apparatusNamesById: _apparatusNamesById,
            )
          : AdminProgressQrScanPdf.buildRawMaterial(
              rawMaterialReport!,
              l10n: context.l10n,
              apparatusNamesById: _apparatusNamesById,
            );
      final filename = report != null
          ? _qrPdfFilename(
              'admin-qr-report',
              report.order?.orderNumber.isNotEmpty == true
                  ? report.order!.orderNumber
                  : report.scannedBatch.batchId,
            )
          : _qrPdfFilename(
              'admin-material-report',
              rawMaterialReport!.barcode,
            );
      final box = context.findRenderObject() as RenderBox?;
      await SharePlus.instance.share(
        ShareParams(
          title: filename,
          subject: filename,
          files: [
            XFile.fromData(
              Uint8List.fromList(bytes),
              mimeType: 'application/pdf',
            ),
          ],
          fileNameOverrides: [filename],
          sharePositionOrigin:
              box == null ? null : box.localToGlobal(Offset.zero) & box.size,
        ),
      );
    } catch (_) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text(
              context.l10n.productionText('worker.scanner.pdf_error'),
            ),
          ),
        );
      }
    } finally {
      if (mounted) {
        setState(() => _sharing = false);
      }
    }
  }

  bool _shouldTryRawMaterialLookup(Object error) {
    if (error is! MobileApiException) {
      return false;
    }
    return error.code == 'progress_batch_not_found' ||
        error.code == 'progress_batch_not_accepted';
  }

  bool _shouldTryPaddonLookup(String qrPayload) {
    return RegExp(r'^\d{5}$').hasMatch(qrPayload.trim());
  }

  String _extractQrPayload(String rawValue) {
    final trimmed = rawValue.trim();
    if (trimmed.isEmpty) {
      return '';
    }
    final uri = Uri.tryParse(trimmed);
    if (uri != null &&
        (uri.scheme == 'http' || uri.scheme == 'https') &&
        uri.pathSegments.isNotEmpty) {
      final queryPayload = (uri.queryParameters['qr_payload'] ??
              uri.queryParameters['progress_qr'] ??
              uri.queryParameters['epc'] ??
              '')
          .trim();
      if (queryPayload.isNotEmpty) {
        return queryPayload;
      }
      return uri.pathSegments.last.trim();
    }
    return trimmed;
  }

  String _firstBarcodeValue(BarcodeCapture capture) {
    for (final barcode in capture.barcodes) {
      final rawValue = barcode.rawValue?.trim() ?? '';
      if (rawValue.isNotEmpty) {
        return rawValue;
      }
      final displayValue = barcode.displayValue?.trim() ?? '';
      if (displayValue.isNotEmpty) {
        return displayValue;
      }
    }
    return '';
  }
}
