// Generated by large_library_splitter.dart; keep changes in the source library.
part of 'admin_raw_material_rules_screen.dart';

class _RawMaterialGroupOptionCard extends StatelessWidget {
  const _RawMaterialGroupOptionCard({
    required this.slot,
    required this.option,
    required this.alternatives,
    required this.selected,
    required this.expanded,
    required this.selectedAlternatives,
    required this.onSelectedChanged,
    required this.onExpandedChanged,
    required this.onAlternativeChanged,
  });

  final M3SegmentVerticalSlot slot;
  final String option;
  final List<String> alternatives;
  final bool selected;
  final bool expanded;
  final Set<String> selectedAlternatives;
  final ValueChanged<bool> onSelectedChanged;
  final VoidCallback onExpandedChanged;
  final void Function(String alternative, bool value) onAlternativeChanged;

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final scheme = theme.colorScheme;
    return AppSegmentSurfaceCard(
      slot: slot,
      backgroundColor: scheme.surfaceContainerLowest,
      elevation: 4,
      shadowColor: scheme.shadow.withValues(alpha: 0.24),
      padding: EdgeInsets.zero,
      child: Column(
        children: [
          InkWell(
            onTap: () => onExpandedChanged(),
            child: Padding(
              padding: EdgeInsets.fromLTRB(14, 8, 4, expanded ? 8 : 8),
              child: ConstrainedBox(
                constraints: BoxConstraints(minHeight: expanded ? 0 : 45),
                child: Row(
                  children: [
                    Checkbox(
                      key: Key('raw-material-group-checkbox-$option'),
                      value: selected,
                      activeColor: scheme.primary,
                      onChanged: (value) => onSelectedChanged(value ?? false),
                    ),
                    Expanded(
                      child: Text(
                        option,
                        maxLines: expanded ? 2 : 1,
                        overflow: TextOverflow.ellipsis,
                        style: theme.textTheme.bodyLarge?.copyWith(
                          fontWeight: FontWeight.w600,
                        ),
                      ),
                    ),
                    IconButton(
                      key: Key('raw-material-group-expand-$option'),
                      tooltip: expanded
                          ? context.l10n.adminText('action.close')
                          : context.l10n.adminText('action.open'),
                      onPressed: onExpandedChanged,
                      icon: AnimatedRotation(
                        duration: const Duration(milliseconds: 160),
                        turns: expanded ? 0.5 : 0,
                        child: const Icon(Icons.keyboard_arrow_down_rounded),
                      ),
                    ),
                  ],
                ),
              ),
            ),
          ),
          AnimatedSize(
            duration: const Duration(milliseconds: 180),
            curve: Curves.easeOutCubic,
            child: expanded
                ? Padding(
                    padding: const EdgeInsets.fromLTRB(14, 0, 14, 14),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.stretch,
                      children: [
                        Text(
                          context.l10n.adminText('raw_material.alternatives'),
                          style: theme.textTheme.labelLarge?.copyWith(
                            color: scheme.onSurfaceVariant,
                            fontWeight: FontWeight.w700,
                          ),
                        ),
                        const SizedBox(height: 4),
                        if (alternatives.isEmpty)
                          Text(
                            context.l10n.adminText(
                              'raw_material.no_other_group',
                            ),
                            style: theme.textTheme.bodySmall?.copyWith(
                              color: scheme.onSurfaceVariant,
                            ),
                          )
                        else
                          for (final alternative in alternatives)
                            Padding(
                              padding: const EdgeInsets.only(bottom: 4),
                              child: CheckboxListTile(
                                key: Key(
                                  'raw-material-alternative-checkbox-$option-$alternative',
                                ),
                                value:
                                    selectedAlternatives.contains(alternative),
                                dense: true,
                                contentPadding: EdgeInsets.zero,
                                controlAffinity:
                                    ListTileControlAffinity.leading,
                                activeColor: scheme.primary,
                                title: Text(alternative),
                                onChanged: (value) => onAlternativeChanged(
                                  alternative,
                                  value ?? false,
                                ),
                              ),
                            ),
                      ],
                    ),
                  )
                : const SizedBox.shrink(),
          ),
        ],
      ),
    );
  }
}

class _RuleTile extends StatelessWidget {
  const _RuleTile({
    required this.slot,
    required this.rule,
    required this.apparatusName,
    required this.onTap,
  });

  final M3SegmentVerticalSlot slot;
  final AdminRawMaterialRule rule;
  final String apparatusName;
  final VoidCallback onTap;

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final scheme = theme.colorScheme;
    return AppSegmentSurfaceCard(
      slot: slot,
      backgroundColor: scheme.surfaceContainerLowest,
      elevation: 4,
      shadowColor: scheme.shadow.withValues(alpha: 0.24),
      padding: const EdgeInsets.fromLTRB(14, 10, 8, 10),
      onTap: onTap,
      child: Row(
        children: [
          SizedBox.square(
            dimension: 30,
            child: DecoratedBox(
              decoration: BoxDecoration(
                color: scheme.secondaryContainer,
                borderRadius: BorderRadius.circular(8),
              ),
              child: Icon(
                Icons.precision_manufacturing_rounded,
                size: 16,
                color: scheme.onSecondaryContainer,
              ),
            ),
          ),
          const SizedBox(width: 14),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  apparatusName,
                  maxLines: 1,
                  overflow: TextOverflow.ellipsis,
                  style: theme.textTheme.titleMedium?.copyWith(
                    fontWeight: FontWeight.w700,
                  ),
                ),
                const SizedBox(height: 4),
                Text(
                  rule.itemGroups.join(', '),
                  maxLines: 2,
                  overflow: TextOverflow.ellipsis,
                  style: theme.textTheme.bodySmall?.copyWith(
                    color: scheme.onSurfaceVariant,
                    height: 1.2,
                  ),
                ),
                const SizedBox(height: 2),
                Text(
                  rule.requiresMaterial
                      ? context.l10n.adminText('raw_material.mandatory')
                      : context.l10n.adminText('raw_material.optional'),
                  style: theme.textTheme.bodySmall?.copyWith(
                    color: scheme.onSurfaceVariant,
                    height: 1.05,
                  ),
                ),
                const SizedBox(height: 2),
                Text(
                  rule.startPolicy == AdminRawMaterialStartPolicy.stateAll
                      ? context.l10n.adminText('raw_material.state_all_scan')
                      : context.l10n.adminText(
                          'raw_material.each_group_scan',
                        ),
                  style: theme.textTheme.bodySmall?.copyWith(
                    color: scheme.onSurfaceVariant,
                    height: 1.05,
                  ),
                ),
              ],
            ),
          ),
          Icon(Icons.chevron_right_rounded, color: scheme.onSurfaceVariant),
        ],
      ),
    );
  }
}

class _RequiredMaterialsTab extends StatelessWidget {
  const _RequiredMaterialsTab({
    required this.apparatus,
    required this.rules,
    required this.saving,
    required this.bottomPadding,
    required this.onChanged,
  });

  final List<AdminApparatus> apparatus;
  final List<AdminRawMaterialRule> rules;
  final bool saving;
  final double bottomPadding;
  final void Function(AdminApparatus apparatus, bool requiresMaterial)
      onChanged;

  AdminRawMaterialRule? _ruleFor(AdminApparatus apparatus) {
    for (final rule in rules) {
      if (rule.apparatusId == apparatus.id) {
        return rule;
      }
    }
    return null;
  }

  @override
  Widget build(BuildContext context) {
    return ListView.builder(
      padding: EdgeInsets.fromLTRB(12, 10, 12, bottomPadding),
      itemCount: apparatus.length,
      itemBuilder: (context, index) {
        final item = apparatus[index];
        final rule = _ruleFor(item);
        final hasRule = rule != null && rule.itemGroups.isNotEmpty;
        return Padding(
          padding: const EdgeInsets.only(bottom: 8),
          child: _RequiredMaterialTile(
            apparatus: item,
            rule: rule,
            enabled: hasRule && !saving,
            onChanged: onChanged,
          ),
        );
      },
    );
  }
}

class _RequiredMaterialTile extends StatelessWidget {
  const _RequiredMaterialTile({
    required this.apparatus,
    required this.rule,
    required this.enabled,
    required this.onChanged,
  });

  final AdminApparatus apparatus;
  final AdminRawMaterialRule? rule;
  final bool enabled;
  final void Function(AdminApparatus apparatus, bool requiresMaterial)
      onChanged;

  @override
  Widget build(BuildContext context) {
    final scheme = Theme.of(context).colorScheme;
    final groups = rule?.itemGroups.join(', ') ?? '';
    return Material(
      color: scheme.surfaceContainerLowest,
      elevation: 4,
      shadowColor: scheme.shadow.withValues(alpha: 0.24),
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(8),
        side: BorderSide(color: scheme.outlineVariant),
      ),
      surfaceTintColor: Colors.transparent,
      clipBehavior: Clip.antiAlias,
      child: SwitchListTile(
        value: rule?.requiresMaterial ?? false,
        onChanged: enabled ? (value) => onChanged(apparatus, value) : null,
        secondary: const Icon(Icons.fact_check_rounded),
        title: Text(apparatus.name.trim()),
        subtitle: Text(
          groups.isEmpty
              ? context.l10n.adminText(
                  'raw_material.select_group_first',
                )
              : groups,
        ),
      ),
    );
  }
}
