// Generated by large_library_splitter.dart; keep changes in the source library.
part of 'admin_production_map_orders_screen.dart';

class _ReadOnlyOrderDetailContent extends StatelessWidget {
  const _ReadOnlyOrderDetailContent({
    required this.noticeAnchorKey,
    required this.onClose,
    required this.map,
    required this.apparatusCatalog,
    required this.baseMetraj,
    required this.orderKg,
    required this.customerName,
    required this.steps,
    required this.uiState,
    required this.showContractWarning,
    required this.pauseLabel,
    required this.queueStates,
    required this.queueStatesByApparatus,
    required this.stageStates,
    required this.materialsLoading,
    required this.materialsError,
    required this.materialStartReady,
    required this.materialStartBlockingText,
    required this.actionInFlight,
    required this.materialIntakeInFlight,
    required this.materialIntakeMode,
    required this.intakeCandidatesExpanded,
    required this.onToggleIntakeCandidatesExpanded,
    required this.previousProgressBatch,
    required this.openingWipBatch,
    required this.openingWipBatches,
    required this.inputProgressBatches,
    required this.inputProgressLoading,
    required this.inputProgressError,
    required this.quickScanStatus,
    required this.quickScanInFlight,
    required this.showQuickScanner,
    required this.allowConcurrentQuickScanner,
    required this.onQuickScan,
    required this.summaryExpanded,
    required this.onToggleSummaryExpanded,
    required this.requiresQolipScan,
    required this.qolipScanned,
    required this.qolipCodes,
    required this.requiredQolips,
    required this.qolipRequirementsStatusText,
    required this.startMaterialsExpanded,
    required this.onToggleStartMaterialsExpanded,
    required this.materialsExpanded,
    required this.onToggleMaterialsExpanded,
    required this.qolipsExpanded,
    required this.onToggleQolipsExpanded,
    required this.mapExpanded,
    required this.onToggleMapExpanded,
    required this.onTapMapApparatus,
    required this.onMaterialIntake,
    required this.onStart,
    required this.onPause,
    required this.onRollComplete,
    required this.onComplete,
    required this.onResume,
    required this.orderControlState,
    required this.allowMaterialUnlink,
    required this.onUnlinkMaterial,
    required this.unlinkingMaterialBarcode,
  });

  final GlobalKey noticeAnchorKey;
  final VoidCallback onClose;
  final ProductionMapDefinition map;
  final List<AdminApparatus> apparatusCatalog;
  final double? baseMetraj;
  final double? orderKg;
  final String? customerName;
  final List<ProductionMapNode> steps;
  final _ReadOnlyOrderDetailUiState uiState;
  final bool showContractWarning;
  final String pauseLabel;
  final Map<String, String> queueStates;
  final Map<String, Map<String, String>> queueStatesByApparatus;
  final Map<String, String> stageStates;
  final bool materialsLoading;
  final String materialsError;
  final bool materialStartReady;
  final String materialStartBlockingText;
  final bool actionInFlight;
  final bool materialIntakeInFlight;
  final bool materialIntakeMode;
  final bool intakeCandidatesExpanded;
  final VoidCallback onToggleIntakeCandidatesExpanded;
  final AdminProgressBatch? previousProgressBatch;
  final AdminOpeningWipBatch? openingWipBatch;
  final List<AdminOpeningWipBatch> openingWipBatches;
  final List<AdminProgressBatch> inputProgressBatches;
  final bool inputProgressLoading;
  final String inputProgressError;
  final String quickScanStatus;
  final bool quickScanInFlight;
  final bool showQuickScanner;
  final bool allowConcurrentQuickScanner;
  final Future<void> Function(String rawValue) onQuickScan;
  final bool summaryExpanded;
  final VoidCallback onToggleSummaryExpanded;
  final bool requiresQolipScan;
  final bool qolipScanned;
  final List<String> qolipCodes;
  final List<AdminProductionMapRequiredQolip> requiredQolips;
  final String qolipRequirementsStatusText;
  final bool startMaterialsExpanded;
  final VoidCallback onToggleStartMaterialsExpanded;
  final bool materialsExpanded;
  final VoidCallback onToggleMaterialsExpanded;
  final bool qolipsExpanded;
  final VoidCallback onToggleQolipsExpanded;
  final bool mapExpanded;
  final VoidCallback onToggleMapExpanded;
  final ValueChanged<ProductionMapNode> onTapMapApparatus;
  final VoidCallback onMaterialIntake;
  final VoidCallback onStart;
  final VoidCallback onPause;
  final VoidCallback onRollComplete;
  final VoidCallback onComplete;
  final VoidCallback onResume;
  final AdminOrderControlState orderControlState;
  final bool allowMaterialUnlink;
  final void Function(AdminRawMaterialAssignment assignment)? onUnlinkMaterial;
  final String unlinkingMaterialBarcode;

  @override
  Widget build(BuildContext context) {
    final scheme = Theme.of(context).colorScheme;
    final rezkaInstructionLines = _rezkaWipSplitInstructionLines(
      map: map,
      station: uiState.station,
      stageNodeId: uiState.stageNodeId,
      outputKadrCounts: uiState.rezkaOutputKadrCounts,
      l10n: context.l10n,
    );
    return DraggableScrollableSheet(
      expand: false,
      initialChildSize: 0.86,
      minChildSize: 0.86,
      maxChildSize: 0.86,
      builder: (context, controller) {
        return ColoredBox(
          key: noticeAnchorKey,
          color: scheme.surfaceContainerHighest,
          child: Stack(
            children: [
              ListView(
                controller: controller,
                padding: const EdgeInsets.fromLTRB(4, 56, 4, 24),
                children: [
                  AnimatedSize(
                    key:
                        const ValueKey('production-order-quick-scanner-motion'),
                    duration: AppMotion.medium,
                    curve: AppMotion.standardDecelerate,
                    alignment: Alignment.topCenter,
                    child: AnimatedSwitcher(
                      duration: AppMotion.medium,
                      switchInCurve: AppMotion.standardDecelerate,
                      switchOutCurve: AppMotion.standardAccelerate,
                      transitionBuilder: (child, animation) => FadeTransition(
                        opacity: animation,
                        child: SizeTransition(
                          sizeFactor: animation,
                          axisAlignment: -1,
                          child: child,
                        ),
                      ),
                      child: showQuickScanner
                          ? Column(
                              key: const ValueKey(
                                'production-order-quick-scanner-visible',
                              ),
                              children: [
                                ProductionQuickScannerPanel(
                                  statusText: quickScanStatus,
                                  busy: quickScanInFlight,
                                  allowConcurrentDetections:
                                      allowConcurrentQuickScanner,
                                  allowManualEntry: !uiState.openingWipRequired,
                                  onCodeDetected: onQuickScan,
                                ),
                                const SizedBox(height: 10),
                              ],
                            )
                          : const SizedBox(
                              key: ValueKey(
                                'production-order-quick-scanner-hidden',
                              ),
                            ),
                    ),
                  ),
                  _OrderStartUnifiedCard(
                    apparatusCatalog: apparatusCatalog,
                    orderCode: _openedOrderDisplayCode(map),
                    productTitle: _openedOrderPrimaryTitle(
                      map,
                      l10n: context.l10n,
                    ),
                    customerName: customerName,
                    contractSynchronized: uiState.contractSynchronized,
                    showContractWarning: showContractWarning,
                    blockingReasonCode: uiState.blockingReasonCode,
                    showBackendBlockingState: uiState.showBackendBlockingState,
                    startAssignments: uiState.materialAssignments,
                    intakeCandidateAssignments:
                        uiState.intakeCandidateAssignments,
                    assignedAssignments: uiState.assignedMaterialAssignments,
                    showStartMaterials: uiState.showStartMaterials,
                    showIntakeCandidates: uiState.showIntakeCandidates,
                    materialIntakeAllowed: uiState.materialIntakeAllowed,
                    materialsLoading: materialsLoading,
                    materialsError: materialsError,
                    materialStartReady: materialStartReady,
                    materialStartBlockingText: materialStartBlockingText,
                    scannedBarcodes: uiState.confirmedMaterialBarcodes,
                    scannedCount: uiState.scannedCount,
                    requiredCount: uiState.materialRequiredCount,
                    showStart: uiState.showStart,
                    allMaterialsScanned: uiState.allMaterialsScanned,
                    actionInFlight: actionInFlight,
                    materialIntakeInFlight: materialIntakeInFlight,
                    materialIntakeMode: materialIntakeMode,
                    intakeCandidatesExpanded: intakeCandidatesExpanded,
                    onToggleIntakeCandidatesExpanded:
                        onToggleIntakeCandidatesExpanded,
                    showPause: uiState.showPause,
                    pauseLabel: pauseLabel,
                    showRollComplete: uiState.showRollComplete,
                    showComplete: uiState.showComplete,
                    showResume: uiState.showResume,
                    showWaitingForPrevious: uiState.showWaitingForPrevious,
                    showWaitingForSequence: uiState.showWaitingForSequence,
                    previousStage: uiState.previousStage,
                    openingWipRequired: uiState.openingWipRequired,
                    previousProgressRequired: uiState.previousProgressRequired,
                    previousProgressReady: uiState.previousProgressReady,
                    previousProgressBatch: previousProgressBatch,
                    openingWipBatch: openingWipBatch,
                    openingWipBatches: openingWipBatches,
                    inputProgressBatches: inputProgressBatches,
                    inputProgressLoading: inputProgressLoading,
                    inputProgressError: inputProgressError,
                    requiresQolipScan: requiresQolipScan,
                    qolipScanned: qolipScanned,
                    qolipCodes: qolipCodes,
                    requiredQolips: requiredQolips,
                    qolipRequirementsStatusText: qolipRequirementsStatusText,
                    startMaterialsExpanded: startMaterialsExpanded,
                    onToggleStartMaterialsExpanded:
                        onToggleStartMaterialsExpanded,
                    materialsExpanded: materialsExpanded,
                    onToggleMaterialsExpanded: onToggleMaterialsExpanded,
                    qolipsExpanded: qolipsExpanded,
                    onToggleQolipsExpanded: onToggleQolipsExpanded,
                    rezkaInstructionLines: rezkaInstructionLines,
                    onMaterialIntake: onMaterialIntake,
                    onStart: onStart,
                    onPause: onPause,
                    onRollComplete: onRollComplete,
                    onComplete: onComplete,
                    onResume: onResume,
                    orderControlState: orderControlState,
                    allowMaterialUnlink: allowMaterialUnlink,
                    onUnlinkMaterial: onUnlinkMaterial,
                    unlinkingMaterialBarcode: unlinkingMaterialBarcode,
                  ),
                  const SizedBox(height: 10),
                  _OrderSummaryCard(
                    map: map,
                    baseMetraj: baseMetraj,
                    orderKg: orderKg,
                    expanded: summaryExpanded,
                    onToggleExpanded: onToggleSummaryExpanded,
                  ),
                  const SizedBox(height: 10),
                  _OrderMapProgressCard(
                    steps: steps,
                    apparatusCatalog: apparatusCatalog,
                    orderId: uiState.orderId,
                    currentStation: uiState.station,
                    queueStates: queueStates,
                    queueStatesByApparatus: queueStatesByApparatus,
                    stageStates: stageStates,
                    currentStageNodeId: uiState.stageNodeId,
                    expanded: mapExpanded,
                    onToggleExpanded: onToggleMapExpanded,
                    onTapApparatus: onTapMapApparatus,
                  ),
                ],
              ),
              Positioned(
                top: 4,
                right: 4,
                child: IconButton.filledTonal(
                  key: const ValueKey('production-order-detail-close'),
                  tooltip: context.l10n.productionText('worker.action.close'),
                  onPressed: onClose,
                  icon: const Icon(Icons.close_rounded),
                ),
              ),
            ],
          ),
        );
      },
    );
  }
}
