// Generated by large_library_splitter.dart; keep changes in the source library.
part of 'admin_calculate_materials_screen.dart';

class AdminCalculateMaterialsScreen extends StatefulWidget {
  const AdminCalculateMaterialsScreen({super.key});

  @override
  State<AdminCalculateMaterialsScreen> createState() =>
      _AdminCalculateMaterialsScreenState();
}

class _AdminCalculateMaterialsScreenState
    extends State<AdminCalculateMaterialsScreen> {
  List<CalculateMaterial> _materials = const [];
  bool _loading = true;
  bool _saving = false;
  String _error = '';

  @override
  void initState() {
    super.initState();
    _load();
  }

  Future<void> _load() async {
    if (mounted) {
      setState(() {
        _loading = true;
        _error = '';
      });
    }
    try {
      final materials = await MobileApi.instance.calculateMaterials();
      if (!mounted) return;
      setState(() {
        _materials = materials;
        _loading = false;
      });
    } catch (error) {
      if (!mounted) return;
      setState(() {
        _loading = false;
        _error = _materialError(error, context.l10n);
      });
    }
  }

  Future<void> _edit([CalculateMaterial? material]) async {
    final draft = await showModalBottomSheet<CalculateMaterial>(
      context: context,
      isScrollControlled: true,
      useSafeArea: true,
      backgroundColor: Theme.of(context).colorScheme.surface,
      builder: (context) => _CalculateMaterialEditor(material: material),
    );
    if (draft == null || !mounted) return;
    setState(() => _saving = true);
    try {
      final saved = await MobileApi.instance.upsertCalculateMaterial(draft);
      if (!mounted) return;
      setState(() {
        final updated = [..._materials];
        final index = updated.indexWhere((material) => material.id == saved.id);
        if (index < 0) {
          updated.add(saved);
        } else if (!saved.active && updated[index].active) {
          updated.removeAt(index);
          updated.add(saved);
        } else {
          updated[index] = saved;
        }
        _materials = [
          ...updated.where((material) => material.active),
          ...updated.where((material) => !material.active),
        ];
      });
      final materials = await MobileApi.instance.calculateMaterials();
      if (!mounted) return;
      setState(() {
        _materials = materials;
      });
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text(context.l10n.adminText('material.saved')),
        ),
      );
    } catch (error) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text(_materialError(error, context.l10n))),
        );
      }
    } finally {
      if (mounted) setState(() => _saving = false);
    }
  }

  Future<void> _reorder(int oldIndex, int newIndex) async {
    if (_saving || oldIndex == newIndex) return;
    final active = _materials.where((material) => material.active).toList();
    if (oldIndex < 0 ||
        oldIndex >= active.length ||
        newIndex < 0 ||
        newIndex >= active.length) return;
    final previous = _materials;
    active.insert(newIndex, active.removeAt(oldIndex));
    setState(() {
      _saving = true;
      _materials = [
        ...active,
        ...previous.where((material) => !material.active),
      ];
    });
    try {
      final saved = await MobileApi.instance.reorderCalculateMaterials(
        active.map((material) => material.id).toList(growable: false),
      );
      if (mounted) setState(() => _materials = saved);
    } catch (error) {
      if (!mounted) return;
      setState(() => _materials = previous);
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text(_materialError(error, context.l10n))),
      );
      await _load();
    } finally {
      if (mounted) setState(() => _saving = false);
    }
  }

  void _openDrawerRoute(String routeName) {
    AdminDrawerNavigation.openRoute(context, routeName);
  }

  @override
  Widget build(BuildContext context) {
    final scheme = Theme.of(context).colorScheme;
    return AppShell(
      drawer: AdminNavigationDrawer(
        selectedIndex: 0,
        selectedRouteName: AppRoutes.adminCalculateMaterials,
        onNavigate: _openDrawerRoute,
      ),
      title: context.l10n.adminText('material.title'),
      subtitle: '',
      nativeTopBar: true,
      nativeTitleTextStyle: AppTheme.werkaNativeAppBarTitleStyle(context),
      bottom: AdminDock(
        activeTab: AdminDockTab.home,
        primaryFabActions: [
          AdminFabMenuAction(
            title: context.l10n.adminText('material.add'),
            icon: Icons.add_box_outlined,
            enabled: !_saving,
            onTap: () => _edit(),
          ),
        ],
      ),
      bottomDockFadeStrength: null,
      contentPadding: EdgeInsets.zero,
      child: ColoredBox(
        color: scheme.surfaceContainerLow,
        child: _body(context),
      ),
    );
  }

  Widget _body(BuildContext context) {
    if (_loading) {
      return const Center(child: CircularProgressIndicator.adaptive());
    }
    if (_error.isNotEmpty) {
      return Center(
        child: Padding(
          padding: const EdgeInsets.all(24),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              Text(_error, textAlign: TextAlign.center),
              const SizedBox(height: 12),
              FilledButton.icon(
                onPressed: _load,
                icon: const Icon(Icons.refresh_rounded),
                label: Text(context.l10n.adminText('action.retry')),
              ),
            ],
          ),
        ),
      );
    }
    final scheme = Theme.of(context).colorScheme;
    final activeCount = _materials.where((material) => material.active).length;
    return M3SequenceList(
      key: const ValueKey('material-sequence-list'),
      padding: EdgeInsets.fromLTRB(
        4,
        12,
        4,
        MediaQuery.paddingOf(context).bottom + 160,
      ),
      header: Padding(
        padding: const EdgeInsets.only(bottom: 12),
        child: Text(
          context.l10n.adminText('material.description'),
          style: Theme.of(context).textTheme.bodyMedium?.copyWith(
                color: scheme.onSurfaceVariant,
              ),
        ),
      ),
      itemCount: _materials.isEmpty ? 1 : _materials.length,
      reorderableItemCount: activeCount,
      itemKey: (index) => ValueKey(
        _materials.isEmpty
            ? 'material-empty'
            : 'material-${_materials[index].id}',
      ),
      onReorder: _reorder,
      itemBuilder: (context, index) {
        if (_materials.isEmpty) {
          return Padding(
            padding: const EdgeInsets.all(24),
            child:
                Center(child: Text(context.l10n.adminText('material.empty'))),
          );
        }
        final material = _materials[index];
        final slot = M3SegmentedListGeometry.standaloneListSlotForIndex(
          index,
          _materials.length,
        );
        return M3SegmentFilledSurface(
          slot: slot,
          cornerRadius: M3SegmentedListGeometry.cornerRadiusForSlot(slot),
          onTap: _saving ? null : () => _edit(material),
          child: Padding(
            padding: const EdgeInsetsDirectional.fromSTEB(14, 8, 4, 8),
            child: ConstrainedBox(
              constraints: const BoxConstraints(minHeight: 45),
              child: Row(
                children: [
                  Expanded(
                    child: Text(
                      material.name,
                      style: Theme.of(context).textTheme.titleMedium?.copyWith(
                            fontWeight: FontWeight.w700,
                            color: material.active
                                ? scheme.onSurface
                                : scheme.onSurfaceVariant,
                          ),
                    ),
                  ),
                  if (material.active)
                    M3SequenceDragHandle(index: index, enabled: !_saving)
                  else
                    Padding(
                      padding: const EdgeInsets.all(8),
                      child: Icon(Icons.visibility_off_outlined,
                          color: scheme.onSurfaceVariant),
                    ),
                ],
              ),
            ),
          ),
        );
      },
    );
  }
}

class _CalculateMaterialEditor extends StatefulWidget {
  const _CalculateMaterialEditor({this.material});

  final CalculateMaterial? material;

  @override
  State<_CalculateMaterialEditor> createState() =>
      _CalculateMaterialEditorState();
}

class _CalculateMaterialEditorState extends State<_CalculateMaterialEditor> {
  final _formKey = GlobalKey<FormState>();
  late final TextEditingController _name;
  late final TextEditingController _density;
  late bool _active;
  late List<_VariantControllers> _variants;
  String _variantError = '';

  @override
  void initState() {
    super.initState();
    final material = widget.material;
    _name = TextEditingController(text: material?.name ?? '');
    _density = TextEditingController(
      text: material == null || material.densityGCm3 <= 0
          ? ''
          : _numberText(material.densityGCm3),
    );
    _active = material?.active ?? true;
    _variants =
        material?.variants.map(_VariantControllers.fromVariant).toList() ??
            <_VariantControllers>[];
  }

  @override
  void dispose() {
    _name.dispose();
    _density.dispose();
    for (final variant in _variants) {
      variant.dispose();
    }
    super.dispose();
  }

  void _addVariant() => setState(() => _variants.add(_VariantControllers()));

  void _removeVariant(int index) {
    if (_variants.length == 1) return;
    setState(() => _variants.removeAt(index).dispose());
  }

  void _save() {
    if (!_formKey.currentState!.validate()) return;
    final density = _decimal(_density.text) ?? 0;
    final variants = <CalculateMaterialVariant>[];
    final seenMicrons = <int>{};
    for (final variant in _variants) {
      final micronText = variant.micron.text.trim();
      final actualGsmText = variant.actualGsm.text.trim();
      if (micronText.isEmpty && actualGsmText.isEmpty) {
        continue;
      }
      final micron = int.tryParse(micronText);
      final actualGsm = _optionalDecimal(variant.actualGsm.text);
      if (micron == null || micron <= 0 || !seenMicrons.add(micron)) {
        setState(
          () => _variantError = context.l10n.adminText(
            'material.validation_microns',
          ),
        );
        return;
      }
      if (density <= 0 && actualGsm == null) {
        setState(
          () => _variantError =
              context.l10n.adminText('material.validation_actual_gsm'),
        );
        return;
      }
      final gsm = actualGsm ?? micron * density;
      variants.add(
        CalculateMaterialVariant(
          micron: micron,
          coefficient: gsm * 0.06,
          actualGsm: actualGsm,
        ),
      );
    }
    if (density <= 0 && variants.isEmpty) {
      setState(
        () => _variantError =
            context.l10n.adminText('material.validation_actual_gsm'),
      );
      return;
    }
    variants.sort((left, right) => left.micron.compareTo(right.micron));
    Navigator.of(context).pop(
      CalculateMaterial(
        id: widget.material?.id ?? '',
        name: _name.text.trim(),
        active: _active,
        densityGCm3: density,
        variants: variants,
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: EdgeInsets.fromLTRB(
        16,
        12,
        16,
        16 + MediaQuery.viewInsetsOf(context).bottom,
      ),
      child: Form(
        key: _formKey,
        child: SingleChildScrollView(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              Row(
                children: [
                  Expanded(
                    child: Text(
                      widget.material == null
                          ? context.l10n.adminText('material.add')
                          : context.l10n.adminText('material.edit'),
                      style: Theme.of(context).textTheme.titleLarge?.copyWith(
                            fontWeight: FontWeight.w800,
                          ),
                    ),
                  ),
                  IconButton(
                    onPressed: () => Navigator.of(context).pop(),
                    icon: const Icon(Icons.close_rounded),
                  ),
                ],
              ),
              TextFormField(
                controller: _name,
                decoration: appSurfaceInputDecoration(
                  context,
                  labelText: context.l10n.adminText('material.name'),
                ),
                validator: (value) => value == null || value.trim().isEmpty
                    ? context.l10n.adminText(
                        'material.validation_required',
                      )
                    : null,
              ),
              const SizedBox(height: 10),
              TextFormField(
                controller: _density,
                keyboardType:
                    const TextInputType.numberWithOptions(decimal: true),
                inputFormatters: [_decimalFormatter],
                decoration: appSurfaceInputDecoration(
                  context,
                  labelText: context.l10n.adminText('material.density'),
                  suffixText: 'g/cm³',
                  hintText: context.l10n.adminText('material.density_hint'),
                ),
                validator: (value) {
                  if (value == null || value.trim().isEmpty) return null;
                  final density = _decimal(value);
                  return density == null || density <= 0
                      ? context.l10n.adminText('material.validation_invalid')
                      : null;
                },
              ),
              SwitchListTile.adaptive(
                contentPadding: EdgeInsets.zero,
                value: _active,
                onChanged: (value) => setState(() => _active = value),
                title: Text(
                  context.l10n.adminText('material.show_in_picker'),
                ),
              ),
              Text(
                context.l10n.adminText('material.microns'),
                style: Theme.of(context).textTheme.titleMedium?.copyWith(
                      fontWeight: FontWeight.w800,
                    ),
              ),
              const SizedBox(height: 4),
              Text(
                context.l10n.adminText('material.actual_gsm_note'),
                style: Theme.of(context).textTheme.bodySmall?.copyWith(
                      color: Theme.of(context).colorScheme.onSurfaceVariant,
                    ),
              ),
              const SizedBox(height: 10),
              for (var index = 0; index < _variants.length; index++) ...[
                if (index > 0) const SizedBox(height: 10),
                _VariantRow(
                  variant: _variants[index],
                  onRemove: _variants.length == 1
                      ? null
                      : () => _removeVariant(index),
                ),
              ],
              if (_variantError.isNotEmpty)
                Padding(
                  padding: const EdgeInsets.only(top: 8),
                  child: Text(
                    _variantError,
                    style: TextStyle(
                      color: Theme.of(context).colorScheme.error,
                    ),
                  ),
                ),
              const SizedBox(height: 10),
              OutlinedButton.icon(
                onPressed: _addVariant,
                icon: const Icon(Icons.add_rounded),
                label: Text(context.l10n.adminText('material.add_micron')),
              ),
              const SizedBox(height: 12),
              FilledButton(
                onPressed: _save,
                child: Text(context.l10n.adminText('action.save')),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
