// Generated by large_library_splitter.dart; keep changes in the source library.
part of 'admin_roles_screen.dart';

String _roleDefinitionLabel(BuildContext context, AdminRoleDefinition role) {
  if (!role.system) {
    return role.label;
  }
  return context.l10n.systemRoleLabel(role.id, role.label);
}

String _roleDefinitionSummary(AppLocalizations l10n, AdminRoleDefinition role) {
  final baseRole = role.baseRole;
  if (baseRole == null) {
    return l10n.adminRoleKindLabel(role.system);
  }
  return '${l10n.roleLabelForCode(userRoleToJson(baseRole))} • ${l10n.adminRoleKindLabel(role.system)}';
}

bool _roleCanAssignToPrincipal(
  AdminRoleDefinition role,
  _RolePrincipal principal,
) {
  if (!role.system) {
    return true;
  }
  if (role.id == 'aparatchi') {
    return principal.role == UserRole.customer ||
        principal.role == UserRole.aparatchi;
  }
  if (role.id == 'qolipchi') {
    return principal.role == UserRole.qolipchi ||
        principal.role == UserRole.aparatchi;
  }
  if (role.id == 'boyoqchi') {
    return principal.role == UserRole.boyoqchi;
  }
  if (role.baseRole == null) {
    return true;
  }
  return role.baseRole == principal.role;
}

bool _roleNeedsApparatus(AdminRoleDefinition role) {
  return role.capabilityCodes.contains('apparatus.queue.read');
}

String _roleAssignmentSubtitle(
  AppLocalizations l10n,
  AdminRoleDefinition role,
) {
  final baseRole = role.baseRole;
  if (baseRole == null) {
    return l10n.adminRoleKindLabel(role.system);
  }
  return l10n.roleLabelForCode(userRoleToJson(baseRole));
}

String _capabilityLabel(
  AppLocalizations l10n,
  String code,
  List<AdminCapability> capabilities,
) {
  final fallback = capabilities
          .where((capability) => capability.code == code)
          .map((capability) => capability.label)
          .letFirstOrNull() ??
      code;
  return l10n.adminCapabilityLabel(code, fallback);
}

extension _FirstOrNull<T> on Iterable<T> {
  T? letFirstOrNull() {
    final iterator = this.iterator;
    if (!iterator.moveNext()) {
      return null;
    }
    return iterator.current;
  }
}
