import '../../../app/app_router.dart';
import '../../../core/api/mobile_api.dart';
import '../../../core/formatters/quantity_formatters.dart';
import '../../../core/localization/app_localizations.dart';
import '../../../core/print_service.dart';
import '../../../core/search/search_normalizer.dart';
import '../../../core/session/session.dart';
import '../../../core/test_mode/test_mode_controller.dart';
import '../../../core/theme/app_theme.dart';
import '../../../core/widgets/forms/forms.dart';
import '../../../core/widgets/feedback/m3_confirm_dialog.dart';
import '../../../core/widgets/feedback/rps_qr_reprint_sheet.dart';
import '../../../core/widgets/lists/m3_segmented_list.dart';
import '../../../core/widgets/shell/app_loading_indicator.dart';
import '../../../core/widgets/shell/app_retry_state.dart';
import '../../../core/widgets/shell/app_shell.dart';
import '../../material_taminotchi/presentation/widgets/material_taminotchi_dock.dart';
import '../../material_taminotchi/presentation/widgets/material_taminotchi_navigation_drawer.dart';
import '../../material_taminotchi/presentation/widgets/material_state_locations_tab.dart';
import '../../shared/models/app_models.dart';
import '../../shared/models/inventory_movement_models.dart';
import '../../werka/presentation/widgets/m3_picker_sheet.dart';
import '../logic/canonical_apparatus_display.dart';
import '../state/admin_warehouse_filter_store.dart';
import 'widgets/admin_dock.dart';
import 'widgets/admin_create_hub_sheet.dart';
import 'widgets/admin_catalog_search_field.dart';
import 'widgets/admin_navigation_drawer.dart';
import 'widgets/admin_summary_card.dart';
import 'widgets/admin_drawer_navigation.dart';
import 'widgets/admin_expandable_filter_chip.dart';
import 'widgets/admin_surface_tab_bar.dart';
import 'dart:async';
import 'package:flutter/material.dart';

part 'admin_warehouses_screen__AdminWarehousesScreenState_methods_01.dart';
part 'admin_warehouses_screen__WarehouseDetailsTabState_methods_02.dart';
part 'admin_warehouses_screen__WarehouseSettingsTabState_methods_03.dart';
part 'admin_warehouses_screen_widgets_part_01.dart';
part 'admin_warehouses_screen_declarations_part_02.dart';
part 'admin_warehouses_screen_declarations_part_03.dart';
part 'admin_warehouses_screen_models_part_04.dart';
part 'admin_warehouses_screen_helpers_part_05.dart';
part 'admin_warehouses_screen_models_resplit_part_01.dart';
part 'admin_warehouses_screen_models_resplit_part_02.dart';
part 'admin_warehouses_screen_models_resplit_part_03.dart';

const Duration _warehouseLiveReconnectInterval = Duration(seconds: 5);
const Duration _warehouseLiveRefreshDebounce = Duration(milliseconds: 250);

const int _warehouseAssigneePageSize = 50;
