// Generated by large_library_splitter.dart; keep changes in the source library.
part of 'admin_supplier_detail_screen.dart';

class AdminSupplierDetailScreen extends StatefulWidget {
  const AdminSupplierDetailScreen({
    super.key,
    required this.supplierRef,
    this.readOnly = false,
    this.chatTarget,
  });

  final String supplierRef;
  final bool readOnly;
  final ChatDirectoryEntry? chatTarget;

  @override
  State<AdminSupplierDetailScreen> createState() =>
      _AdminSupplierDetailScreenState();
}

class _AdminSupplierDetailScreenState extends State<AdminSupplierDetailScreen> {
  late Future<AdminSupplierDetail> _detailFuture;
  bool _savingStatus = false;
  bool _savingPhone = false;
  bool _regeneratingCode = false;
  bool _removing = false;
  bool _adminPanelExpanded = false;
  bool _changed = false;
  late final RetryAfterCountdown _retryAfter;
  int get _retryAfterSec => _retryAfter.seconds;

  @override
  void initState() {
    super.initState();
    _retryAfter = RetryAfterCountdown(onChanged: _refreshRetryAfter);
    _detailFuture = _loadDetail();
  }

  @override
  void dispose() {
    _retryAfter.dispose();
    super.dispose();
  }

  Future<AdminSupplierDetail> _loadDetail() async {
    final detail = await MobileApi.instance.adminSupplierDetail(
      widget.supplierRef,
    );
    _setRetryAfter(detail.codeRetryAfterSec);
    return detail;
  }

  void _refreshRetryAfter() {
    if (mounted) {
      setState(() {});
    }
  }

  void _setRetryAfter(int seconds) => _retryAfter.set(seconds);

  Future<void> _reload() async {
    final future = _loadDetail();
    setState(() {
      _detailFuture = future;
    });
    await future;
  }

  Future<void> _toggleBlocked(AdminSupplierDetail detail) async {
    setState(() => _savingStatus = true);
    try {
      final updated = await MobileApi.instance.adminSetSupplierBlocked(
        ref: detail.ref,
        blocked: !detail.blocked,
      );
      _changed = true;
      setState(() {
        _detailFuture = Future<AdminSupplierDetail>.value(updated);
      });
    } finally {
      if (mounted) {
        setState(() => _savingStatus = false);
      }
    }
  }

  Future<void> _savePhone(AdminSupplierDetail detail, String phone) async {
    final trimmedPhone = phone.trim();
    if (trimmedPhone.isEmpty) {
      return;
    }

    setState(() => _savingPhone = true);
    try {
      final updated = await MobileApi.instance.adminUpdateSupplierPhone(
        ref: detail.ref,
        phone: trimmedPhone,
      );
      _changed = true;
      setState(() {
        _detailFuture = Future<AdminSupplierDetail>.value(updated);
      });
    } catch (error) {
      if (!mounted) {
        return;
      }
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text(
            context.l10n.adminText(
              'detail.phone_save_failed',
              values: {'error': error},
            ),
          ),
        ),
      );
    } finally {
      if (mounted) {
        setState(() => _savingPhone = false);
      }
    }
  }

  Future<void> _regenerateCode() async {
    setState(() => _regeneratingCode = true);
    try {
      final updated = await MobileApi.instance.adminRegenerateSupplierCode(
        widget.supplierRef,
      );
      _setRetryAfter(updated.codeRetryAfterSec);
      _changed = true;
      setState(() {
        _detailFuture = Future<AdminSupplierDetail>.value(updated);
      });
    } finally {
      if (mounted) {
        setState(() => _regeneratingCode = false);
      }
    }
  }

  Future<void> _removeSupplier() async {
    final bool? confirmed = await showM3ConfirmDialog(
      context: context,
      title: context.l10n.adminText('detail.supplier_remove_title'),
      message: context.l10n.adminText('detail.supplier_remove_message'),
      cancelLabel: context.l10n.adminText('action.cancel'),
      confirmLabel: context.l10n.adminText('detail.customer_remove'),
      destructive: true,
    );
    if (confirmed != true) {
      return;
    }

    setState(() => _removing = true);
    try {
      await MobileApi.instance.adminRemoveSupplier(widget.supplierRef);
      _changed = true;
      if (mounted) {
        Navigator.of(context).pop(true);
      }
    } finally {
      if (mounted) {
        setState(() => _removing = false);
      }
    }
  }

  Future<void> _copyCode(String code) async {
    await Clipboard.setData(ClipboardData(text: code));
    if (!mounted) {
      return;
    }
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(content: Text(context.l10n.adminText('detail.code_copied'))),
    );
  }

  @override
  Widget build(BuildContext context) {
    return PopScope(
      canPop: false,
      onPopInvokedWithResult: (didPop, _) {
        if (didPop) {
          return;
        }
        Navigator.of(context).pop(_changed);
      },
      child: AppShell(
        title: context.l10n.adminText('profile.title'),
        subtitle: '',
        nativeTopBar: true,
        nativeTitleTextStyle: AppTheme.werkaNativeAppBarTitleStyle(context),
        contentPadding: EdgeInsets.zero,
        bottom: const AdminDock(activeTab: AdminDockTab.user),
        child: SafeArea(
          top: false,
          child: FutureBuilder<AdminSupplierDetail>(
            future: _detailFuture,
            builder: (context, snapshot) {
              if (snapshot.connectionState != ConnectionState.done) {
                return const Center(child: AppLoadingIndicator());
              }
              if (snapshot.hasError) {
                return ListView(
                  padding: const EdgeInsets.fromLTRB(20, 4, 20, 24),
                  children: [
                    AppRetryState(onRetry: _reload, padding: EdgeInsets.zero),
                  ],
                );
              }

              final detail = snapshot.data!;
              return ListView(
                padding: const EdgeInsets.fromLTRB(
                  _supplierDetailPanelGap,
                  _supplierDetailPanelGap,
                  _supplierDetailPanelGap,
                  116,
                ),
                children: [
                  AppSegmentSurfaceCard(
                    padding: EdgeInsets.zero,
                    child: _AdminSupplierDetailCard(
                      detail: detail,
                      readOnly: widget.readOnly,
                      chatTarget: widget.chatTarget,
                      retryAfterSec: _retryAfterSec,
                      expanded: _adminPanelExpanded,
                      savingStatus: _savingStatus,
                      savingPhone: _savingPhone,
                      regeneratingCode: _regeneratingCode,
                      removing: _removing,
                      onExpandedChanged: (expanded) {
                        setState(() => _adminPanelExpanded = expanded);
                      },
                      onSavePhone: _savePhone,
                      onToggleBlocked: _toggleBlocked,
                      onRegenerateCode: _regenerateCode,
                      onCopyCode: _copyCode,
                      onRemove: _removeSupplier,
                      onViewItems: () => Navigator.of(context).pushNamed(
                        AppRoutes.adminSupplierItemsView,
                        arguments: widget.supplierRef,
                      ),
                      onAddItem: () => Navigator.of(context).pushNamed(
                        AppRoutes.adminSupplierItemsAdd,
                        arguments: widget.supplierRef,
                      ),
                    ),
                  ),
                ],
              );
            },
          ),
        ),
      ),
    );
  }
}
