// Generated by large_library_splitter.dart; keep changes in the source library.
part of 'admin_customer_detail_screen.dart';

class _AdminCustomerPanel extends StatelessWidget {
  const _AdminCustomerPanel({
    required this.detail,
    required this.itemManagementEnabled,
    required this.removeEnabled,
    required this.isMaterialTaminotchi,
    required this.warehouseEditor,
    required this.savingPhone,
    required this.regeneratingCode,
    required this.removing,
    required this.addingItem,
    required this.editingMaterialItemGroups,
    required this.removingItemCode,
    required this.onSavePhone,
    required this.onAddItem,
    required this.onRemoveItem,
    required this.onEditMaterialItemGroups,
    required this.onRegenerateCode,
    required this.onCopyCode,
    required this.onRemove,
  });

  final AdminCustomerDetail detail;
  final bool itemManagementEnabled;
  final bool removeEnabled;
  final bool isMaterialTaminotchi;
  final Widget? warehouseEditor;
  final bool savingPhone;
  final bool regeneratingCode;
  final bool removing;
  final bool addingItem;
  final bool editingMaterialItemGroups;
  final String? removingItemCode;
  final Future<void> Function(AdminCustomerDetail detail, String phone)
      onSavePhone;
  final Future<void> Function() onAddItem;
  final Future<bool> Function(SupplierItem item) onRemoveItem;
  final Future<void> Function() onEditMaterialItemGroups;
  final Future<void> Function() onRegenerateCode;
  final Future<void> Function(String code) onCopyCode;
  final Future<void> Function() onRemove;

  @override
  Widget build(BuildContext context) {
    final l10n = context.l10n;
    final theme = Theme.of(context);
    final scheme = theme.colorScheme;
    return Column(
      crossAxisAlignment: CrossAxisAlignment.stretch,
      children: [
        Divider(
          height: 1,
          color: scheme.outlineVariant.withValues(alpha: 0.7),
        ),
        const SizedBox(height: 14),
        Text(
          l10n.adminText('profile.admin_controls'),
          style: theme.textTheme.titleMedium?.copyWith(
            fontWeight: FontWeight.w800,
          ),
        ),
        const SizedBox(height: 14),
        Text(l10n.adminText('profile.phone'), style: theme.textTheme.bodySmall),
        const SizedBox(height: 6),
        _CustomerPhoneInlineField(
          detail: detail,
          savingPhone: savingPhone,
          onSavePhone: onSavePhone,
        ),
        const SizedBox(height: 14),
        Text(
          l10n.adminText('profile.access_code'),
          style: theme.textTheme.bodySmall,
        ),
        const SizedBox(height: 6),
        AppDetailField(
          child: Row(
            children: [
              Expanded(
                child: Text(
                  detail.code.trim().isEmpty
                      ? l10n.adminText('profile.not_generated')
                      : detail.code,
                  style: theme.textTheme.titleMedium,
                ),
              ),
              if (detail.code.trim().isNotEmpty)
                IconButton(
                  onPressed: () => onCopyCode(detail.code),
                  icon: const Icon(Icons.content_copy_outlined),
                ),
              IconButton(
                key: const ValueKey('admin-customer-detail-code-regenerate'),
                onPressed: regeneratingCode || detail.codeLocked
                    ? null
                    : onRegenerateCode,
                icon: regeneratingCode
                    ? const SizedBox(
                        height: 18,
                        width: 18,
                        child: CircularProgressIndicator(strokeWidth: 2),
                      )
                    : const Icon(Icons.refresh_rounded),
              ),
            ],
          ),
        ),
        if (detail.codeRetryAfterSec > 0) ...[
          const SizedBox(height: 12),
          Text(
            l10n.adminText(
              'profile.code_wait',
              values: {'seconds': detail.codeRetryAfterSec},
            ),
            style: theme.textTheme.bodySmall?.copyWith(
              color: scheme.onSurfaceVariant,
            ),
          ),
        ],
        if (isMaterialTaminotchi) ...[
          const SizedBox(height: 18),
          Text(
            l10n.adminText('item.group'),
            style: theme.textTheme.titleLarge,
          ),
          const SizedBox(height: 8),
          Text(
            detail.assignedItemGroups.isEmpty
                ? l10n.adminText('detail.groups_unassigned')
                : l10n.adminText('detail.groups_scope'),
            style: theme.textTheme.bodySmall?.copyWith(
              color: detail.assignedItemGroups.isEmpty
                  ? scheme.error
                  : scheme.onSurfaceVariant,
            ),
          ),
          if (detail.assignedItemGroups.isNotEmpty) ...[
            const SizedBox(height: 10),
            Wrap(
              spacing: 8,
              runSpacing: 8,
              children: [
                for (final group in detail.assignedItemGroups)
                  Chip(
                    avatar: const Icon(Icons.category_outlined, size: 17),
                    label: Text(group),
                  ),
              ],
            ),
          ],
          const SizedBox(height: 12),
          SizedBox(
            width: double.infinity,
            child: OutlinedButton.icon(
              key: const ValueKey(
                'admin-material-detail-edit-item-groups',
              ),
              style: appOutlinedActionButtonStyle(
                borderRadius: _customerDetailButtonRadius,
              ),
              onPressed:
                  editingMaterialItemGroups ? null : onEditMaterialItemGroups,
              icon: editingMaterialItemGroups
                  ? const SizedBox.square(
                      dimension: 18,
                      child: CircularProgressIndicator(strokeWidth: 2),
                    )
                  : const Icon(Icons.edit_outlined),
              label: Text(
                editingMaterialItemGroups
                    ? l10n.adminText('detail.loading')
                    : l10n.adminText('detail.edit_groups'),
              ),
            ),
          ),
          const SizedBox(height: 18),
          if (warehouseEditor != null) warehouseEditor!,
        ],
        if (itemManagementEnabled) ...[
          const SizedBox(height: 18),
          Text(
            l10n.adminText('detail.assigned_items'),
            style: theme.textTheme.titleLarge,
          ),
          const SizedBox(height: 10),
          Text(
            detail.assignedItems.isEmpty
                ? l10n.adminText('detail.assigned_items_empty')
                : l10n.adminText(
                    'detail.assigned_items_count',
                    values: {'count': detail.assignedItems.length},
                  ),
            style: theme.textTheme.bodySmall?.copyWith(
              color: scheme.onSurfaceVariant,
            ),
          ),
          const SizedBox(height: 12),
          Row(
            children: [
              Expanded(
                child: OutlinedButton(
                  style: appOutlinedActionButtonStyle(
                    borderRadius: _customerDetailButtonRadius,
                  ),
                  onPressed: detail.assignedItems.isEmpty
                      ? null
                      : () => _showAssignedItemsSheet(
                            context,
                            detail,
                            onRemoveItem: onRemoveItem,
                            removingItemCode: removingItemCode,
                          ),
                  child: Text(l10n.adminText('detail.items_view')),
                ),
              ),
              const SizedBox(width: 12),
              Expanded(
                child: OutlinedButton(
                  style: appOutlinedActionButtonStyle(
                    borderRadius: _customerDetailButtonRadius,
                  ),
                  onPressed: addingItem ? null : onAddItem,
                  child: Text(
                    addingItem
                        ? l10n.adminText('detail.items_adding')
                        : l10n.adminText('detail.add'),
                  ),
                ),
              ),
            ],
          ),
        ],
        if (removeEnabled) ...[
          const SizedBox(height: 8),
          SizedBox(
            width: double.infinity,
            child: OutlinedButton(
              style: appOutlinedActionButtonStyle(
                borderRadius: _customerDetailButtonRadius,
              ),
              onPressed: removing ? null : onRemove,
              child: Text(
                removing
                    ? l10n.adminText('detail.removing')
                    : l10n.adminText('detail.remove_from_system'),
              ),
            ),
          ),
        ],
      ],
    );
  }
}

class _CustomerPhoneInlineField extends StatefulWidget {
  const _CustomerPhoneInlineField({
    required this.detail,
    required this.savingPhone,
    required this.onSavePhone,
  });

  final AdminCustomerDetail detail;
  final bool savingPhone;
  final Future<void> Function(AdminCustomerDetail detail, String phone)
      onSavePhone;

  @override
  State<_CustomerPhoneInlineField> createState() =>
      _CustomerPhoneInlineFieldState();
}

class _CustomerPhoneInlineFieldState extends State<_CustomerPhoneInlineField> {
  late final TextEditingController _controller;
  bool _editing = false;

  @override
  void initState() {
    super.initState();
    _controller = TextEditingController(text: widget.detail.phone.trim());
  }

  @override
  void didUpdateWidget(covariant _CustomerPhoneInlineField oldWidget) {
    super.didUpdateWidget(oldWidget);
    if (!_editing && oldWidget.detail.phone != widget.detail.phone) {
      _controller.text = widget.detail.phone.trim();
    }
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  Future<void> _submit() async {
    await widget.onSavePhone(widget.detail, _controller.text);
    if (mounted) {
      setState(() => _editing = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    final l10n = context.l10n;
    final theme = Theme.of(context);
    final phone = widget.detail.phone.trim();
    return AppDetailField(
      child: Row(
        children: [
          Expanded(
            child: _editing
                ? TextField(
                    key: const ValueKey('admin-customer-detail-phone-input'),
                    controller: _controller,
                    autofocus: true,
                    keyboardType: TextInputType.phone,
                    decoration: const InputDecoration(
                      border: InputBorder.none,
                      isDense: true,
                      hintText: '+998 90 123 45 67',
                    ),
                    style: theme.textTheme.titleMedium,
                    onSubmitted: (_) => _submit(),
                  )
                : Text(
                    phone.isEmpty ? l10n.adminText('profile.entered') : phone,
                    style: theme.textTheme.titleMedium,
                  ),
          ),
          IconButton(
            key: const ValueKey('admin-customer-detail-phone-action'),
            tooltip: _editing
                ? l10n.adminText('profile.save_phone')
                : phone.isEmpty
                    ? l10n.adminText('profile.enter_phone')
                    : l10n.adminText('profile.update_phone'),
            onPressed: widget.savingPhone
                ? null
                : _editing
                    ? _submit
                    : () => setState(() => _editing = true),
            icon: widget.savingPhone
                ? const SizedBox(
                    height: 18,
                    width: 18,
                    child: CircularProgressIndicator(strokeWidth: 2),
                  )
                : Icon(_editing ? Icons.check_rounded : Icons.edit_rounded),
          ),
        ],
      ),
    );
  }
}

String _customerInitials(String name) {
  final parts = name
      .trim()
      .split(RegExp(r'\s+'))
      .where((part) => part.trim().isNotEmpty)
      .toList(growable: false);
  if (parts.isEmpty) {
    return 'H';
  }
  final first = parts.first.characters.first.toUpperCase();
  if (parts.length == 1) {
    return first;
  }
  return '$first${parts.last.characters.first.toUpperCase()}';
}
