// Generated by large_library_splitter.dart; keep changes in the source library.
part of 'gscale_mobile_app.dart';

class _ManualServerSheetState extends State<ManualServerSheet> {
  late final TextEditingController _controller;
  bool _checking = false;
  String _errorText = '';

  @override
  void initState() {
    super.initState();
    _controller = TextEditingController(
      text: _sanitizeManualServerAddress(_configuredApiBaseUrl),
    );
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  Future<void> _submit() async {
    if (_checking) {
      return;
    }

    setState(() {
      _checking = true;
      _errorText = '';
    });

    final endpoint = parseServerEndpoint(_controller.text);
    if (endpoint == null) {
      setState(() {
        _checking = false;
        _errorText = 'Manzil formati noto‘g‘ri';
      });
      return;
    }
    if (_shouldSkipDiscoveryHost(endpoint.host)) {
      setState(() {
        _checking = false;
        _errorText = 'Localhost emas, Wi‑Fi server manzilini kiriting';
      });
      return;
    }

    final server = await probeServer(
      widget.client,
      endpoint,
      timeout: _manualProbeTimeout,
    );
    if (!mounted) {
      return;
    }

    if (server == null) {
      setState(() {
        _checking = false;
        _errorText = 'Bu server bilan qo‘shilish muvaffaqiyatsiz';
      });
      return;
    }

    Navigator.of(context).pop(server);
  }

  @override
  Widget build(BuildContext context) {
    final scheme = Theme.of(context).colorScheme;
    final bottomInset = MediaQuery.of(context).viewInsets.bottom;

    return Padding(
      padding: EdgeInsets.fromLTRB(18, 0, 18, bottomInset + 18),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            'Server qo‘shish',
            style: Theme.of(
              context,
            ).textTheme.titleLarge?.copyWith(fontWeight: FontWeight.w800),
          ),
          const SizedBox(height: 8),
          Text(
            'Masalan: 192.168.1.12:39117',
            style: Theme.of(
              context,
            ).textTheme.bodyMedium?.copyWith(color: scheme.onSurfaceVariant),
          ),
          const SizedBox(height: 16),
          TextField(
            controller: _controller,
            keyboardType: TextInputType.url,
            decoration: InputDecoration(
              labelText: 'Server manzili',
              hintText: 'http://192.168.1.12:39117',
              border: OutlineInputBorder(
                borderRadius: BorderRadius.circular(8),
              ),
              enabledBorder: OutlineInputBorder(
                borderRadius: BorderRadius.circular(8),
                borderSide: BorderSide(color: scheme.outlineVariant),
              ),
              focusedBorder: OutlineInputBorder(
                borderRadius: BorderRadius.circular(8),
                borderSide: BorderSide(color: scheme.primary, width: 1.4),
              ),
            ),
            onSubmitted: (_) => _submit(),
          ),
          if (_errorText.isNotEmpty) ...[
            const SizedBox(height: 10),
            Text(_errorText, style: TextStyle(color: scheme.error)),
          ],
          const SizedBox(height: 16),
          FilledButton.icon(
            onPressed: _checking ? null : _submit,
            icon: const Icon(Icons.link_rounded),
            label: Text(_checking ? 'Tekshirilmoqda...' : 'Serverga ulanish'),
          ),
        ],
      ),
    );
  }
}
