// Generated by large_library_splitter.dart; keep changes in the source library.
part of 'profile_screen.dart';

class _ProfileSettingsSheet extends StatelessWidget {
  const _ProfileSettingsSheet({
    required this.maxHeight,
    required this.bottomPadding,
    required this.currentLocale,
    required this.themeVariant,
    required this.isDarkMode,
    required this.hasPin,
    required this.savingPin,
    required this.hasSwitchPin,
    required this.savingSwitchPin,
    required this.biometricEnabled,
    required this.savingBiometric,
    required this.onShowPinFlow,
    required this.onRemovePin,
    required this.onShowSwitchPinFlow,
    required this.onRemoveSwitchPin,
    required this.onToggleBiometric,
    required this.onCheckForUpdate,
    required this.onDisconnectSession,
  });

  final double maxHeight;
  final double bottomPadding;
  final Locale currentLocale;
  final AppThemeVariant themeVariant;
  final bool isDarkMode;
  final bool hasPin;
  final bool savingPin;
  final bool hasSwitchPin;
  final bool savingSwitchPin;
  final bool biometricEnabled;
  final bool savingBiometric;
  final VoidCallback onShowPinFlow;
  final VoidCallback onRemovePin;
  final VoidCallback onShowSwitchPinFlow;
  final VoidCallback onRemoveSwitchPin;
  final ValueChanged<bool> onToggleBiometric;
  final VoidCallback onCheckForUpdate;
  final VoidCallback onDisconnectSession;

  @override
  Widget build(BuildContext context) {
    final l10n = context.l10n;
    final theme = Theme.of(context);
    final scheme = theme.colorScheme;
    return _ProfileSelectionSheet(
      title: l10n.profileSettingsTitle,
      subtitle: l10n.profileSettingsBody,
      maxHeight: maxHeight,
      bottomPadding: bottomPadding,
      child: AppSegmentSurfaceCard(
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          mainAxisSize: MainAxisSize.min,
          children: [
            _ProfileSettingsRowPadding(
              child: _LanguagePreferenceRow(currentLocale: currentLocale),
            ),
            const SizedBox(height: 16),
            _ProfileSettingsRowPadding(
              child: _ThemeModePreferenceRow(isDark: isDarkMode),
            ),
            const SizedBox(height: 16),
            _ProfileSettingsRowPadding(
              child: _ThemePreferenceRow(variant: themeVariant),
            ),
            const SizedBox(height: 16),
            _ProfileSettingsRowPadding(
              child: _AppUpdatePreferenceRow(onTap: onCheckForUpdate),
            ),
            const SizedBox(height: 22),
            Divider(
              height: 1,
              thickness: 1,
              color: scheme.outlineVariant.withValues(alpha: 0.55),
            ),
            const SizedBox(height: 22),
            Text(l10n.securityTitle, style: theme.textTheme.titleLarge),
            const SizedBox(height: 14),
            Text(l10n.appLockPinTitle, style: theme.textTheme.titleMedium),
            const SizedBox(height: 4),
            Text(
              l10n.appLockPinBody,
              style: theme.textTheme.bodySmall?.copyWith(
                color: scheme.onSurfaceVariant,
              ),
            ),
            const SizedBox(height: 12),
            _ProfileActionButton(
              primary: true,
              onPressed: savingPin ? null : onShowPinFlow,
              label: savingPin
                  ? l10n.pinSaving
                  : hasPin
                      ? l10n.pinChange
                      : l10n.pinSet,
            ),
            if (hasPin) ...[
              const SizedBox(height: 10),
              _ProfileActionButton(
                primary: false,
                onPressed: savingPin ? null : onRemovePin,
                label: l10n.pinRemove,
              ),
            ],
            const SizedBox(height: 16),
            _ProfileSettingsRowPadding(
              child: _BiometricPreferenceRow(
                enabled: biometricEnabled,
                interactive: hasPin && !savingBiometric,
                onChanged: onToggleBiometric,
              ),
            ),
            const SizedBox(height: 22),
            Divider(
              height: 1,
              thickness: 1,
              color: scheme.outlineVariant.withValues(alpha: 0.55),
            ),
            const SizedBox(height: 22),
            Text(l10n.switchPinTitle, style: theme.textTheme.titleMedium),
            const SizedBox(height: 4),
            Text(
              l10n.switchPinBody,
              style: theme.textTheme.bodySmall?.copyWith(
                color: scheme.onSurfaceVariant,
              ),
            ),
            const SizedBox(height: 12),
            _ProfileActionButton(
              primary: true,
              onPressed: savingSwitchPin ? null : onShowSwitchPinFlow,
              label: savingSwitchPin
                  ? l10n.pinSaving
                  : hasSwitchPin
                      ? l10n.switchPinChange
                      : l10n.switchPinSet,
            ),
            if (hasSwitchPin) ...[
              const SizedBox(height: 10),
              _ProfileActionButton(
                primary: false,
                onPressed: savingSwitchPin ? null : onRemoveSwitchPin,
                label: l10n.switchPinRemove,
              ),
            ],
            const SizedBox(height: 22),
            Divider(
              height: 1,
              thickness: 1,
              color: scheme.outlineVariant.withValues(alpha: 0.55),
            ),
            const SizedBox(height: 14),
            _DisconnectSessionSettingsRow(onTap: onDisconnectSession),
          ],
        ),
      ),
    );
  }
}

class _AppUpdatePreferenceRow extends StatelessWidget {
  const _AppUpdatePreferenceRow({required this.onTap});

  final VoidCallback onTap;

  @override
  Widget build(BuildContext context) {
    final l10n = context.l10n;
    final theme = Theme.of(context);
    final scheme = theme.colorScheme;
    return InkWell(
      borderRadius: BorderRadius.circular(18),
      onTap: onTap,
      child: Padding(
        padding: const EdgeInsets.symmetric(vertical: 4),
        child: Row(
          children: [
            Icon(Icons.system_update_rounded, color: scheme.primary),
            const SizedBox(width: 14),
            Expanded(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    l10n.appUpdateSettingsTitle,
                    style: theme.textTheme.titleMedium,
                  ),
                  const SizedBox(height: 4),
                  Text(
                    l10n.appUpdateSettingsBody,
                    style: theme.textTheme.bodySmall?.copyWith(
                      color: scheme.onSurfaceVariant,
                    ),
                  ),
                ],
              ),
            ),
            const SizedBox(width: 10),
            Icon(Icons.chevron_right_rounded, color: scheme.onSurfaceVariant),
          ],
        ),
      ),
    );
  }
}

class _ProfileSettingsRowPadding extends StatelessWidget {
  const _ProfileSettingsRowPadding({required this.child});

  final Widget child;

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.symmetric(horizontal: 2, vertical: 2),
      child: child,
    );
  }
}

class _DisconnectSessionSettingsRow extends StatelessWidget {
  const _DisconnectSessionSettingsRow({required this.onTap});

  final VoidCallback onTap;

  @override
  Widget build(BuildContext context) {
    final l10n = context.l10n;
    final theme = Theme.of(context);
    final scheme = theme.colorScheme;
    return InkWell(
      borderRadius: BorderRadius.circular(18),
      onTap: onTap,
      child: Padding(
        padding: const EdgeInsets.symmetric(horizontal: 2, vertical: 10),
        child: Row(
          children: [
            Icon(Icons.logout_rounded, color: scheme.error),
            const SizedBox(width: 14),
            Expanded(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    l10n.disconnectSessionTitle,
                    style: theme.textTheme.titleMedium?.copyWith(
                      color: scheme.error,
                    ),
                  ),
                  const SizedBox(height: 4),
                  Text(
                    l10n.disconnectSessionBody,
                    style: theme.textTheme.bodySmall?.copyWith(
                      color: scheme.onSurfaceVariant,
                    ),
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}

class _LanguagePreferenceRow extends StatelessWidget {
  const _LanguagePreferenceRow({required this.currentLocale});

  final Locale currentLocale;

  Future<void> _openLanguagePicker(BuildContext context) async {
    final l10n = context.l10n;
    final picked = await showModalBottomSheet<Locale>(
      context: context,
      isDismissible: true,
      enableDrag: true,
      useSafeArea: true,
      backgroundColor: Colors.transparent,
      sheetAnimationStyle: AppMotion.sheetEaseOut,
      builder: (context) {
        return GestureDetector(
          behavior: HitTestBehavior.opaque,
          onTap: () => Navigator.of(context).maybePop(),
          child: SafeArea(
            top: false,
            bottom: false,
            child: Align(
              alignment: Alignment.bottomCenter,
              child: GestureDetector(
                onTap: () {},
                child: _ProfileSelectionSheet(
                  title: l10n.languageTitle,
                  subtitle: l10n.languageBody,
                  child: M3SegmentSpacedColumn(
                    children: [
                      _ProfileSelectionOption(
                        index: 0,
                        itemCount: 3,
                        title: l10n.uzbek,
                        subtitle: 'Uzbek',
                        active: currentLocale.languageCode == 'uz',
                        onTap: () =>
                            Navigator.of(context).pop(const Locale('uz')),
                      ),
                      _ProfileSelectionOption(
                        index: 1,
                        itemCount: 3,
                        title: l10n.english,
                        subtitle: 'English',
                        active: currentLocale.languageCode == 'en',
                        onTap: () =>
                            Navigator.of(context).pop(const Locale('en')),
                      ),
                      _ProfileSelectionOption(
                        index: 2,
                        itemCount: 3,
                        title: l10n.russian,
                        subtitle: 'Russian',
                        active: currentLocale.languageCode == 'ru',
                        onTap: () =>
                            Navigator.of(context).pop(const Locale('ru')),
                      ),
                    ],
                  ),
                ),
              ),
            ),
          ),
        );
      },
    );
    if (picked == null) {
      return;
    }
    await LocaleController.instance.setLocale(picked);
  }

  @override
  Widget build(BuildContext context) {
    final l10n = context.l10n;
    final scheme = Theme.of(context).colorScheme;
    return InkWell(
      borderRadius: BorderRadius.circular(18),
      onTap: () => _openLanguagePicker(context),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.center,
        children: [
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  l10n.languageTitle,
                  style: Theme.of(context).textTheme.titleMedium,
                ),
                const SizedBox(height: 4),
                Text(
                  l10n.languageBody,
                  style: Theme.of(context).textTheme.bodySmall?.copyWith(
                        color: scheme.onSurfaceVariant,
                      ),
                ),
              ],
            ),
          ),
          const SizedBox(width: 16),
          Container(
            padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 8),
            decoration: BoxDecoration(
              color: scheme.surfaceContainerHighest,
              borderRadius: BorderRadius.circular(999),
            ),
            child: Text(
              currentLocale.languageCode == 'uz'
                  ? l10n.uzbek
                  : currentLocale.languageCode == 'ru'
                      ? l10n.russian
                      : l10n.english,
              style: Theme.of(context).textTheme.labelLarge,
            ),
          ),
        ],
      ),
    );
  }
}

class _ThemeModePreferenceRow extends StatelessWidget {
  const _ThemeModePreferenceRow({required this.isDark});

  final bool isDark;

  @override
  Widget build(BuildContext context) {
    final l10n = context.l10n;
    final theme = Theme.of(context);
    final scheme = theme.colorScheme;
    return Row(
      crossAxisAlignment: CrossAxisAlignment.center,
      children: [
        Expanded(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(l10n.themeModeTitle, style: theme.textTheme.titleMedium),
              const SizedBox(height: 4),
              Text(
                l10n.themeModeBody,
                style: theme.textTheme.bodySmall?.copyWith(
                  color: scheme.onSurfaceVariant,
                ),
              ),
            ],
          ),
        ),
        const SizedBox(width: 16),
        _ThemeIconToggle(isDark: isDark),
      ],
    );
  }
}
