// Generated by large_library_splitter.dart; keep changes in the source library.
part of 'profile_screen.dart';

extension __ProfileScreenStateAstPart02 on _ProfileScreenState {
  Future<void> _openProfileSettings() async {
    await showModalBottomSheet<void>(
      context: context,
      isScrollControlled: true,
      useSafeArea: false,
      backgroundColor: Colors.transparent,
      sheetAnimationStyle: AppMotion.sheetEaseOut,
      builder: (sheetContext) {
        final mediaQuery = MediaQuery.of(sheetContext);
        return GestureDetector(
          behavior: HitTestBehavior.opaque,
          onTap: () => Navigator.of(sheetContext).maybePop(),
          child: Align(
            alignment: Alignment.bottomCenter,
            child: GestureDetector(
              onTap: () {},
              child: AnimatedBuilder(
                animation: SecurityController.instance,
                builder: (context, _) {
                  return AnimatedBuilder(
                    animation: ThemeController.instance,
                    builder: (context, _) {
                      return _ProfileSettingsSheet(
                        maxHeight: mediaQuery.size.height * 0.78,
                        bottomPadding: mediaQuery.padding.bottom + 24,
                        currentLocale: LocaleController.instance.locale,
                        themeVariant: ThemeController.instance.variant,
                        isDarkMode: ThemeController.instance.isDark,
                        hasPin:
                            SecurityController.instance.hasPinForCurrentUser,
                        savingPin: savingPin,
                        hasSwitchPin: SecurityController
                            .instance.hasSwitchPinForCurrentUser,
                        savingSwitchPin: savingSwitchPin,
                        biometricEnabled: SecurityController
                            .instance.biometricEnabledForCurrentUser,
                        savingBiometric: savingBiometric,
                        onShowPinFlow: _showPinFlow,
                        onRemovePin: _removePin,
                        onShowSwitchPinFlow: _showSwitchPinFlow,
                        onRemoveSwitchPin: _removeSwitchPin,
                        onToggleBiometric: _toggleBiometric,
                        onCheckForUpdate: () async {
                          await AppUpdateCoordinator.instance.checkAndPrompt(
                            context,
                            manual: true,
                          );
                        },
                        onDisconnectSession: () async {
                          Navigator.of(sheetContext).pop();
                          await showDisconnectSessionPrompt(context);
                        },
                      );
                    },
                  );
                },
              ),
            ),
          ),
        );
      },
    );
  }

  void _openWerkaDrawerRoute(String route) {
    final current = ModalRoute.of(context)?.settings.name;
    if (current == route) {
      return;
    }
    Navigator.of(context).pushReplacementNamed(route);
  }

  void _openSupplierDrawerRoute(String route) {
    final current = ModalRoute.of(context)?.settings.name;
    if (current == route) {
      return;
    }
    Navigator.of(context).pushReplacementNamed(route);
  }

  void _openCustomerDrawerRoute(String route) {
    final current = ModalRoute.of(context)?.settings.name;
    if (current == route) {
      return;
    }
    Navigator.of(context).pushReplacementNamed(route);
  }

  void _openMaterialTaminotchiDrawerRoute(String route) {
    final current = ModalRoute.of(context)?.settings.name;
    if (current == route) {
      return;
    }
    Navigator.of(context).pushReplacementNamed(route);
  }

  void _openAparatchiDrawerRoute(String route) {
    final current = ModalRoute.of(context)?.settings.name;
    if (current == route) {
      return;
    }
    AppRootNavigation.replaceRootRoute(context, route);
  }

  void _openQolipDrawerRoute(String route) {
    final current = ModalRoute.of(context)?.settings.name;
    if (current == route) {
      return;
    }
    AppRootNavigation.replaceRootRoute(context, route);
  }

  void _openBoyoqchiDrawerRoute(String route) {
    final current = ModalRoute.of(context)?.settings.name;
    if (current == route) {
      return;
    }
    AppRootNavigation.replaceRootRoute(context, route);
  }
}
