// Generated by large_library_splitter.dart; keep changes in the source library.
part of 'admin_localization.dart';

const _admin_localization_adminTranslations_resplitPart02 = {
  'admin.warehouse.incoming_quantity': {
    'uz': 'Kirim miqdori',
    'en': 'Incoming quantity',
    'ru': 'Количество прихода',
  },
  'admin.warehouse.select_product': {
    'uz': 'Mahsulot tanlang',
    'en': 'Select an item',
    'ru': 'Выберите товар',
  },
  'admin.warehouse.product_search': {
    'uz': 'Mahsulot nomi yoki kodini qidiring',
    'en': 'Search by item name or code',
    'ru': 'Поиск по названию или коду товара',
  },
  'admin.warehouse.no_selection': {
    'uz': 'Ombor tanlanmagan',
    'en': 'No warehouse selected',
    'ru': 'Склад не выбран',
  },
  'admin.warehouse.delete_title': {
    'uz': 'Omborni o‘chirish',
    'en': 'Delete warehouse',
    'ru': 'Удалить склад',
  },
  'admin.warehouse.delete_blocked': {
    'uz': 'Omborni o‘chirib bo‘lmaydi',
    'en': 'Warehouse cannot be deleted',
    'ru': 'Склад нельзя удалить',
  },
  'admin.warehouse.qr_view': {
    'uz': 'QR kodni ko‘rish',
    'en': 'View QR code',
    'ru': 'Показать QR-код',
  },
  'admin.warehouse.qr_mismatch': {
    'uz': 'Serverdagi QR identifikatori mos kelmadi',
    'en': 'The server QR identifier did not match',
    'ru': 'QR-идентификатор сервера не совпадает',
  },
  'admin.material.title': {
    'uz': 'Xomashyo mikronlari',
    'en': 'Raw material microns',
    'ru': 'Микроны сырья',
  },
  'admin.material.add': {
    'uz': 'Xomashyo qo‘shish',
    'en': 'Add raw material',
    'ru': 'Добавить сырьё',
  },
  'admin.material.empty': {
    'uz': 'Xomashyo yo‘q',
    'en': 'No raw materials found',
    'ru': 'Сырьё не найдено',
  },
  'admin.material.name': {
    'uz': 'Xomashyo nomi',
    'en': 'Raw material name',
    'ru': 'Название сырья',
  },
  'admin.material.density': {
    'uz': 'Zichlik',
    'en': 'Density',
    'ru': 'Плотность',
  },
  'admin.material.density_hint': {
    'uz': 'masalan: PET 1.40',
    'en': 'for example: PET 1.40',
    'ru': 'например: PET 1.40',
  },
  'admin.material.show_in_picker': {
    'uz': 'Tanlashda ko‘rsatilsin',
    'en': 'Show in selectors',
    'ru': 'Показывать в списках выбора',
  },
  'admin.material.add_micron': {
    'uz': 'Mikron qo‘shish',
    'en': 'Add micron',
    'ru': 'Добавить микрон',
  },
  'admin.material.actual_gsm': {
    'uz': 'Actual GSM',
    'en': 'Actual GSM',
    'ru': 'Фактический GSM',
  },
  'admin.material.saved': {
    'uz': 'Xomashyo saqlandi',
    'en': 'Raw material saved',
    'ru': 'Сырьё сохранено',
  },
  'admin.material.micron': {
    'uz': 'Mikron',
    'en': 'Micron',
    'ru': 'Микрон',
  },
  'admin.material.microns': {
    'uz': 'Mikronlar',
    'en': 'Microns',
    'ru': 'Микроны',
  },
  'admin.material.micron_search': {
    'uz': 'Mikron qidiring',
    'en': 'Search microns',
    'ru': 'Поиск микронов',
  },
  'admin.apparatus.title': {
    'uz': 'Aparat sozlamalari',
    'en': 'Equipment settings',
    'ru': 'Настройки оборудования',
  },
  'admin.apparatus.add': {
    'uz': 'Aparat qo‘shish',
    'en': 'Add equipment',
    'ru': 'Добавить оборудование',
  },
  'admin.apparatus.name': {
    'uz': 'Aparat nomi',
    'en': 'Equipment name',
    'ru': 'Название оборудования',
  },
  'admin.apparatus.family': {
    'uz': 'Aparat oilasi (family)',
    'en': 'Equipment family',
    'ru': 'Семейство оборудования',
  },
  'admin.apparatus.family_select': {
    'uz': 'Aparat oilasi tanlang',
    'en': 'Select an equipment family',
    'ru': 'Выберите семейство оборудования',
  },
  'admin.apparatus.kind': {
    'uz': 'Aparat turi (kind)',
    'en': 'Equipment type',
    'ru': 'Тип оборудования',
  },
  'admin.apparatus.kind_select': {
    'uz': 'Aparat turi tanlang',
    'en': 'Select an equipment type',
    'ru': 'Выберите тип оборудования',
  },
  'admin.apparatus.capabilities': {
    'uz': 'Capability lar',
    'en': 'Capabilities',
    'ru': 'Возможности',
  },
  'admin.apparatus.capability_select': {
    'uz': 'Capability tanlang',
    'en': 'Select capabilities',
    'ru': 'Выберите возможности',
  },
  'admin.apparatus.groups': {
    'uz': 'Aparat guruhlari',
    'en': 'Equipment groups',
    'ru': 'Группы оборудования',
  },
  'admin.apparatus.group.print': {
    'uz': 'Bosma aparat',
    'en': 'Printing equipment',
    'ru': 'Печатное оборудование',
  },
  'admin.apparatus.group.laminate': {
    'uz': 'Laminatsiya',
    'en': 'Lamination',
    'ru': 'Ламинация',
  },
  'admin.apparatus.group.cut': {
    'uz': 'Rezka',
    'en': 'Cutting',
    'ru': 'Резка',
  },
  'admin.apparatus.group.package': {
    'uz': 'Paket apparati',
    'en': 'Bag-making equipment',
    'ru': 'Пакетное оборудование',
  },
  'admin.apparatus.group.glue': {
    'uz': 'Kley apparati',
    'en': 'Adhesive equipment',
    'ru': 'Клеевое оборудование',
  },
  'admin.apparatus.group.unclassified': {
    'uz': 'Tasniflanmagan aparatlar',
    'en': 'Unclassified equipment',
    'ru': 'Неклассифицированное оборудование',
  },
  'admin.apparatus.groups_canonical_description': {
    'uz':
        'Guruhlar canonical operation maydonidan avtomatik hosil qilinadi. Guruhni o‘zgartirish uchun aparat master-data turini tahrirlang.',
    'en':
        'Groups are derived automatically from the canonical operation field. Edit the equipment master-data type to change its group.',
    'ru':
        'Группы автоматически формируются из canonical-поля operation. Чтобы изменить группу, отредактируйте тип мастер-данных оборудования.',
  },
  'admin.apparatus.custom_groups_description': {
    'uz':
        'Maxsus guruhlar faqat aparatlar ro‘yxatini tartiblash uchun. Ular canonical operation, navbat yoki ishlab chiqarish jarayonini o‘zgartirmaydi.',
    'en':
        'Custom groups only organize the equipment list. They do not change canonical operations, queues, or production workflows.',
    'ru':
        'Пользовательские группы только упорядочивают список оборудования. Они не меняют canonical operation, очереди или производство.',
  },
  'admin.apparatus.automatic_groups': {
    'uz': 'Avtomatik guruhlar',
    'en': 'Automatic groups',
    'ru': 'Автоматические группы',
  },
  'admin.apparatus.custom_groups_empty': {
    'uz': 'Maxsus guruhlar hali qo‘shilmagan',
    'en': 'No custom groups yet',
    'ru': 'Пользовательских групп пока нет',
  },
  'admin.apparatus.group': {
    'uz': 'Aparat guruhi',
    'en': 'Equipment group',
    'ru': 'Группа оборудования',
  },
  'admin.apparatus.group_name': {
    'uz': 'Guruh nomi',
    'en': 'Group name',
    'ru': 'Название группы',
  },
  'admin.apparatus.group_save': {
    'uz': 'Guruhni saqlash',
    'en': 'Save group',
    'ru': 'Сохранить группу',
  },
  'admin.apparatus.group_add': {
    'uz': 'Aparat guruhi qo‘shish',
    'en': 'Add equipment group',
    'ru': 'Добавить группу оборудования',
  },
  'admin.apparatus.group_edit': {
    'uz': 'Aparat guruhini tahrirlash',
    'en': 'Edit equipment group',
    'ru': 'Изменить группу оборудования',
  },
  'admin.apparatus.group_delete': {
    'uz': 'Aparat guruhini o‘chirish',
    'en': 'Delete equipment group',
    'ru': 'Удалить группу оборудования',
  },
  'admin.apparatus.group_delete_confirm': {
    'uz': '{name} guruhi o‘chirilsinmi? Aparatlarning o‘zi o‘chirilmaydi.',
    'en': 'Delete {name}? The equipment itself will not be deleted.',
    'ru': 'Удалить группу {name}? Само оборудование не будет удалено.',
  },
  'admin.apparatus.group_added': {
    'uz': 'Aparat guruhi qo‘shildi',
    'en': 'Equipment group added',
    'ru': 'Группа оборудования добавлена',
  },
  'admin.apparatus.group_updated': {
    'uz': 'Aparat guruhi saqlandi',
    'en': 'Equipment group saved',
    'ru': 'Группа оборудования сохранена',
  },
  'admin.apparatus.group_deleted': {
    'uz': 'Aparat guruhi o‘chirildi',
    'en': 'Equipment group deleted',
    'ru': 'Группа оборудования удалена',
  },
  'admin.apparatus.group_save_failed': {
    'uz': 'Aparat guruhi saqlanmadi',
    'en': 'Equipment group was not saved',
    'ru': 'Не удалось сохранить группу оборудования',
  },
  'admin.apparatus.group_delete_failed': {
    'uz': 'Aparat guruhi o‘chirilmadi',
    'en': 'Equipment group was not deleted',
    'ru': 'Не удалось удалить группу оборудования',
  },
  'admin.apparatus.unassigned': {
    'uz': 'Guruhsiz',
    'en': 'Unassigned',
    'ru': 'Без группы',
  },
  'admin.apparatus.empty': {
    'uz': 'Aparatlar topilmadi',
    'en': 'No equipment found',
    'ru': 'Оборудование не найдено',
  },
  'admin.apparatus.search': {
    'uz': 'Aparat qidiring',
    'en': 'Search equipment',
    'ru': 'Поиск оборудования',
  },
  'admin.apparatus.edit': {
    'uz': 'Aparatni tahrirlash',
    'en': 'Edit equipment',
    'ru': 'Изменить оборудование',
  },
  'admin.apparatus.remove_link': {
    'uz': 'Bog‘lanishni olib tashlash',
    'en': 'Remove link',
    'ru': 'Удалить связь',
  },
  'admin.apparatus.training_enable': {
    'uz': 'Training’ni yoqish',
    'en': 'Enable training',
    'ru': 'Включить обучение',
  },
  'admin.apparatus.training_enabled': {
    'uz': 'Training rejimi yoqildi',
    'en': 'Training mode enabled',
    'ru': 'Режим обучения включён',
  },
  'admin.apparatus.training_disabled': {
    'uz': 'Training rejimi o‘chirildi',
    'en': 'Training mode disabled',
    'ru': 'Режим обучения выключен',
  },
  'admin.apparatus.available': {
    'uz': 'Mavjud aparatlar',
    'en': 'Available equipment',
    'ru': 'Доступное оборудование',
  },
  'admin.apparatus.assign_removed': {
    'uz': 'Aparat guruhdan chiqarildi',
    'en': 'Equipment removed from the group',
    'ru': 'Оборудование удалено из группы',
  },
  'admin.apparatus.assign_already': {
    'uz': 'Aparat shu guruhda allaqachon bor',
    'en': 'Equipment is already in this group',
    'ru': 'Оборудование уже входит в эту группу',
  },
  'admin.apparatus.assigned': {
    'uz': 'Aparat guruhga biriktirildi',
    'en': 'Equipment assigned to the group',
    'ru': 'Оборудование назначено группе',
  },
  'admin.apparatus.map_duplicate': {
    'uz': 'Bu 3D obyekt {name} apparatiga biriktirilgan',
    'en': 'This 3D object is already linked to {name}',
    'ru': 'Этот 3D-объект уже привязан к оборудованию {name}',
  },
  'admin.apparatus.map_removed': {
    'uz': '3D xarita bog‘lanishi olib tashlandi',
    'en': '3D map link removed',
    'ru': 'Связь с 3D-картой удалена',
  },
  'admin.apparatus.map_assigned': {
    'uz': 'Aparat 3D xaritaga biriktirildi',
    'en': 'Equipment linked to the 3D map',
    'ru': 'Оборудование привязано к 3D-карте',
  },
};
