// Generated by large_library_splitter.dart; keep changes in the source library.
part of 'admin_localization.dart';

const _admin_localization_adminTranslations_resplitPart21 = {
  'admin.production.no_equipment': {
    'uz': 'Ko‘chirish uchun aparat yo‘q',
    'en': 'No equipment available for moving orders',
    'ru': 'Нет оборудования для перемещения заказов',
  },
  'admin.production.audit_title': {
    'uz': 'Ish jarayoni tekshiruvi',
    'en': 'Workflow audit',
    'ru': 'Проверка рабочего процесса',
  },
  'admin.production.audit_clean': {
    'uz': 'Ish jarayoni tekshiruvi toza',
    'en': 'Workflow audit passed',
    'ru': 'Проверка рабочего процесса пройдена',
  },
  'admin.production.audit_issues': {
    'uz': 'Ish jarayoni tekshiruvida xatolar bor',
    'en': 'Workflow audit found issues',
    'ru': 'Проверка рабочего процесса выявила ошибки',
  },
  'admin.production.audit_description': {
    'uz':
        'Buyurtma, WIP, sessiya, ko‘chirish va quvvat qoidalari tekshiriladi.',
    'en': 'Orders, WIP, sessions, transfers, and capacity rules are checked.',
    'ru': 'Проверяются заказы, WIP, сессии, перемещения и правила мощности.',
  },
  'admin.production.refresh_audit': {
    'uz': 'Tekshiruvni yangilash',
    'en': 'Refresh audit',
    'ru': 'Обновить проверку',
  },
  'admin.production.orders': {
    'uz': 'Buyurtmalar',
    'en': 'Orders',
    'ru': 'Заказы',
  },
  'admin.production.batches': {
    'uz': 'Partiyalar',
    'en': 'Batches',
    'ru': 'Партии',
  },
  'admin.production.sessions': {
    'uz': 'Sessiyalar',
    'en': 'Sessions',
    'ru': 'Сессии',
  },
  'admin.production.errors': {
    'uz': 'Xatolar',
    'en': 'Errors',
    'ru': 'Ошибки',
  },
  'admin.production.audit_success': {
    'uz': 'Barcha tekshiruvlar muvaffaqiyatli',
    'en': 'All checks passed',
    'ru': 'Все проверки успешно пройдены',
  },
  'admin.production.audit_success_description': {
    'uz': 'Yashirin buyurtma va WIP nomuvofiqligi aniqlanmadi.',
    'en': 'No hidden order or WIP inconsistencies were found.',
    'ru': 'Скрытых несоответствий заказов и WIP не обнаружено.',
  },
  'admin.production.audit_order': {
    'uz': 'Buyurtma: {value}',
    'en': 'Order: {value}',
    'ru': 'Заказ: {value}',
  },
  'admin.production.audit_object': {
    'uz': 'Obyekt: {value}',
    'en': 'Object: {value}',
    'ru': 'Объект: {value}',
  },
  'admin.production.event_details': {
    'uz': 'Hodisa tafsilotlari',
    'en': 'Event details',
    'ru': 'Детали события',
  },
  'admin.production.event': {
    'uz': 'Hodisa',
    'en': 'Event',
    'ru': 'Событие',
  },
  'admin.production.time': {
    'uz': 'Vaqt',
    'en': 'Time',
    'ru': 'Время',
  },
  'admin.production.executor': {
    'uz': 'Bajaruvchi',
    'en': 'Performed by',
    'ru': 'Исполнитель',
  },
  'admin.production.event_id': {
    'uz': 'Event ID',
    'en': 'Event ID',
    'ru': 'ID события',
  },
  'admin.production.issue_note': {
    'uz': 'Muammo izohi',
    'en': 'Issue note',
    'ru': 'Описание проблемы',
  },
  'admin.production.freeze_details': {
    'uz': 'Muzlatish tafsilotlari',
    'en': 'Freeze details',
    'ru': 'Детали заморозки',
  },
  'admin.production.target_worker': {
    'uz': 'Maqsad ishchi',
    'en': 'Target worker',
    'ru': 'Целевой работник',
  },
  'admin.production.target_session': {
    'uz': 'Maqsad sessiya',
    'en': 'Target session',
    'ru': 'Целевая сессия',
  },
  'admin.production.freeze_request_id': {
    'uz': 'Freeze request ID',
    'en': 'Freeze request ID',
    'ru': 'ID запроса заморозки',
  },
  'admin.production.requested_at': {
    'uz': 'So‘rov vaqti',
    'en': 'Requested at',
    'ru': 'Время запроса',
  },
  'admin.production.state_transition': {
    'uz': 'Holat o‘zgarishi',
    'en': 'State transition',
    'ru': 'Изменение состояния',
  },
  'admin.production.transfer_details': {
    'uz': 'Apparat almashtirish tafsilotlari',
    'en': 'Equipment transfer details',
    'ru': 'Детали перемещения оборудования',
  },
  'admin.production.from': {
    'uz': 'Qayerdan',
    'en': 'From',
    'ru': 'Откуда',
  },
  'admin.production.to': {
    'uz': 'Qayerga',
    'en': 'To',
    'ru': 'Куда',
  },
  'admin.production.transfer_id': {
    'uz': 'Transfer ID',
    'en': 'Transfer ID',
    'ru': 'ID перемещения',
  },
  'admin.production.progress_batch': {
    'uz': 'Progress batch',
    'en': 'Progress batch',
    'ru': 'Прогресс-партия',
  },
  'admin.production.material_qr': {
    'uz': 'Material QR/barcode',
    'en': 'Material QR/barcode',
    'ru': 'QR/штрихкод материала',
  },
  'admin.production.progress_info': {
    'uz': 'Progress ma’lumoti',
    'en': 'Progress information',
    'ru': 'Данные прогресса',
  },
  'admin.production.progress_info_plural': {
    'uz': 'Progress ma’lumotlari',
    'en': 'Progress information',
    'ru': 'Данные прогресса',
  },
  'admin.production.progress_empty': {
    'uz': 'Bu hodisa uchun qo‘shimcha progress ma’lumoti yo‘q.',
    'en': 'No additional progress information is available for this event.',
    'ru': 'Для этого события нет дополнительных данных прогресса.',
  },
  'admin.production.produced': {
    'uz': 'Ishlab chiqarildi: {value}',
    'en': 'Produced: {value}',
    'ru': 'Произведено: {value}',
  },
  'admin.production.returned_ink': {
    'uz': 'Qaytgan bo‘yoq: {value} kg',
    'en': 'Returned ink: {value} kg',
    'ru': 'Возвращено краски: {value} кг',
  },
  'admin.production.print_roll_waste': {
    'uz': 'Bosma rulon qoldig‘i: {value}',
    'en': 'Printing roll leftover: {value}',
    'ru': 'Остаток печатного рулона: {value}',
  },
  'admin.production.film_waste': {
    'uz': 'Plyonka qoldig‘i: {value}',
    'en': 'Film leftover: {value}',
    'ru': 'Остаток плёнки: {value}',
  },
  'admin.production.print_waste': {
    'uz': 'Bosma chiqindi: {value}',
    'en': 'Printing waste: {value}',
    'ru': 'Отходы печати: {value}',
  },
  'admin.production.lamination_waste': {
    'uz': 'Laminatsiya chiqindisi: {value}',
    'en': 'Lamination waste: {value}',
    'ru': 'Отходы ламинации: {value}',
  },
  'admin.production.edge_waste': {
    'uz': 'Chekka chiqindi: {value}',
    'en': 'Edge waste: {value}',
    'ru': 'Кромочные отходы: {value}',
  },
  'admin.production.total_waste': {
    'uz': 'Jami chiqindi: {value}',
    'en': 'Total waste: {value}',
    'ru': 'Всего отходов: {value}',
  },
  'admin.production.finished_goods': {
    'uz': 'Tayyor mahsulot: {value} kg',
    'en': 'Finished goods: {value} kg',
    'ru': 'Готовая продукция: {value} кг',
  },
  'admin.production.finished_meters': {
    'uz': 'Tayyor metr: {value} m',
    'en': 'Finished length: {value} m',
    'ru': 'Готовая длина: {value} м',
  },
  'admin.production.batch_id': {
    'uz': 'Batch ID',
    'en': 'Batch ID',
    'ru': 'ID партии',
  },
  'admin.production.item': {
    'uz': 'Mahsulot',
    'en': 'Item',
    'ru': 'Товар',
  },
  'admin.production.location': {
    'uz': 'Joylashuvi',
    'en': 'Location',
    'ru': 'Расположение',
  },
  'admin.production.next_equipment': {
    'uz': 'Keyingi aparat',
    'en': 'Next equipment',
    'ru': 'Следующее оборудование',
  },
  'admin.production.parent_batch': {
    'uz': 'Parent batch',
    'en': 'Parent batch',
    'ru': 'Родительская партия',
  },
  'admin.production.note': {
    'uz': 'Izoh',
    'en': 'Note',
    'ru': 'Примечание',
  },
  'admin.production.qr_payload': {
    'uz': 'QR kodi / payload',
    'en': 'QR code / payload',
    'ru': 'QR-код / payload',
  },
  'admin.production.copied': {
    'uz': 'QR payload nusxalandi',
    'en': 'QR payload copied',
    'ru': 'QR payload скопирован',
  },
  'admin.production.wip_prefix': {
    'uz': 'WIP: {value}',
    'en': 'WIP: {value}',
    'ru': 'WIP: {value}',
  },
  'admin.production.flow_prefix': {
    'uz': 'Flow: {value}',
    'en': 'Flow: {value}',
    'ru': 'Поток: {value}',
  },
  'admin.production.stock_prefix': {
    'uz': 'Stock: {value}',
    'en': 'Stock: {value}',
    'ru': 'Склад: {value}',
  },
  'admin.production.qolip_title': {
    'uz': 'Order qoliplari',
    'en': 'Order molds',
    'ru': 'Формы заказа',
  },
  'admin.production.qolip_description': {
    'uz': 'Qolip ishlatilayotgan bo‘lsa band, ish tugasa avtomatik qaytadi.',
    'en':
        'A mold is busy while in use and returns automatically when the work is completed.',
    'ru':
        'Форма занята, пока используется, и автоматически возвращается после завершения работы.',
  },
  'admin.production.qolip_load_failed': {
    'uz': 'Qoliplar yuklanmadi',
    'en': 'Could not load molds',
    'ru': 'Не удалось загрузить формы',
  },
  'admin.production.qolip_product_missing': {
    'uz': 'Bu tayyor mahsulot katalogdan topilmadi',
    'en': 'This finished product was not found in the catalog',
    'ru': 'Готовый товар не найден в каталоге',
  },
  'admin.production.qolip_group_missing': {
    'uz': 'Bu tayyor mahsulotning guruhi aniqlanmadi',
    'en': 'The item group for this finished product is not set',
    'ru': 'Для готового товара не указана группа',
  },
  'admin.production.qolip_add_failed': {
    'uz': 'Qolip qo‘shish ma’lumotlari yuklanmadi',
    'en': 'Could not load data to add a mold',
    'ru': 'Не удалось загрузить данные для добавления формы',
  },
  'admin.production.qolip_retry': {
    'uz': 'Qayta urinish',
    'en': 'Retry',
    'ru': 'Повторить',
  },
  'admin.production.qolip_empty': {
    'uz': 'Bu tayyor mahsulotga hali qolip biriktirilmagan.',
    'en': 'No molds are assigned to this finished product yet.',
    'ru': 'Для этого готового товара формы пока не назначены.',
  },
  'admin.production.qolip_add': {
    'uz': 'Qolip qo‘shish',
    'en': 'Add mold',
    'ru': 'Добавить форму',
  },
  'admin.production.qolip_in_use': {
    'uz': 'Ishlatilmoqda',
    'en': 'In use',
    'ru': 'Используется',
  },
  'admin.production.qolip_available': {
    'uz': 'Bo‘sh',
    'en': 'Available',
    'ru': 'Свободна',
  },
};
