// Generated by large_library_splitter.dart; keep changes in the source library.
part of 'app_localizations.dart';

const _app_localizations_declarations__productionTranslations_resplitPart12 = {
  'qolip.checkouts.search_empty': {
    'uz': 'Qidiruvda topilmadi',
    'en': 'No matching records found',
    'ru': 'Совпадений не найдено',
  },
  'qolip.checkouts.loading': {
    'uz': 'Qarz daftari yuklanmoqda',
    'en': 'Loading checkout ledger',
    'ru': 'Загрузка журнала выдачи',
  },
  'qolip.checkouts.return_to': {
    'uz': 'Qayerga qaytarasiz?',
    'en': 'Where should this be returned?',
    'ru': 'Куда вернуть?',
  },
  'qolip.checkouts.returned': {
    'uz': '{item} {cell} ga qaytdi',
    'en': '{item} was returned to {cell}',
    'ru': '{item} возвращено в ячейку {cell}',
  },
  'qolip.checkouts.return_failed': {
    'uz': 'Qolip qaytarilmadi',
    'en': 'The mold could not be returned',
    'ru': 'Не удалось вернуть форму',
  },
  'qolip.checkouts.return_to_mold': {
    'uz': '{qolip} uchun yacheyka tanlang',
    'en': 'Select a cell for {qolip}',
    'ru': 'Выберите ячейку для {qolip}',
  },
  'qolip.checkouts.selection_cancel': {
    'uz': 'Tanlashni bekor qilish',
    'en': 'Cancel selection',
    'ru': 'Отменить выбор',
  },
  'qolip.checkouts.selection_summary': {
    'uz': '{count} ta tanlandi',
    'en': '{count} selected',
    'ru': 'Выбрано: {count}',
  },
  'qolip.checkouts.selection_return': {
    'uz': 'Tanlanganlarni qaytarish',
    'en': 'Return selected',
    'ru': 'Вернуть выбранные',
  },
  'qolip.checkouts.selection_returned': {
    'uz': '{count} ta qolip qaytdi',
    'en': '{count} molds were returned',
    'ru': 'Возвращено форм: {count}',
  },
  'qolip.checkouts.selection_returned_partial': {
    'uz': '{success} ta qaytdi, {failed} ta qaytmadi',
    'en': '{success} returned, {failed} failed',
    'ru': 'Возвращено: {success}, не вернулось: {failed}',
  },
  'qolip.checkouts.unknown_worker': {
    'uz': 'Noma’lum qolipchi',
    'en': 'Unknown worker',
    'ru': 'Неизвестный работник',
  },
  'qolip.checkouts.product': {
    'uz': 'Mahsulot',
    'en': 'Product',
    'ru': 'Товар',
  },
  'qolip.checkouts.item_code': {
    'uz': 'Item kodi',
    'en': 'Item code',
    'ru': 'Код позиции',
  },
  'qolip.checkouts.quantity': {
    'uz': 'Soni',
    'en': 'Quantity',
    'ru': 'Количество',
  },
  'qolip.checkouts.issued_at': {
    'uz': 'Berilgan vaqt',
    'en': 'Issued at',
    'ru': 'Время выдачи',
  },
  'qolip.checkouts.issued_to': {
    'uz': 'Kimga berilgan',
    'en': 'Issued to',
    'ru': 'Кому выдано',
  },
  'qolip.checkouts.mold_code': {
    'uz': 'Qolip kodi',
    'en': 'Mold code',
    'ru': 'Код формы',
  },
  'qolip.checkouts.size': {
    'uz': 'Razmer',
    'en': 'Size',
    'ru': 'Размер',
  },
  'qolip.checkouts.block': {
    'uz': 'Blok',
    'en': 'Block',
    'ru': 'Блок',
  },
  'qolip.checkouts.cell': {
    'uz': 'Joy',
    'en': 'Cell',
    'ru': 'Ячейка',
  },
  'qolip.checkouts.warehouse': {
    'uz': 'Ombor',
    'en': 'Warehouse',
    'ru': 'Склад',
  },
  'qolip.checkouts.checkout_id': {
    'uz': 'Checkout ID',
    'en': 'Checkout ID',
    'ru': 'ID выдачи',
  },
  'qolip.transfer.title': {
    'uz': 'Joylashuv transferi',
    'en': 'Location transfer',
    'ru': 'Перемещение по ячейкам',
  },
  'qolip.transfer.heading': {
    'uz': 'Qolipni boshqa joyga ko‘chirish',
    'en': 'Move a mold to another location',
    'ru': 'Переместить форму в другую ячейку',
  },
  'qolip.transfer.description': {
    'uz':
        'Manba qolipni tanlang, keyin boriladigan blok va yacheykani belgilang.',
    'en': 'Select the source mold, then choose the destination block and cell.',
    'ru': 'Выберите исходную форму, затем блок и ячейку назначения.',
  },
  'qolip.transfer.source_block': {
    'uz': 'Manba bloki',
    'en': 'Source block',
    'ru': 'Исходный блок',
  },
  'qolip.transfer.source_mold': {
    'uz': 'Ko‘chiriladigan qolip',
    'en': 'Mold to move',
    'ru': 'Форма для перемещения',
  },
  'qolip.transfer.target_block': {
    'uz': 'Boriladigan blok',
    'en': 'Destination block',
    'ru': 'Блок назначения',
  },
  'qolip.transfer.select_cell': {
    'uz': 'Yacheyka tanlash',
    'en': 'Select cell',
    'ru': 'Выбрать ячейку',
  },
  'qolip.transfer.cell': {
    'uz': 'Yacheyka: {cell}',
    'en': 'Cell: {cell}',
    'ru': 'Ячейка: {cell}',
  },
  'qolip.transfer.quantity': {
    'uz': 'Miqdor',
    'en': 'Quantity',
    'ru': 'Количество',
  },
  'qolip.transfer.max_quantity': {
    'uz': 'Maksimal {count} ta',
    'en': 'Maximum {count}',
    'ru': 'Максимум: {count}',
  },
  'qolip.transfer.move': {
    'uz': 'Joylashuvni ko‘chirish',
    'en': 'Move location',
    'ru': 'Переместить',
  },
  'qolip.transfer.moving': {
    'uz': 'Ko‘chirilmoqda...',
    'en': 'Moving...',
    'ru': 'Перемещение...',
  },
  'qolip.transfer.empty': {
    'uz': 'Blok mavjud emas',
    'en': 'No blocks available',
    'ru': 'Нет доступных блоков',
  },
  'qolip.transfer.source_required': {
    'uz': 'Avval ko‘chiriladigan qolipni tanlang',
    'en': 'Select a mold to move first',
    'ru': 'Сначала выберите форму для перемещения',
  },
  'qolip.transfer.cell_required': {
    'uz': 'Avval boriladigan yacheykani tanlang',
    'en': 'Select a destination cell first',
    'ru': 'Сначала выберите ячейку назначения',
  },
  'qolip.transfer.quantity_range': {
    'uz': 'Qolip soni 1 dan {max} gacha bo‘lishi kerak',
    'en': 'Quantity must be between 1 and {max}',
    'ru': 'Количество должно быть от 1 до {max}',
  },
  'qolip.transfer.invalid_cell': {
    'uz': 'Yacheyka noto‘g‘ri tanlangan',
    'en': 'The selected cell is invalid',
    'ru': 'Выбрана неверная ячейка',
  },
  'qolip.transfer.target_unconfirmed': {
    'uz': 'Server targetni tasdiqlamadi: {location}',
    'en': 'The server did not confirm the destination: {location}',
    'ru': 'Сервер не подтвердил назначение: {location}',
  },
  'qolip.transfer.moved': {
    'uz': '{item} {block} / {cell} ga ko‘chirildi',
    'en': '{item} was moved to {block} / {cell}',
    'ru': '{item} перемещено в {block} / {cell}',
  },
  'qolip.transfer.failed': {
    'uz': 'Ko‘chirish amalga oshmadi',
    'en': 'Could not move the mold',
    'ru': 'Не удалось переместить форму',
  },
  'qolip.cell_picker.title': {
    'uz': 'Joy tanlang',
    'en': 'Select a cell',
    'ru': 'Выберите ячейку',
  },
  'qolip.cell_picker.search_hint': {
    'uz': 'Masalan: A1, B3, C9',
    'en': 'For example: A1, B3, C9',
    'ru': 'Например: A1, B3, C9',
  },
  'qolip.cell_picker.no_match': {
    'uz': 'Mos joy topilmadi. A1 yoki B3 kabi yozing.',
    'en': 'No matching cells. Try a value such as A1 or B3.',
    'ru': 'Подходящие ячейки не найдены. Введите, например, A1 или B3.',
  },
  'qolip.cell_picker.select': {
    'uz': '{cell} — tanlash',
    'en': 'Select {cell}',
    'ru': 'Выбрать {cell}',
  },
  'qolip.cell_picker.other_matches': {
    'uz': 'Boshqa mos joylar',
    'en': 'Other matching cells',
    'ru': 'Другие подходящие ячейки',
  },
  'qolip.cell_picker.row': {
    'uz': 'Qator',
    'en': 'Row',
    'ru': 'Ряд',
  },
  'qolip.cell_picker.row_heading': {
    'uz': '{letter} qatori',
    'en': 'Row {letter}',
    'ru': 'Ряд {letter}',
  },
  'qolip.scanner.prompt.cell': {
    'uz': 'Yachayka QR kodini ramkaga keltiring',
    'en': 'Align the cell QR code within the frame',
    'ru': 'Поместите QR-код ячейки в рамку',
  },
  'qolip.scanner.prompt.mold': {
    'uz': 'Qolip QR kodini ramkaga keltiring',
    'en': 'Align the mold QR code within the frame',
    'ru': 'Поместите QR-код формы в рамку',
  },
  'qolip.scanner.prompt.universal': {
    'uz': 'Qolip yoki yachayka QR kodini ramkaga keltiring',
    'en': 'Align a mold or cell QR code within the frame',
    'ru': 'Поместите QR-код формы или ячейки в рамку',
  },
  'qolip.scanner.checking.cell': {
    'uz': 'Yachayka tekshirilmoqda...',
    'en': 'Checking cell...',
    'ru': 'Проверка ячейки...',
  },
  'qolip.scanner.checking.mold': {
    'uz': 'Qolip QR o‘qilmoqda...',
    'en': 'Reading mold QR code...',
    'ru': 'Чтение QR-кода формы...',
  },
  'qolip.scanner.checking.universal': {
    'uz': 'QR o‘qilmoqda...',
    'en': 'Reading QR code...',
    'ru': 'Чтение QR-кода...',
  },
  'qolip.scanner.title.cell': {
    'uz': 'Yachayka scan',
    'en': 'Scan cell QR',
    'ru': 'Сканировать QR ячейки',
  },
  'qolip.scanner.title.mold': {
    'uz': 'Qolip scan',
    'en': 'Scan mold QR',
    'ru': 'Сканировать QR формы',
  },
  'qolip.scanner.title.universal': {
    'uz': 'QR scan',
    'en': 'Scan QR',
    'ru': 'Сканировать QR',
  },
  'qolip.scanner.camera_failed': {
    'uz': 'Kamera ochilmadi',
    'en': 'Could not start the camera',
    'ru': 'Не удалось открыть камеру',
  },
  'qolip.scanner.camera_retry': {
    'uz': 'Kamera ochilmadi. Ruxsatlarni tekshirib qayta urinib ko‘ring.',
    'en': 'Could not start the camera. Check permissions and try again.',
    'ru':
        'Не удалось открыть камеру. Проверьте разрешения и повторите попытку.',
  },
  'qolip.scanner.not_found': {
    'uz': 'Bu QR yachayka uchun topilmadi.',
    'en': 'This QR code does not belong to a cell.',
    'ru': 'Этот QR-код не относится к ячейке.',
  },
  'qolip.scanner.empty': {
    'uz': 'Yachayka QR bo‘sh.',
    'en': 'The cell QR code is empty.',
    'ru': 'QR-код ячейки пуст.',
  },
  'qolip.scanner.check_failed': {
    'uz': 'Yachayka QR tekshirishda xatolik.',
    'en': 'Could not validate the cell QR code.',
    'ru': 'Ошибка проверки QR-кода ячейки.',
  },
  'qolip.scanner.unsupported': {
    'uz': 'Bu qurilmada QR scanner qo‘llab-quvvatlanmadi.',
    'en': 'QR scanning is not supported on this device.',
    'ru': 'Сканирование QR не поддерживается на этом устройстве.',
  },
};
