import 'package:flutter/widgets.dart';

import 'admin_localization.dart';

part 'app_localizations_AppLocalizations_methods_01.dart';
part 'app_localizations_AppLocalizations_methods_02.dart';
part 'app_localizations_declarations_part_01.dart';
part 'app_localizations__productionTranslations_resplit_collection_01.dart';
part 'app_localizations__productionTranslations_resplit_collection_02.dart';
part 'app_localizations__productionTranslations_resplit_collection_03.dart';
part 'app_localizations__productionTranslations_resplit_collection_04.dart';
part 'app_localizations__productionTranslations_resplit_collection_05.dart';
part 'app_localizations__productionTranslations_resplit_collection_06.dart';
part 'app_localizations__productionTranslations_resplit_collection_07.dart';
part 'app_localizations__productionTranslations_resplit_collection_08.dart';
part 'app_localizations__productionTranslations_resplit_collection_09.dart';
part 'app_localizations__productionTranslations_resplit_collection_10.dart';
part 'app_localizations__productionTranslations_resplit_collection_11.dart';
part 'app_localizations__productionTranslations_resplit_collection_12.dart';
part 'app_localizations__productionTranslations_resplit_collection_13.dart';
part 'app_localizations__productionTranslations_resplit_collection_14.dart';
part 'app_localizations_AppLocalizations_resplit_class.dart';
