// Generated by large_library_splitter.dart; keep changes in the source library.
part of 'returned_paint_sheet.dart';

extension __ReturnedPaintSheetStateAstPart01 on _ReturnedPaintSheetState {
  Color _fieldBorderColor(String label) {
    return switch (label) {
      'Mix' => const Color(0xFF8A6A4A),
      '1w Oq' || '7w Oq' => const Color(0xFFC9B9AA),
      'Qora' => const Color(0xFF202124),
      'Sariq' => const Color(0xFFE0B52D),
      'Qizil' => const Color(0xFFE53935),
      'Ko‘k' => const Color(0xFF1E88E5),
      'Spirt' => const Color(0xFF6AAED6),
      'Mix+' => const Color(0xFF8A6A4A),
      'Pantone+' => const Color(0xFF8E6BBE),
      _ => Theme.of(context).colorScheme.outlineVariant,
    };
  }

  InputDecoration _paintFieldDecoration(String label) {
    final base = appSurfaceInputDecoration(context, labelText: label);
    final color = _fieldBorderColor(label);
    return base.copyWith(
      border: OutlineInputBorder(
        borderRadius: BorderRadius.circular(12),
        borderSide: BorderSide(color: color, width: 1.2),
      ),
      enabledBorder: OutlineInputBorder(
        borderRadius: BorderRadius.circular(12),
        borderSide: BorderSide(color: color, width: 1.2),
      ),
      focusedBorder: OutlineInputBorder(
        borderRadius: BorderRadius.circular(12),
        borderSide: BorderSide(color: color, width: 1.8),
      ),
    );
  }

  String _paintStateKey(String paint, int usageIndex) =>
      '${usageIndex == 0 ? 'rasxot' : 'astatka'}:$paint';

  List<String> _resolvedFields(
    _ReturnedPaintOption option,
    int usageIndex,
  ) {
    final fields = option.fieldLabels ?? _returnedPaintFieldLabels;
    return widget.draft.fieldLabelsFor(
      _paintStateKey(option.label, usageIndex),
      fields,
    );
  }

  List<TextEditingController> _controllersForPaint(
    String paint,
    List<String> fieldLabels,
    int usageIndex,
  ) {
    final stateKey = _paintStateKey(paint, usageIndex);
    return _controllersForState(stateKey, fieldLabels);
  }

  List<TextEditingController> _controllersForState(
    String stateKey,
    List<String> fieldLabels,
  ) {
    final existing = _fieldControllersByPaint[stateKey];
    if (existing != null && existing.length == fieldLabels.length) {
      return existing;
    }
    for (final controller in existing ?? const <TextEditingController>[]) {
      controller.dispose();
    }
    final values = widget.draft.valuesFor(stateKey, fieldLabels.length);
    final controllers = [
      for (var index = 0; index < fieldLabels.length; index++)
        TextEditingController(text: values[index]),
    ];
    _fieldControllersByPaint[stateKey] = controllers;
    return controllers;
  }

  Widget? _completionIndicator(
    _ReturnedPaintOption option,
    int usageIndex,
  ) {
    if (option.label == 'Pantone') {
      final pantoneKey = _paintStateKey('Pantone', usageIndex);
      final mixKey = _paintStateKey('Pantone Mix', usageIndex);
      final pantoneFields = widget.draft.fieldLabelsFor(pantoneKey, const []);
      final mixFields = widget.draft.fieldLabelsFor(mixKey, const []);
      final filled = [
        ...widget.draft.valuesFor(pantoneKey, pantoneFields.length),
        ...widget.draft.valuesFor(mixKey, mixFields.length),
      ].map((value) => value.trim().isNotEmpty).toList();
      if (filled.every((value) => !value)) return null;
      return Icon(
        filled.every((value) => value)
            ? Icons.check_rounded
            : Icons.star_rounded,
        size: filled.every((value) => value) ? 17 : 16,
        color: option.foreground,
      );
    }
    final fields = _resolvedFields(option, usageIndex);
    final values = widget.draft.valuesFor(
      _paintStateKey(option.label, usageIndex),
      fields.length,
    );
    final filled = values.map((value) => value.trim().isNotEmpty).toList();
    if (filled.every((value) => !value)) return null;
    return Icon(
      filled.every((value) => value) ? Icons.check_rounded : Icons.star_rounded,
      size: filled.every((value) => value) ? 17 : 16,
      color: option.foreground,
    );
  }

  void _updateFieldValue({
    required String paint,
    required int index,
    required String value,
    required int usageIndex,
  }) {
    final stateKey = _paintStateKey(paint, usageIndex);
    final baseFields = _selectedFieldLabels ?? _returnedPaintFieldLabels;
    _updateStateFieldValue(
      stateKey: stateKey,
      index: index,
      value: value,
      baseFields: baseFields,
    );
  }

  void _updateStateFieldValue({
    required String stateKey,
    required int index,
    required String value,
    required List<String> baseFields,
  }) {
    final fields = widget.draft.fieldLabelsFor(stateKey, baseFields);
    widget.draft.setValue(stateKey, index, value, fields.length);
    setState(() => _error = '');
  }

  Future<void> _addNamedField(
    String paint,
    int usageIndex, {
    String? stateKeyOverride,
  }) async {
    final stateKey = stateKeyOverride ?? _paintStateKey(paint, usageIndex);
    final existing = widget.draft.dynamicFieldLabelsFor(stateKey);
    var enteredLabel = '';
    var enteredValue = '';
    final field = await showDialog<List<String>>(
      context: context,
      builder: (context) => AlertDialog(
        insetPadding: const EdgeInsets.symmetric(horizontal: 24, vertical: 24),
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(24)),
        titlePadding: const EdgeInsets.fromLTRB(24, 22, 24, 8),
        contentPadding: const EdgeInsets.fromLTRB(24, 0, 24, 8),
        actionsPadding: const EdgeInsets.fromLTRB(24, 0, 24, 22),
        title: Text('$paint maydoni nomi'),
        content: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            TextField(
              key: const ValueKey('returned-paint-field-name'),
              autofocus: true,
              textCapitalization: TextCapitalization.words,
              decoration: const InputDecoration(
                labelText: 'Majburiy nom',
                hintText: 'Masalan: Pantone Blue',
              ),
              onChanged: (value) => enteredLabel = value,
            ),
            const SizedBox(height: 12),
            TextField(
              key: const ValueKey('returned-paint-field-value'),
              keyboardType:
                  const TextInputType.numberWithOptions(decimal: true),
              inputFormatters: <TextInputFormatter>[
                _returnedPaintNumberFormatter(),
              ],
              decoration: const InputDecoration(
                labelText: 'Qiymat',
                hintText: 'Masalan: 12.5',
              ),
              onChanged: (value) => enteredValue = value,
            ),
          ],
        ),
        actions: [
          SizedBox(
            width: double.infinity,
            height: 48,
            child: OutlinedButton(
              onPressed: () => Navigator.of(context).pop(),
              child: const Text('Bekor qilish'),
            ),
          ),
          const SizedBox(height: 10),
          SizedBox(
            width: double.infinity,
            height: 48,
            child: FilledButton(
              key: const ValueKey('returned-paint-confirm-field-name'),
              onPressed: () {
                final label = enteredLabel.trim();
                final value = enteredValue.trim().replaceAll(',', '.');
                final parsed = double.tryParse(value);
                if (label.isNotEmpty &&
                    value.isNotEmpty &&
                    parsed != null &&
                    parsed.isFinite &&
                    parsed >= 0) {
                  Navigator.of(context).pop([label, value]);
                }
              },
              child: const Text('Qo‘shish'),
            ),
          ),
        ],
      ),
    );
    if (!mounted || field == null || field.length != 2) return;
    final label = field[0].trim();
    final value = field[1].trim();
    if (existing.any((value) => value.toLowerCase() == label.toLowerCase())) {
      setState(() => _error = 'Bu nom allaqachon qo‘shilgan.');
      return;
    }
    widget.draft.addNamedField(stateKey, label);
    final baseFields = _selectedFieldLabels ?? _returnedPaintFieldLabels;
    final fields = widget.draft.fieldLabelsFor(stateKey, baseFields);
    widget.draft.setValue(stateKey, fields.length - 1, value, fields.length);
    setState(() => _error = '');
  }

  Future<ImageSource?> _chooseImageSource() {
    return showModalBottomSheet<ImageSource>(
      context: context,
      useSafeArea: true,
      showDragHandle: true,
      builder: (context) {
        return SafeArea(
          child: Padding(
            padding: const EdgeInsets.fromLTRB(12, 0, 12, 12),
            child: Column(
              mainAxisSize: MainAxisSize.min,
              children: [
                ListTile(
                  leading: const Icon(Icons.camera_alt_outlined),
                  title: const Text('Kamera'),
                  onTap: () => Navigator.of(context).pop(ImageSource.camera),
                ),
                ListTile(
                  leading: const Icon(Icons.photo_library_outlined),
                  title: const Text('Gallery'),
                  onTap: () => Navigator.of(context).pop(ImageSource.gallery),
                ),
              ],
            ),
          ),
        );
      },
    );
  }

  Future<void> _chooseAndPickImage() async {
    if (_uploadingImage || _removingImage) return;
    final source = await _chooseImageSource();
    if (!mounted || source == null) return;
    await _pickImage(source);
  }

  Future<void> _pickImage(ImageSource source) async {
    if (_uploadingImage || _removingImage) return;
    final picked = await _imagePicker.pickImage(
      source: source,
      maxWidth: 1800,
      maxHeight: 1800,
      imageQuality: 84,
    );
    if (picked == null) return;
    setState(() {
      _uploadingImage = true;
      _error = '';
    });
    final previous = widget.draft.image;
    try {
      final bytes = await picked.readAsBytes();
      if (bytes.isEmpty) {
        throw const MobileApiException(
          code: 'returned_paint_image_empty',
          message: 'Tanlangan rasm bo‘sh',
        );
      }
      if (bytes.length > 6 * 1024 * 1024) {
        throw const MobileApiException(
          code: 'returned_paint_image_too_large',
          message: 'Rasm hajmi 6 MB dan oshmasligi kerak',
        );
      }
      final image = await MobileApi.instance.uploadReturnedPaintImage(
        orderId: widget.orderId,
        apparatus: widget.apparatus,
        bytes: bytes,
        filename: picked.name,
        mime: _imageMime(picked),
      );
      widget.draft.setImage(image);
      if (previous != null && previous.imageId != image.imageId) {
        try {
          await MobileApi.instance.deleteReturnedPaintImage(
            previous.imageId,
            orderId: widget.orderId,
          );
        } catch (_) {
          // The new order-bound image is already saved; an unattached old image
          // must not roll the user's replacement back.
        }
      }
    } catch (error) {
      if (mounted) _error = _errorText(error, 'Rasm yuklanmadi');
    } finally {
      if (mounted) setState(() => _uploadingImage = false);
    }
  }

  Future<void> _removeImage() async {
    final image = widget.draft.image;
    if (image == null || _uploadingImage || _removingImage) return;
    setState(() {
      _removingImage = true;
      _error = '';
    });
    try {
      await MobileApi.instance.deleteReturnedPaintImage(
        image.imageId,
        orderId: widget.orderId,
      );
      widget.draft.setImage(null);
    } catch (error) {
      if (mounted) _error = _errorText(error, 'Rasm olib tashlanmadi');
    } finally {
      if (mounted) setState(() => _removingImage = false);
    }
  }

  Future<void> _save() async {
    final callback = widget.onSave;
    if (callback == null || _saving) return;
    if (returnedPaintDraftHasInvalidValues(widget.draft)) {
      setState(() {
        _error = 'Qaytarilgan bo‘yoq qiymatlarini to‘g‘ri raqamda kiriting.';
      });
      return;
    }
    final items = returnedPaintItemsFromDraft(widget.draft);
    if (!returnedPaintHasMinimumFieldsPerUsage(items)) {
      final rasxotCount = returnedPaintFilledFieldCountForUsage(
        items,
        'rasxot',
      );
      final astatkaCount = returnedPaintFilledFieldCountForUsage(
        items,
        'astatka',
      );
      setState(() {
        _error = 'Har bir tabda kamida 3 ta maydon to‘ldiring. '
            'Rasxot: $rasxotCount/3, Astatka: $astatkaCount/3.';
      });
      return;
    }
    setState(() {
      _saving = true;
      _error = '';
    });
    try {
      await callback(items);
      if (mounted) Navigator.of(context).pop();
    } catch (error) {
      if (mounted) {
        setState(() {
          _error = _errorText(error, 'Qaytarilgan bo‘yoq saqlanmadi');
        });
      }
    } finally {
      if (mounted) setState(() => _saving = false);
    }
  }
}
