// Generated by large_library_splitter.dart; keep changes in the source library.
part of 'godex_rps_renderer.dart';

Uint8List _GodexRpsRenderer__renderQrGraphic_resplit2AstPart(
    String payload, int qrBoxDots) {
  if (payload.isEmpty) throw StateError('qr payload is empty');
  final qr = _QrCode.encodeText(payload);
  const quietZone = 4;
  final moduleCount = qr.size + quietZone * 2;
  final moduleDots = math.max(qrBoxDots ~/ moduleCount, 1);
  final drawn = moduleCount * moduleDots;
  final offset = math.max(qrBoxDots - drawn, 0) ~/ 2;
  final bitmap = _MonoBitmap.filled(qrBoxDots, qrBoxDots, light: true);
  for (var y = 0; y < qr.size; y++) {
    for (var x = 0; x < qr.size; x++) {
      if (!qr.getModule(x, y)) continue;
      final startX = offset + (x + quietZone) * moduleDots;
      final startY = offset + (y + quietZone) * moduleDots;
      for (var dy = 0; dy < moduleDots; dy++) {
        for (var dx = 0; dx < moduleDots; dx++) {
          bitmap.setLight(startX + dx, startY + dy, false);
        }
      }
    }
  }
  return GodexRpsRenderer._encodeMonoBmp(bitmap);
}

void _GodexRpsRenderer__drawText_resplit2AstPart(
    _MonoBitmap canvas, int x, int y, int scale, String text) {
  var cursor = x;
  for (final ch in text.split('')) {
    GodexRpsRenderer._drawChar(canvas, cursor, y, scale, ch.toUpperCase());
    cursor += 6 * scale;
  }
}

void _GodexRpsRenderer__drawChar_resplit2AstPart(
    _MonoBitmap canvas, int x, int y, int scale, String ch) {
  if (ch == ' ') return;
  final glyph = _glyphRows[ch] ?? const [31, 17, 21, 21, 21, 17, 31];
  for (var rowIndex = 0; rowIndex < glyph.length; rowIndex++) {
    for (var col = 0; col < 5; col++) {
      if ((glyph[rowIndex] & (0x10 >> col)) == 0) continue;
      for (var dy = 0; dy < scale; dy++) {
        for (var dx = 0; dx < scale; dx++) {
          canvas.setLight(
              x + col * scale + dx, y + rowIndex * scale + dy, false);
        }
      }
    }
  }
}

Uint8List _GodexRpsRenderer__encodeMonoBmp_resplit2AstPart(_MonoBitmap src) {
  final rowBytes = ((src.width + 31) ~/ 32) * 4;
  final pixelBytes = rowBytes * src.height;
  const headerBytes = 14 + 40 + 8;
  final out = BytesBuilder(copy: false);
  void u16(int value) {
    out.addByte(value & 0xff);
    out.addByte((value >> 8) & 0xff);
  }

  void u32(int value) {
    out.addByte(value & 0xff);
    out.addByte((value >> 8) & 0xff);
    out.addByte((value >> 16) & 0xff);
    out.addByte((value >> 24) & 0xff);
  }

  out.add(const [0x42, 0x4d]);
  u32(headerBytes + pixelBytes);
  u16(0);
  u16(0);
  u32(headerBytes);
  u32(40);
  u32(src.width);
  u32(src.height);
  u16(1);
  u16(1);
  u32(0);
  u32(pixelBytes);
  u32(0);
  u32(0);
  u32(2);
  u32(2);
  out.add(const [0, 0, 0, 0, 0xff, 0xff, 0xff, 0]);
  for (var y = src.height - 1; y >= 0; y--) {
    final row = Uint8List(rowBytes);
    for (var x = 0; x < src.width; x++) {
      if (src.isLight(x, y)) {
        row[x ~/ 8] |= 0x80 >> (x % 8);
      }
    }
    out.add(row);
  }
  return out.takeBytes();
}

List<String> _GodexRpsRenderer__wrapTextForEzpl_resplit2AstPart(
  String text,
  int widthDots,
  int xMul,
  int pitchDots,
  int minChars,
) {
  final cleanText = GodexRpsRenderer._sanitizeLabelText(text);
  if (cleanText.isEmpty) return const [''];
  final charWidth = math.max(pitchDots * math.max(xMul, 1), 1);
  final widthChars = math.max(minChars, math.max(widthDots ~/ charWidth, 0));
  final lines = GodexRpsRenderer._wrapWordsByCharCount(cleanText, widthChars,
      breakLong: false);
  return lines.any((line) => line.length > widthChars)
      ? GodexRpsRenderer._wrapWordsByCharCount(cleanText, widthChars,
          breakLong: true)
      : lines;
}

List<String> _GodexRpsRenderer__wrapWordsByCharCount_resplit2AstPart(
    String text, int width,
    {required bool breakLong}) {
  final lines = <String>[];
  var current = '';
  for (final word
      in text.split(RegExp(r'\s+')).where((word) => word.isNotEmpty)) {
    final candidate = current.isEmpty ? word : '$current $word';
    if (candidate.length <= width) {
      current = candidate;
      continue;
    }
    if (current.isNotEmpty) lines.add(current);
    if (!breakLong || word.length <= width) {
      current = word;
      continue;
    }
    var rest = word;
    while (rest.length > width) {
      lines.add(rest.substring(0, width));
      rest = rest.substring(width);
    }
    current = rest;
  }
  if (current.isNotEmpty) lines.add(current);
  return lines.isEmpty ? [text] : lines;
}

String _GodexRpsRenderer__uppercaseClean_resplit2AstPart(String value) =>
    GodexRpsRenderer._sanitizeLabelText(value).toUpperCase();

String _GodexRpsRenderer__sanitizeLabelText_resplit2AstPart(String value) {
  return value
      .replaceAll(RegExp(r'[\r\n\^~]'), ' ')
      .trim()
      .split(RegExp(r'\s+'))
      .where((part) => part.isNotEmpty)
      .join(' ');
}

String _GodexRpsRenderer__normalizeKgValue_resplit2AstPart(String text) {
  var value = GodexRpsRenderer._sanitizeLabelText(text);
  final lowered = value.toLowerCase();
  if (lowered.startsWith('kg:')) value = value.substring(3).trim();
  if (value.toLowerCase().endsWith('kg')) {
    value = value.substring(0, value.length - 2).trim();
  }
  final parsed = double.tryParse(value.replaceAll(',', '.'));
  if (parsed == null || !parsed.isFinite) return value;
  var formatted = (parsed * 10).round().toString();
  formatted = (int.parse(formatted) / 10).toStringAsFixed(1);
  while (formatted.contains('.') && formatted.endsWith('0')) {
    formatted = formatted.substring(0, formatted.length - 1);
  }
  if (formatted.endsWith('.')) {
    formatted = formatted.substring(0, formatted.length - 1);
  }
  return formatted;
}

Uint8List _GodexRpsRenderer__ascii_resplit2AstPart(String value) =>
    Uint8List.fromList(value.codeUnits.map((unit) => unit & 0xff).toList());
