// Generated by large_library_splitter.dart; keep changes in the source library.
part of 'reliable_mobile_scanner.dart';

class ReliableScannerSession implements Listenable {
  static const Duration _startTimeout = Duration(seconds: 8);
  static const Duration _releaseTimeout = Duration(seconds: 4);

  ReliableScannerSession({
    Size? cameraResolution,
    CameraLensType lensType = CameraLensType.any,
    DetectionSpeed detectionSpeed = DetectionSpeed.normal,
    int detectionTimeoutMs = 250,
    CameraFacing facing = CameraFacing.back,
    List<BarcodeFormat> formats = const <BarcodeFormat>[],
    bool returnImage = false,
    bool torchEnabled = false,
    bool invertImage = false,
    bool autoZoom = false,
    double? initialZoom,
  }) : this._(
          controller: MobileScannerController(
            autoStart: false,
            cameraResolution: cameraResolution,
            lensType: lensType,
            detectionSpeed: detectionSpeed,
            detectionTimeoutMs: detectionTimeoutMs,
            facing: facing,
            formats: formats,
            returnImage: returnImage,
            torchEnabled: torchEnabled,
            invertImage: invertImage,
            autoZoom: autoZoom,
            initialZoom: initialZoom,
          ),
          coordinator: _appScannerCoordinator,
        );

  @visibleForTesting
  ReliableScannerSession.testing({
    required ReliableScannerDriver driver,
    required ReliableScannerCoordinator coordinator,
  }) : this._(
          driver: driver,
          coordinator: coordinator,
        );

  ReliableScannerSession._({
    MobileScannerController? controller,
    ReliableScannerDriver? driver,
    required ReliableScannerCoordinator coordinator,
  })  : assert(controller != null || driver != null),
        _controller = controller,
        _driver = driver ?? _MobileScannerDriver(controller!),
        _coordinator = coordinator;

  final MobileScannerController? _controller;
  final ReliableScannerDriver _driver;
  final ReliableScannerCoordinator _coordinator;
  final _ReliableScannerNotifier _notifier = _ReliableScannerNotifier();

  ReliableScannerPhase _phase = ReliableScannerPhase.idle;
  Object? _lastError;
  bool _attached = false;
  bool _routeVisible = true;
  bool _appResumed = true;
  bool _requested = true;
  bool _disposed = false;
  bool _driverDisposed = false;
  bool _listenersDisposed = false;
  bool _forceRestart = false;
  bool _detectionRecoveryInFlight = false;
  int _priority = 0;
  int _recoveryCount = 0;

  MobileScannerController get controller {
    final controller = _controller;
    if (controller == null) {
      throw StateError('A testing scanner session has no mobile controller.');
    }
    return controller;
  }

  ReliableScannerPhase get phase => _phase;

  Object? get lastError => _lastError;

  int get recoveryCount => _recoveryCount;

  Future<void> get settled => _coordinator.settled;

  bool get _shouldRun =>
      !_disposed && _attached && _routeVisible && _appResumed && _requested;

  Future<void> attach() {
    if (_disposed) {
      return Future<void>.value();
    }
    _attached = true;
    return _coordinator.reconcile(this, promote: true);
  }

  Future<void> detach() {
    if (_disposed) {
      return _coordinator.settled;
    }
    _attached = false;
    return _coordinator.reconcile(this);
  }

  Future<void> setRouteVisible(bool visible) {
    if (_disposed || _routeVisible == visible) {
      return Future<void>.value();
    }
    _routeVisible = visible;
    if (visible) {
      _forceRestart = true;
    }
    return _coordinator.reconcile(this, promote: visible);
  }

  Future<void> setAppLifecycleState(AppLifecycleState state) {
    final resumed = state == AppLifecycleState.resumed;
    if (_disposed || _appResumed == resumed) {
      return Future<void>.value();
    }
    _appResumed = resumed;
    if (resumed) {
      _forceRestart = true;
    }
    return _coordinator.reconcile(this, promote: resumed);
  }

  Future<bool> start({bool forceRestart = false}) async {
    if (_disposed) {
      return false;
    }
    _requested = true;
    _forceRestart = _forceRestart || forceRestart;
    await _coordinator.reconcile(this, promote: true);
    return _phase == ReliableScannerPhase.running;
  }

  Future<void> stop() {
    if (_disposed) {
      return _coordinator.settled;
    }
    _requested = false;
    return _coordinator.reconcile(this);
  }

  Future<bool> retry() => start(forceRestart: true);

  void handleDetectionError(Object error, StackTrace stackTrace) {
    if (_disposed) {
      return;
    }

    _lastError = error;
    try {
      FlutterError.reportError(
        FlutterErrorDetails(
          exception: error,
          stack: stackTrace,
          library: 'reliable mobile scanner',
          context: ErrorDescription('while decoding a camera frame'),
        ),
      );
    } catch (_) {
      // Error reporting must not prevent the camera recovery attempt.
    }

    if (_detectionRecoveryInFlight) {
      return;
    }
    _detectionRecoveryInFlight = true;
    unawaited(_recoverAfterDetectionError());
  }

  Future<void> _recoverAfterDetectionError() async {
    try {
      await retry();
    } finally {
      _detectionRecoveryInFlight = false;
    }
  }

  Future<void> dispose() async {
    if (_disposed) {
      await _coordinator.settled;
      return;
    }
    _disposed = true;
    _requested = false;
    await _coordinator.reconcile(this);
    _notifier.dispose();
    _listenersDisposed = true;
  }

  Future<bool> _startDriver({required bool forceRestart}) async {
    if (_disposed || !_shouldRun) {
      return false;
    }
    if (_driver.isRunning && !forceRestart) {
      _lastError = null;
      _setPhase(ReliableScannerPhase.running);
      return true;
    }

    Object? startError;
    for (var attempt = 0; attempt < 2; attempt += 1) {
      if (_disposed || !_shouldRun) {
        return false;
      }
      if ((forceRestart && _driver.isRunning) || attempt > 0) {
        await _safeStopDriver();
      }
      _setPhase(
        attempt == 0
            ? ReliableScannerPhase.starting
            : ReliableScannerPhase.recovering,
      );
      try {
        final startOperation = _driver.start();
        if (_driver.hasCameraPermission) {
          await startOperation.timeout(_startTimeout);
        } else {
          // Permission prompts are user-driven and must not be timed out.
          await startOperation;
        }
        if (_driver.isRunning) {
          _lastError = null;
          _setPhase(ReliableScannerPhase.running);
          return true;
        }
        startError = _driver.error ??
            StateError('Scanner start completed without a running camera.');
      } catch (error) {
        startError = error;
      }
      if (attempt == 0) {
        _recoveryCount += 1;
      }
    }

    _lastError = startError ?? StateError('Scanner failed to start.');
    _setPhase(ReliableScannerPhase.error);
    return false;
  }

  Future<void> _stopDriver() async {
    if (_driverDisposed) {
      return;
    }
    _setPhase(ReliableScannerPhase.stopping);
    await _safeStopDriver();
    if (!_disposed && _phase != ReliableScannerPhase.error) {
      _setPhase(ReliableScannerPhase.suspended);
    }
  }

  Future<void> _safeStopDriver() async {
    try {
      await _driver.stop().timeout(_releaseTimeout);
    } catch (error) {
      _lastError = error;
    }
  }

  Future<void> _disposeDriver() async {
    if (_driverDisposed) {
      return;
    }
    _driverDisposed = true;
    try {
      await _driver.dispose().timeout(_releaseTimeout);
    } catch (error) {
      _lastError = error;
    }
    _setPhase(ReliableScannerPhase.disposed);
  }

  void _recordCoordinatorError(Object error) {
    _lastError = error;
    _setPhase(ReliableScannerPhase.error);
  }

  void _setPhase(ReliableScannerPhase next) {
    if (_phase == next) {
      return;
    }
    _phase = next;
    if (!_listenersDisposed) {
      _notifier.emit();
    }
  }

  @override
  void addListener(VoidCallback listener) => _notifier.addListener(listener);

  @override
  void removeListener(VoidCallback listener) =>
      _notifier.removeListener(listener);
}

class _ReliableScannerNotifier extends ChangeNotifier {
  void emit() => notifyListeners();
}

class _MobileScannerDriver implements ReliableScannerDriver {
  const _MobileScannerDriver(this.controller);

  final MobileScannerController controller;

  @override
  Object? get error => controller.value.error;

  @override
  bool get hasCameraPermission => controller.value.hasCameraPermission;

  @override
  bool get isRunning => controller.value.isRunning;

  @override
  Future<void> dispose() => controller.dispose();

  @override
  Future<void> start() => controller.start();

  @override
  Future<void> stop() => controller.stop();
}

class ReliableScannerLifecycle extends StatefulWidget {
  const ReliableScannerLifecycle({
    super.key,
    required this.session,
    required this.child,
    this.routeObserver,
  });

  final ReliableScannerSession session;
  final Widget child;
  final RouteObserver<ModalRoute<dynamic>>? routeObserver;

  @override
  State<ReliableScannerLifecycle> createState() =>
      _ReliableScannerLifecycleState();
}
