// Generated by large_library_splitter.dart; keep changes in the source library.
part of 'test_mode_demo_data.dart';

const _test_mode_demo_data_TestModeDemoData_resplit_class_TestModeDemoData_items_resplit2Value =
    [
  SupplierItem(
    code: 'DEMO-HOTLUNCH',
    name: 'Hotlunch',
    uom: 'Dona',
    warehouse: 'Tayyor mahsulot ombori - DEMO',
    itemGroup: 'Tayyor mahsulot',
    customerNames: ['Demo haridor'],
  ),
  SupplierItem(
    code: 'DEMO-CPP',
    name: 'CPP sous',
    uom: 'Kg',
    warehouse: 'Xomashyo ombori - DEMO',
    itemGroup: 'Demo xomashyo',
  ),
  SupplierItem(
    code: 'DEMO-INK',
    name: 'Demo kraska',
    uom: 'Kg',
    warehouse: '',
    itemGroup: 'Kraska',
  ),
  SupplierItem(
    code: 'DEMO-PACK',
    name: 'Qadoq quti',
    uom: 'Dona',
    warehouse: 'Qadoqlash ombori - DEMO',
    itemGroup: 'Demo qadoqlash',
  ),
  SupplierItem(
    code: 'DEMO-SALAD',
    name: 'Salat set',
    uom: 'Dona',
    warehouse: 'Tayyor mahsulot ombori - DEMO',
    itemGroup: 'Tayyor mahsulot',
    customerNames: ['Demo filial'],
  ),
  SupplierItem(
    code: 'DEMO-DRINK',
    name: 'Demo ichimlik',
    uom: 'Dona',
    warehouse: '',
    itemGroup: 'Ichimlik',
  ),
];
