// Generated by large_library_splitter.dart; keep changes in the source library.
part of 'werka_detail_screen.dart';

class _ReceiptActionSegment extends StatelessWidget {
  const _ReceiptActionSegment({
    required this.label,
    required this.backgroundColor,
    required this.foregroundColor,
    required this.borderColor,
    required this.borderRadius,
    required this.onTap,
    this.icon,
    this.textStyle,
  });

  final String label;
  final Color backgroundColor;
  final Color foregroundColor;
  final Color borderColor;
  final BorderRadius borderRadius;
  final VoidCallback? onTap;
  final IconData? icon;
  final TextStyle? textStyle;

  @override
  Widget build(BuildContext context) {
    return Material(
      color: Colors.transparent,
      shape: RoundedRectangleBorder(borderRadius: borderRadius),
      clipBehavior: Clip.antiAlias,
      child: InkWell(
        onTap: onTap,
        child: Ink(
          decoration: BoxDecoration(
            color: onTap == null
                ? backgroundColor.withValues(alpha: 0.56)
                : backgroundColor,
            borderRadius: borderRadius,
            border: Border.all(color: borderColor),
          ),
          child: Center(
            child: Padding(
              padding: const EdgeInsets.symmetric(horizontal: 10),
              child: Row(
                mainAxisSize: MainAxisSize.min,
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  Flexible(
                    child: Text(
                      label,
                      maxLines: 1,
                      overflow: TextOverflow.ellipsis,
                      textAlign: TextAlign.center,
                      style: textStyle?.copyWith(color: foregroundColor),
                    ),
                  ),
                  if (icon != null) ...[
                    const SizedBox(width: 4),
                    Icon(icon, size: 19, color: foregroundColor),
                  ],
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }
}

class _QuantityFieldRow extends StatelessWidget {
  const _QuantityFieldRow({
    required this.controller,
    required this.unit,
    required this.textTheme,
    required this.scheme,
    required this.hintText,
    this.readOnly = false,
    this.labelText,
  });

  final TextEditingController controller;
  final String unit;
  final TextTheme textTheme;
  final ColorScheme scheme;
  final String hintText;
  final bool readOnly;
  final String? labelText;

  @override
  Widget build(BuildContext context) {
    final borderRadius = BorderRadius.circular(14);
    final fieldBorder = OutlineInputBorder(
      borderRadius: borderRadius,
      borderSide: BorderSide(color: scheme.outlineVariant),
    );
    return Row(
      crossAxisAlignment: CrossAxisAlignment.end,
      children: [
        SizedBox(
          width: 176,
          child: TextField(
            controller: controller,
            keyboardType: TextInputType.number,
            inputFormatters: [
              FilteringTextInputFormatter.digitsOnly,
              const _MaxNumericValueFormatter(100000),
            ],
            textAlign: TextAlign.right,
            style: textTheme.headlineMedium?.copyWith(
              fontSize: 30,
              height: 1.1,
              fontWeight: FontWeight.w800,
            ),
            readOnly: readOnly,
            decoration: InputDecoration(
              labelText: labelText,
              hintText: hintText,
              contentPadding: const EdgeInsets.fromLTRB(18, 12, 18, 12),
              border: fieldBorder,
              enabledBorder: fieldBorder,
              focusedBorder: OutlineInputBorder(
                borderRadius: borderRadius,
                borderSide: BorderSide(color: scheme.primary, width: 1.6),
              ),
            ),
          ),
        ),
        const SizedBox(width: 12),
        Padding(
          padding: const EdgeInsets.only(bottom: 12),
          child: Text(
            unit,
            style: textTheme.titleLarge?.copyWith(
              fontSize: 18,
              color: scheme.onSurfaceVariant,
              fontWeight: FontWeight.w700,
            ),
          ),
        ),
      ],
    );
  }
}

class _MaxNumericValueFormatter extends TextInputFormatter {
  const _MaxNumericValueFormatter(this.maxValue);

  final int maxValue;

  @override
  TextEditingValue formatEditUpdate(
    TextEditingValue oldValue,
    TextEditingValue newValue,
  ) {
    final text = newValue.text;
    if (text.isEmpty) {
      return newValue;
    }
    final value = int.tryParse(text);
    if (value == null || value > maxValue) {
      return oldValue;
    }
    return newValue;
  }
}

class _WerkaDetailInfoRow extends StatelessWidget {
  const _WerkaDetailInfoRow({required this.label, required this.value});

  final String label;
  final String value;

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final scheme = theme.colorScheme;
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 16),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Expanded(
            child: Text(
              label,
              style: theme.textTheme.bodyMedium?.copyWith(
                color: scheme.onSurfaceVariant,
              ),
            ),
          ),
          const SizedBox(width: 16),
          Flexible(
            child: Text(
              value,
              textAlign: TextAlign.right,
              style: theme.textTheme.titleMedium,
            ),
          ),
        ],
      ),
    );
  }
}
