// Generated by large_library_splitter.dart; keep changes in the source library.
part of '../mobile_api.dart';

void resetMobileApiQolipTestModeData() {
  _testModeQolipLocations.clear();
  _testModeQolipSpecs.clear();
  _testModeFirstQolipCodes.clear();
  _testModeQolipCheckouts.clear();
  _testModeQolipBlocks
    ..clear()
    ..addAll(const [
      QolipBlock(name: 'A', warehouse: 'Qolip ombori'),
      QolipBlock(name: 'B', warehouse: 'Qolip ombori'),
    ]);
}

String qolipErrorMessage(
  Object error, {
  String fallback = 'Amal bajarilmadi',
  AppLocalizations? l10n,
}) {
  final code = switch (error) {
    MobileApiException(code: final value) => value,
    _ => error.toString(),
  };
  final localized = l10n?.qolipErrorText(code);
  if (localized != null && localized.isNotEmpty) {
    return localized;
  }
  final normalizedCode = code.trim().toLowerCase();
  return switch (normalizedCode) {
    'insufficient_stock' => 'Joyda yetarli qolip qolmadi',
    'location_not_found' => 'Qolip joyi topilmadi',
    'location_invalid' => 'Joy noto‘g‘ri tanlangan',
    'checkout_not_found' => 'Berilgan qolip topilmadi',
    'checkout_not_returnable' => 'Bu qolipni qaytarib bo‘lmaydi',
    'qolip_checkout_required' => 'Qolip avval workerga qarzga berilishi kerak',
    'qolip_checkout_assigned_to_another_worker' =>
      'Qolip boshqa workerga berilgan',
    'worker_required' => 'Ishchini tanlang',
    'worker_not_found' => 'Ishchi topilmadi',
    'quantity_required' => 'Qolip soni noto‘g‘ri',
    'location_identity_mismatch' =>
      'Bu joyda boshqa qolip bor. Avval mavjud qolipni ko‘chiring',
    'qolip_in_use' =>
      'Qolip ishchiga berilgan yoki aktiv orderda ishlatilmoqda',
    'qolip_code_conflict' => 'Bu qolip code allaqachon mavjud',
    'panton_limit_exceeded' =>
      'Panton 1–100 band. Yangi Panton biriktirib bo‘lmaydi',
    'block_in_use' =>
      'Blokda qolip yoki qaytarilmagan berish bor. Uni o‘chirib bo‘lmaydi',
    'block_exists' => 'Bu nomdagi blok allaqachon mavjud',
    'block_not_found' => 'Blok topilmadi',
    'forbidden' => 'Bu amal uchun ruxsat yo‘q',
    'unauthorized' => 'Sessiya tugagan. Qayta kiring',
    _ when normalizedCode.contains('insufficient_stock') =>
      'Joyda yetarli qolip qolmadi',
    _ when normalizedCode.contains('location_not_found') =>
      'Qolip joyi topilmadi',
    _ => fallback,
  };
}

class QolipProductSpecBatchItem {
  const QolipProductSpecBatchItem({
    required this.qolipCode,
    required this.size,
    this.qolipColor = '',
  });

  final String qolipCode;
  final int size;
  final String qolipColor;
}

String _testModeQolipLocationId({
  required String block,
  required String itemCode,
  required String qolipCode,
  required int size,
  required String rowLetter,
  int? columnNumber,
}) {
  return [
    block.trim(),
    itemCode.trim(),
    qolipCode.trim(),
    size,
    rowLetter.trim(),
    columnNumber ?? 0,
  ].join(':');
}

class QolipCellQrPrintResult {
  const QolipCellQrPrintResult({required this.cellQr, required this.printJob});

  final QolipCellQr cellQr;
  final UsbRpsPrintRequest printJob;

  String get id => cellQr.id;
  String get block => cellQr.block;
  String get warehouse => cellQr.warehouse;
  String get rowLetter => cellQr.rowLetter;
  int get columnNumber => cellQr.columnNumber;
  String get locationLabel => cellQr.locationLabel;
  String get qrPayload => cellQr.qrPayload;
}

class QolipCodeQrPrintResult {
  const QolipCodeQrPrintResult({required this.qolipQr, required this.printJob});

  final QolipCodeQr qolipQr;
  final UsbRpsPrintRequest printJob;

  String get qolipCode => qolipQr.qolipCode;
  String get qrPayload => qolipQr.qrPayload;
  String get itemCode => qolipQr.itemCode;
  String get itemName => qolipQr.itemName;
  String get itemGroup => qolipQr.itemGroup;
  int get size => qolipQr.size;
}

UsbRpsPrintRequest _qolipCellUsbPrintJob(QolipCellQr cellQr) {
  return UsbRpsPrintRequest(
    epc: cellQr.qrPayload,
    itemCode: cellQr.qrPayload,
    itemName: _qolipCellLabel(cellQr),
    warehouse: cellQr.warehouse,
    printer: 'godex',
    printMode: 'label',
    grossQty: 1,
    unit: 'dona',
    labelKind: 'qolip_cell',
    progressQty: 1,
    progressUnit: 'dona',
  );
}

String _qolipCellLabel(QolipCellQr cellQr) {
  final row = cellQr.rowLetter.trim().toUpperCase();
  if (row.isNotEmpty && cellQr.columnNumber > 0) {
    return '$row${cellQr.columnNumber}';
  }
  return cellQr.locationLabel.trim();
}

UsbRpsPrintRequest _qolipCodeUsbPrintJob(QolipCodeQr qolipQr) {
  return UsbRpsPrintRequest(
    epc: qolipQr.qrPayload,
    itemCode: qolipQr.qolipCode,
    itemName: qolipQr.itemName,
    warehouse: 'ACCORD',
    printer: 'godex',
    printMode: 'label',
    grossQty: 1,
    unit: 'dona',
    labelKind: 'qolip_code',
    progressQty: 1,
    progressUnit: 'dona',
  );
}

MobileApiException _qolipCellQrException(http.Response response) {
  String code = 'qolip_cell_qr_lookup_failed';
  String message = 'Yachayka QR tekshirishda xatolik.';
  try {
    final data = jsonDecode(response.body);
    if (data is Map) {
      code = data['error']?.toString() ?? data['code']?.toString() ?? code;
      final serverMessage = data['message']?.toString() ?? '';
      if (serverMessage.trim().isNotEmpty) {
        message = serverMessage.trim();
      } else if (code == 'cell_qr_not_found') {
        message = 'Bu QR yachayka uchun topilmadi.';
      } else if (code == 'qr_required') {
        message = 'Yachayka QR bo‘sh.';
      }
    }
  } catch (_) {
    // Keep the user-facing fallback above.
  }
  return MobileApiException(
    code: code,
    message: message,
    statusCode: response.statusCode,
  );
}

MobileApiException _qolipApiException(
  http.Response response, {
  required String fallbackCode,
  required String fallbackMessage,
}) {
  var code = fallbackCode;
  var message = fallbackMessage;
  try {
    final data = jsonDecode(response.body);
    if (data is Map) {
      code = data['error']?.toString() ?? data['code']?.toString() ?? code;
      final serverMessage = data['message']?.toString() ?? '';
      if (serverMessage.trim().isNotEmpty) {
        message = serverMessage.trim();
      }
    }
  } catch (_) {
    // Keep fallback values.
  }
  return MobileApiException(
    code: code,
    message: message,
    statusCode: response.statusCode,
  );
}

String _testModeQolipCellQrPayload(String value) {
  var hash = BigInt.parse('cbf29ce484222325', radix: 16);
  final prime = BigInt.parse('100000001b3', radix: 16);
  final mask = BigInt.parse('ffffffffffffffff', radix: 16);
  for (final unit in value.trim().codeUnits) {
    hash = hash ^ BigInt.from(unit);
    hash = (hash * prime) & mask;
  }
  final checksum = hash & BigInt.from(0xffff);
  return '4002${hash.toRadixString(16).padLeft(16, '0').toUpperCase()}'
      '${checksum.toRadixString(16).padLeft(4, '0').toUpperCase()}';
}
